/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ABUnknownPersonViewControllerDelegate <NSObject>
-(void)unknownPersonViewController:(id)controller didResolveToPerson:(const void*)person;
@optional
-(BOOL)unknownPersonViewController:(id)controller shouldPerformDefaultActionForPerson:(const void*)person property:(int)property identifier:(int)identifier;
@end

