/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "ABUnknownPersonViewControllerDelegate.h"

@class NSString, ABUnknownPersonViewController;

__attribute__((visibility("hidden")))
@interface AddressBookNewContactViewController : XXUnknownSuperclass <ABUnknownPersonViewControllerDelegate> {
	ABUnknownPersonViewController* _legacyPersonViewController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) ABUnknownPersonViewController* legacyPersonViewController;
+(id)contactViewControllerWithPhone:(id)phone;
-(void).cxx_destruct;
-(BOOL)unknownPersonViewController:(id)controller shouldPerformDefaultActionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(void)unknownPersonViewController:(id)controller didResolveToPerson:(void*)person;
-(void)actionDismiss:(id)dismiss;
-(void)viewWillAppear:(BOOL)view;
-(id)initWithPerson:(void*)person;
@end

