/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"

@class NSString, VKRemoteImageAssetGroup;
@protocol VKRemoteAction;

__attribute__((visibility("hidden")))
@interface AppWidgetCoverListItem : VKRenderable {
	NSString* _title;
	NSString* _descr;
	VKRemoteImageAssetGroup* _cover;
	NSString* _buttonTitle;
	id<VKRemoteAction> _action;
	id<VKRemoteAction> _buttonAction;
}
@property(retain, nonatomic) id<VKRemoteAction> buttonAction;
@property(retain, nonatomic) id<VKRemoteAction> action;
@property(retain, nonatomic) NSString* buttonTitle;
@property(retain, nonatomic) VKRemoteImageAssetGroup* cover;
@property(retain, nonatomic) NSString* descr;
@property(retain, nonatomic) NSString* title;
-(void).cxx_destruct;
-(BOOL)process:(id)process context:(id)context;
@end

