/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMLiveController.h"
#import "VKClient-Structs.h"

@class AudioSelection, AudioListModel, VKIdentity;

__attribute__((visibility("hidden")))
@interface AudioListController : VKMLiveController {
	BOOL _multi;
	AudioSelection* _audioSelection;
	VKIdentity* _playlistFilterIden;
}
@property(retain, nonatomic) AudioListModel* model;
@property(retain, nonatomic) VKIdentity* playlistFilterIden;
@property(retain, nonatomic) AudioSelection* audioSelection;
@property(assign, nonatomic) BOOL multi;
-(void).cxx_destruct;
-(id)audioFromCell:(id)cell;
-(void)updateSelection;
-(void)model:(id)model updated:(id)updated;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didDeselectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view shouldHighlightRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)handleCell:(id)cell select:(BOOL)select;
-(id)VKMTableCreateSearchController80;
-(void)VKMTablePerformDeselectOnViewWillAppear:(BOOL)vkmtablePerformDeselectOnView;
-(BOOL)VKMRoute:(id)route context:(id)context;
-(int)VKMControllerModalAutoClosePosition;
-(void)handleAudioSelectionChanged:(id)changed;
-(void)twitchTitle;
-(void)updateDoneButton;
-(void)customizeTable:(id)table;
-(void)actionDone:(id)done;
-(void)viewDidLoad;
-(id)setupPlaylistFilterIden:(id)iden;
-(id)setupAudioSelection:(id)selection;
-(id)setupMulti:(BOOL)multi;
-(id)initWithMain:(id)main andModel:(id)model;
-(void)dealloc;
@end

