/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AudioCellAttach.h"
#import "VKClient-Structs.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface AudioCellAttachSearch : AudioCellAttach {
	UIImageView* _hqImage;
}
@property(retain, nonatomic) UIImageView* hqImage;
-(void).cxx_destruct;
-(id)audio;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(void)layoutSubviews;
-(id)createSubviews;
@end

