/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMCell.h"

@class AudioShuffleButton;

__attribute__((visibility("hidden")))
@interface AudioShuffleButtonCell : VKMCell {
}
@property(retain, nonatomic) AudioShuffleButton* domain;
-(void)layoutSubviews;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

