/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AutoplayedVideoViewDelegate <NSObject>
-(id)navDelegate;
-(void)videoViewBecameHidden:(id)hidden;
-(BOOL)videoViewToggleFullscreen:(id)fullscreen;
-(void)videoViewDidStartPlaying:(id)videoView;
-(void)videoViewDidFinishLoading:(id)videoView;
@end

