/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMCollectionCell.h"
#import "VKClient-Structs.h"

@class MarketGalleryImageView, UILabel, VKDomainWithCustomCellClass;
@protocol VKImageFilter;

__attribute__((visibility("hidden")))
@interface BaseMarketGalleryCell : VKMCollectionCell {
	MarketGalleryImageView* _imageView;
	UILabel* _topTitleLabel;
	UILabel* _bottomTitleLabel;
	id<VKImageFilter> _imageFilter;
}
@property(readonly, retain, nonatomic) VKDomainWithCustomCellClass* domain;
@property(readonly, retain, nonatomic) id<VKImageFilter> imageFilter;
@property(readonly, retain, nonatomic) UILabel* bottomTitleLabel;
@property(readonly, retain, nonatomic) UILabel* topTitleLabel;
@property(readonly, retain, nonatomic) MarketGalleryImageView* imageView;
+(CGSize)imageSize;
+(CGSize)cellSizeWithDomain:(id)domain widthConstraint:(float)constraint;
+(void)prerender:(id)prerender;
-(void).cxx_destruct;
-(void)setHighlighted:(BOOL)highlighted;
-(void)attachEntity:(id)entity expectedReuse:(double)reuse;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(void)prepareForReuse;
-(void)setOpaque:(BOOL)opaque;
-(void)setBackgroundColor:(id)color;
-(void)customizeSubviews;
-(id)createSubviews;
-(id)createImageFilter;
-(id)initWithFrame:(CGRect)frame;
@end

