/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "VKRenderable.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface BlockItem : VKRenderable <NSCoding> {
	NSString* _title;
	NSString* _photo;
	NSString* _link;
	int _type;
	Class _cellClass;
}
@property(retain, nonatomic) Class cellClass;
@property(assign, nonatomic) int type;
@property(retain, nonatomic) NSString* link;
@property(retain, nonatomic) NSString* photo;
@property(retain, nonatomic) NSString* title;
+(id)blockItemWithFriendDictionary:(id)friendDictionary;
+(id)blockItemWithDomain:(id)domain;
+(id)blockItemWithTitle:(id)title photo:(id)photo link:(id)link type:(int)type;
-(void).cxx_destruct;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)initWithTitle:(id)title photo:(id)photo link:(id)link type:(int)type;
@end

