/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TouchHighlightButton.h"
#import "VKClient-Structs.h"

@class UIFont;

__attribute__((visibility("hidden")))
@interface ButtonWithImage : TouchHighlightButton {
	UIFont* _titleFont;
	float _titleImageSpace;
}
@property(assign, nonatomic) float titleImageSpace;
@property(retain, nonatomic) UIFont* titleFont;
-(void).cxx_destruct;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)didMoveToSuperview;
-(CGSize)intrinsicContentSize;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(CGRect)titleRectForContentRect:(CGRect)contentRect;
-(id)initWithFrame:(CGRect)frame titleImageSpace:(float)space titleFont:(id)font;
@end

