/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ChatTableView : XXUnknownSuperclass {
	BOOL _needUpdateOffsets;
	NSDictionary* _rectsForVisibleRows;
}
@property(retain, nonatomic) NSDictionary* rectsForVisibleRows;
-(void).cxx_destruct;
-(CGPoint)vk_newContentOffsetAfterUpdates;
-(void)_setupCellAnimations;
-(void)_endCellAnimationsWithContext:(id)context;
@end

