/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class NSPointerArray, NSString;
@protocol Component5Delegate;

__attribute__((visibility("hidden")))
@interface Component5 : XXUnknownSuperclass {
	NSPointerArray* _stateListeners;
	NSString* _tag;
	id<Component5Delegate> _delegate;
	NSString* _identifier;
	id _state;
}
@property(retain, nonatomic) id state;
@property(readonly, assign, nonatomic) NSString* identifier;
@property(assign, nonatomic) __weak id<Component5Delegate> delegate;
@property(retain, nonatomic) NSString* tag;
+(void)performBlock:(id)block async:(BOOL)async;
+(void)performBlock:(id)block;
+(void)load;
+(Class)nodeClass;
+(Class)controllerClass;
-(void).cxx_destruct;
-(id)nodeWithContext:(id)context;
-(id)nodeForState:(id)state context:(id)context;
-(BOOL)isUtility;
-(id)preparedViewWithContext:(id)context;
-(id)viewWithContext:(id)context;
-(id)createView;
-(void)didUpdateState:(id)state toState:(id)state2 animated:(BOOL)animated;
-(void)willUpdateState:(id)state toState:(id)state2 animated:(BOOL)animated;
-(void)_updateState:(id)state animated:(BOOL)animated async:(BOOL)async;
-(void)updateStateSync:(id)sync;
-(void)updateStateSync:(id)sync animated:(BOOL)animated;
-(void)updateState:(id)state;
-(void)updateState:(id)state animated:(BOOL)animated;
-(void)removeStateListener:(id)listener;
-(void)addStateListener:(id)listener;
-(id)initWithState:(id)state;
-(id)initWithState:(id)state sizeConstraints:(XXStruct_JC2WWA)constraints;
-(id)init;
-(id)embedUnder:(id)under;
-(id)embedIn:(id)anIn horizontalAlignment:(int)alignment verticalAlignment:(int)alignment3;
-(id)embedInCenter:(id)center;
-(id)embedIn:(id)anIn;
-(id)backgroundColor:(id)color;
-(id)insetRight:(float)right;
-(id)insetLeft:(float)left;
-(id)insetBottom:(float)bottom;
-(id)insetTop:(float)top;
-(id)insetY:(float)y;
-(id)insetX:(float)x;
-(id)insets:(UIEdgeInsets)insets;
-(id)sizeConstraints:(XXStruct_JC2WWA)constraints;
-(id)aspectRatio:(float)ratio;
@end

