/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AnimatedIndexUpdate.h"


__attribute__((visibility("hidden")))
@interface DetailStaticIndexUpdate : AnimatedIndexUpdate {
}
-(void)applyForTableView:(id)tableView shouldReload:(BOOL)reload reload:(id)reload3;
@end

