/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet;
@protocol DiffTrackerDelegate;

__attribute__((visibility("hidden")))
@interface DiffTracker : XXUnknownSuperclass {
	NSSet* _current;
	id<DiffTrackerDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<DiffTrackerDelegate> delegate;
@property(copy, nonatomic) NSSet* current;
-(void).cxx_destruct;
-(void)added:(id)added deleted:(id)deleted;
-(void)update:(id)update;
@end

