/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class NSDictionary, UICollectionViewLayoutAttributes;

__attribute__((visibility("hidden")))
@interface DiscoverLayout : XXUnknownSuperclass {
	NSDictionary* _itemAttributesMap;
	NSDictionary* _decorationAttributes;
	UICollectionViewLayoutAttributes* _footerAttributes;
	CGSize _collectionViewContentSize;
}
@property(assign, nonatomic) CGSize collectionViewContentSize;
@property(retain, nonatomic) UICollectionViewLayoutAttributes* footerAttributes;
@property(retain, nonatomic) NSDictionary* decorationAttributes;
@property(retain, nonatomic) NSDictionary* itemAttributesMap;
-(void).cxx_destruct;
-(id)layoutAttributesForDecorationViewOfKind:(id)kind atIndexPath:(id)indexPath;
-(id)layoutAttributesForItemAtIndexPath:(id)indexPath;
-(id)layoutAttributesForElementsInRect:(CGRect)rect;
-(void)prepareLayout;
-(id)init;
@end

