/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"
#import "UIViewControllerAnimatedTransitioning.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface DiscoverToDetailTransition : XXUnknownSuperclass <UIViewControllerAnimatedTransitioning> {
	CGRect _fromRect;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) CGRect fromRect;
+(id)transitionFromViewController:(id)viewController toViewController:(id)viewController2;
-(void)animateTransition:(id)transition;
-(double)transitionDuration:(id)duration;
@end

