/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class NSString, UIFont;

__attribute__((visibility("hidden")))
@interface EditAttachmentStyle : XXUnknownSuperclass {
	BOOL _textShadow;
	NSString* _backgroundImage;
	NSString* _deleteImage;
	UIFont* _font1;
	UIFont* _font2;
	UIFont* _font3;
	float _cornerRadius;
	float _titlePadding;
	float _titleY;
	float _titleH1;
	float _titleH2;
	float _titleH3;
	CGSize _size;
	CGPoint _deleteOffset;
	UIEdgeInsets _borderInset;
	UIEdgeInsets _viewInset;
}
@property(assign, nonatomic) BOOL textShadow;
@property(assign, nonatomic) float titleH3;
@property(assign, nonatomic) float titleH2;
@property(assign, nonatomic) float titleH1;
@property(assign, nonatomic) float titleY;
@property(assign, nonatomic) float titlePadding;
@property(assign, nonatomic) CGPoint deleteOffset;
@property(assign, nonatomic) float cornerRadius;
@property(assign, nonatomic) UIEdgeInsets viewInset;
@property(assign, nonatomic) UIEdgeInsets borderInset;
@property(assign, nonatomic) CGSize size;
@property(retain, nonatomic) UIFont* font3;
@property(retain, nonatomic) UIFont* font2;
@property(retain, nonatomic) UIFont* font1;
@property(retain, nonatomic) NSString* deleteImage;
@property(retain, nonatomic) NSString* backgroundImage;
+(id)post;
+(id)messages;
-(void).cxx_destruct;
@end

