/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"


__attribute__((visibility("hidden")))
@interface ExtendedHitTestTextView : XXUnknownSuperclass {
	BOOL _hitTestOnlyInGlyphsBounds;
}
@property(assign, nonatomic) BOOL hitTestOnlyInGlyphsBounds;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

