/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PostInteractionStats.h"
#import "PrettyCardsStats.h"
#import "SnippetStats.h"
#import "PhotoStats.h"
#import "AudioStats.h"


@protocol FeedPostInteractionStats <PostInteractionStats, AudioStats, PhotoStats, SnippetStats, PrettyCardsStats>
@end

