/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ListModelContext.h"

@class NSIndexPath;

__attribute__((visibility("hidden")))
@interface FriendRequestsContext : ListModelContext {
	int _totalRequests;
	int _undeadRequests;
	NSIndexPath* _reloadPath;
	int _lastViewed;
}
@property(assign, nonatomic) int lastViewed;
@property(retain, nonatomic) NSIndexPath* reloadPath;
@property(assign, nonatomic) int undeadRequests;
@property(assign, nonatomic) int totalRequests;
-(void).cxx_destruct;
-(void)spawnCopy:(id)copy;
@end

