/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LoadingModel.h"


__attribute__((visibility("hidden")))
@interface FriendsRequestsModel : LoadingModel {
	int _currentFilter;
}
@property(assign, nonatomic) int currentFilter;
-(void)handleDeleteRequests:(id)requests :(id)arg2;
-(void)handleFriend:(id)aFriend :(id)arg2;
-(void)registerForEvents:(id)events;
-(id)componentForObject:(id)object withContext:(id)context;
-(BOOL)shouldLoad:(id)load;
-(void)updateIndexSections:(id)sections withContext:(id)context;
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(id)requestForContext:(id)context;
-(id)spawnContext:(id)context;
-(id)countKey;
-(void)setFilter:(int)filter;
-(id)setupFilter:(int)filter;
-(BOOL)isSameModel:(id)model;
@end

