/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKSelectorTableView.h"
#import "VKClient-Structs.h"


__attribute__((visibility("hidden")))
@interface FriendsSelector : VKSelectorTableView {
}
-(BOOL)willSelectOption:(id)option;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
@end

