/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SearchModel.h"

@class NSArray, Index, VKNewsSearchItem, NSDate;

__attribute__((visibility("hidden")))
@interface HintsSearchModel : SearchModel {
	BOOL _initialStale;
	Index* _initial;
	NSDate* _initialUpdated;
	NSArray* _newsHintsResults;
	VKNewsSearchItem* _newsSearchItem;
}
@property(retain) Index* initial;
@property(retain, nonatomic) VKNewsSearchItem* newsSearchItem;
@property(retain, nonatomic) NSArray* newsHintsResults;
@property(assign, nonatomic) BOOL initialStale;
@property(retain) NSDate* initialUpdated;
+(id)with:(id)with;
-(void).cxx_destruct;
-(void)model:(id)model updated:(id)updated;
-(BOOL)shouldLoad:(id)load;
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(id)countString;
-(id)requestForContext:(id)context;
@end

