/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SearchModelUpdater.h"

@class HintsSearchModel;

__attribute__((visibility("hidden")))
@interface HintsSearchModelUpdater : SearchModelUpdater {
}
@property(readonly, assign, nonatomic) HintsSearchModel* model;
@end

