/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"


__attribute__((visibility("hidden")))
@interface InteractiveMapComponent : Component5 {
}
-(id)createView;
-(void)configureView:(id)view withState:(id)state;
@end

