/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AuthModel;

__attribute__((visibility("hidden")))
@interface LandingPageController : XXUnknownSuperclass {
	AuthModel* _model;
	unsigned _sharedWebCredentialAvailability;
}
@property(retain, nonatomic) AuthModel* model;
@property(assign, nonatomic) unsigned sharedWebCredentialAvailability;
-(void).cxx_destruct;
-(void)actionLogIn:(id)anIn;
-(void)actionFacebook:(id)facebook;
-(void)actionSignUp:(id)up;
-(void)showLoginController;
-(int)preferredStatusBarStyle;
-(BOOL)shouldAutorotate;
-(void)tryToLoginWithLogin:(id)login password:(id)password keychainDomain:(id)domain;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
@end

