/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"

@class NSArray, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface LookupContactOther : VKRenderable {
	BOOL _invited;
	NSString* _subtitle;
	NSString* _firstName;
	NSString* _lastName;
	NSString* _imageUrlString;
	UIImage* _image;
	NSArray* _records;
}
@property(retain, nonatomic) NSArray* records;
@property(assign, nonatomic) BOOL invited;
@property(retain, nonatomic) UIImage* image;
@property(copy, nonatomic) NSString* imageUrlString;
@property(copy, nonatomic) NSString* lastName;
@property(copy, nonatomic) NSString* firstName;
@property(copy, nonatomic) NSString* subtitle;
-(void).cxx_destruct;
-(id)fullName;
-(Class)cellClass;
@end

