/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class VKMImageView, UILabel, UIButton;

__attribute__((visibility("hidden")))
@interface MainMenuPlayer : XXUnknownSuperclass {
	UIButton* _playerTouch;
	VKMImageView* _coverImageView;
	UIButton* _playButton;
	UIButton* _nextButton;
	UILabel* _titleLabel;
}
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UIButton* nextButton;
@property(retain, nonatomic) UIButton* playButton;
@property(retain, nonatomic) VKMImageView* coverImageView;
@property(retain, nonatomic) UIButton* playerTouch;
-(void).cxx_destruct;
-(void)highlightUpdated;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)clear;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

