/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MasksCacheDelegate.h"
#import "VKClient-Structs.h"

@class NSString, AFHTTPRequestOperation, MasksCache, WeakObservers, VKMask;

__attribute__((visibility("hidden")))
@interface MaskLoader : XXUnknownSuperclass <MasksCacheDelegate> {
	WeakObservers* _observers;
	VKMask* _currentMask;
	AFHTTPRequestOperation* _op;
	MasksCache* _masksCache;
	XXStruct_xAnk1C _progressBytes;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) XXStruct_xAnk1C progressBytes;
@property(retain, nonatomic) WeakObservers* observers;
@property(retain, nonatomic) MasksCache* masksCache;
@property(retain, nonatomic) AFHTTPRequestOperation* op;
@property(retain, nonatomic) VKMask* currentMask;
-(void).cxx_destruct;
-(void)masksCache:(id)cache cleanedMasksWithIden:(id)iden;
-(BOOL)isLoading;
-(void)cancel;
-(void)changeMaskAndLoadIfNeeded:(id)needed;
-(id)jsonPathForMaskIfCached:(id)maskIfCached;
-(unsigned)maskStateForMask:(id)mask;
-(id)init;
@end

