/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TouchHighlightButton.h"
#import "VKClient-Structs.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface MasksButtonRemove : TouchHighlightButton {
	UIImageView* _backgroundImageView;
	UIImageView* _imageView_vk;
}
@property(retain, nonatomic) UIImageView* imageView_vk;
@property(retain, nonatomic) UIImageView* backgroundImageView;
+(id)button;
-(void).cxx_destruct;
-(void)updateHighlight:(BOOL)highlight animated:(BOOL)animated;
@end

