/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class NSString, UILabel, UIFont;

__attribute__((visibility("hidden")))
@interface MBContactCollectionViewPromptCell : XXUnknownSuperclass {
	NSString* _prompt;
	UIFont* _font;
	UILabel* _promptLabel;
	UIEdgeInsets _insets;
}
@property(retain, nonatomic) UIFont* font;
@property(assign, nonatomic) UIEdgeInsets insets;
@property(copy, nonatomic) NSString* prompt;
@property(assign, nonatomic) __weak UILabel* promptLabel;
+(float)widthWithPrompt:(id)prompt;
-(void).cxx_destruct;
-(void)setup;
-(void)awakeFromNib;
-(id)initWithPrompt:(id)prompt;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
@end

