/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HintsCell.h"
#import "VKClient-Structs.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface MenuBirthdayCell : HintsCell {
	UIButton* _giftButton;
}
@property(retain, nonatomic) UIButton* giftButton;
+(void)prerender:(id)prerender;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(void)actionSendGift:(id)gift;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(float)photoSize;
-(float)photoPaddingTop;
-(UIEdgeInsets)labelEdgeInsets;
@end

