/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModelAction.h"

@class VKDomain;

__attribute__((visibility("hidden")))
@interface ModelActionRefresh : ModelAction {
}
@property(retain, nonatomic) VKDomain* target;
+(int)domainType;
-(void)runInContext:(id)context;
@end

