/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModelAction.h"

@class VKIdentity;

__attribute__((visibility("hidden")))
@interface MoneyCancelTransferAction : ModelAction {
	VKIdentity* _transferIden;
}
@property(readonly, assign, nonatomic) VKIdentity* transferIden;
+(int)domainType;
+(id)transfer:(id)transfer;
-(void).cxx_destruct;
-(BOOL)actionResultForData:(id)data context:(id)context;
-(id)actionRequestForContext:(id)context;
-(id)initWithTransferIden:(id)transferIden;
@end

