/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MTRGStatUtils : XXUnknownSuperclass {
}
+(void)sendProgressStatWithTime:(double)time statsArray:(id)array;
+(void)sendStatWithUrl:(id)url;
+(void)sendStatWithUrl:(id)url type:(id)type value:(id)value;
+(void)sendStats:(id)stats forType:(id)type;
@end

