/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MTRGAudioVastConverter : XXUnknownSuperclass {
}
+(id)companionBannerWithVastCompanionAd:(id)vastCompanionAd;
+(id)audioBannerFromVastInLineLinear:(id)lineLinear withBannerID:(id)bannerID;
+(void)convertVastInline:(id)anInline toAudioSection:(id)audioSection toAdData:(id)adData adService:(id)service;
+(void)convertVastWrapper:(id)wrapper forAdService:(id)adService;
+(void)convertVast:(id)vast audioSection:(id)section toAdData:(id)adData adService:(id)service;
@end

