/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MTRGResponseParser : XXUnknownSuperclass {
}
+(void)parseVast:(id)vast adData:(id)data adParams:(id)params adService:(id)service onSentry:(id)sentry;
+(void)parseRBData:(id)data adData:(id)data2 adParams:(id)params adService:(id)service onSentry:(id)sentry;
+(void)parseResponseWithString:(id)string adData:(id)data adParams:(id)params adService:(id)service;
+(void)parseResponseWithData:(id)data adData:(id)data2 adParams:(id)params adService:(id)service;
@end

