/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NotificationHandler.h"

@class NSString, NSDate;

__attribute__((visibility("hidden")))
@interface NHandlerVibration : XXUnknownSuperclass <NotificationHandler> {
	NSDate* _last;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSDate* last;
-(void).cxx_destruct;
-(void)clearImmediatly;
-(void)handle:(id)handle;
@end

