/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface NotificationSettings : VKRenderable {
	BOOL _isEnabled;
	NSString* _sid;
	NSString* _cid;
	NSString* _label;
	NSString* _details;
}
@property(assign, nonatomic) BOOL isEnabled;
@property(retain, nonatomic) NSString* details;
@property(retain, nonatomic) NSString* label;
@property(retain, nonatomic) NSString* cid;
@property(retain, nonatomic) NSString* sid;
-(void).cxx_destruct;
-(BOOL)process:(id)process context:(id)context;
@end

