/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMLiveController.h"
#import "VKClient-Structs.h"


__attribute__((visibility("hidden")))
@interface NotificationsSettingsController : VKMLiveController {
	BOOL _pushEnabled;
}
@property(assign, nonatomic) BOOL pushEnabled;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)actionSwitch:(id)aSwitch;
-(void)notificationAppActive:(id)active;
-(BOOL)VKMRoute:(id)route context:(id)context;
-(id)VKMScrollViewIndexFromModel:(id)model;
-(int)VKMTableStyle;
-(id)initWithMain:(id)main andModel:(id)model;
-(void)dealloc;
@end

