/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PagingViewDelegate <NSObject>
-(void)pagingView:(id)view scrollingProgress:(float)progress fromPage:(int)page toPage:(int)page4;
-(void)pagingView:(id)view didChangeCurrentPage:(int)page;
@end

