/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ListModelContext.h"

@class NSArray, VKDomain, VKPhoto, NSDictionary, NSNumber;
@protocol VKBrowsableImage;

__attribute__((visibility("hidden")))
@interface PhotoFeedContext : ListModelContext {
	BOOL _isStreamContext;
	VKDomain<VKBrowsableImage>* _initialPhoto;
	NSArray* _photos;
	NSNumber* _photosTotal;
	NSDictionary* _pendingDetails;
	VKPhoto* _emptyPhoto;
	unsigned _initial;
	int _statsContext;
}
@property(assign, nonatomic) int statsContext;
@property(assign, nonatomic) BOOL isStreamContext;
@property(assign, nonatomic) unsigned initial;
@property(retain, nonatomic) VKPhoto* emptyPhoto;
@property(retain, nonatomic) NSDictionary* pendingDetails;
@property(retain, nonatomic) NSNumber* photosTotal;
@property(retain, nonatomic) NSArray* photos;
@property(retain, nonatomic) VKDomain<VKBrowsableImage>* initialPhoto;
+(id)contextForPhoto:(id)photo list:(id)list source:(id)source;
+(id)duplicate:(id)duplicate;
-(void).cxx_destruct;
-(id)parsePhotosData:(id)data;
-(BOOL)canContainPhotoIdentity:(id)identity;
-(id)codeForNextPage;
-(void)spawnCopy:(id)copy;
-(BOOL)reorderPhoto:(id)photo after:(id)after before:(id)before;
-(BOOL)removePhotosWithIdentity:(id)identity;
-(void)prepend:(id)prepend;
-(void)addPhotos:(id)photos withData:(id)data;
-(void)addPhotos:(id)photos;
-(void)setupInitial:(id)initial;
@end

