/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class PopupWindow;

@protocol PopupWindowController <NSObject>
@property(assign, nonatomic) unsigned orientationMask;
@property(retain, nonatomic) PopupWindow* cyclePopupWindow;
-(void)popupWindow:(id)window present:(BOOL)present animated:(BOOL)animated completion:(id)completion;
@end

