/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ListModel.h"


__attribute__((visibility("hidden")))
@interface PushSourcesModel : ListModel {
	BOOL _needUpdate;
}
@property(assign, nonatomic) BOOL needUpdate;
-(void)handleSubscribe:(id)subscribe :(id)arg2;
-(void)registerForEvents:(id)events;
-(BOOL)shouldLoad:(id)load;
-(void)updateIndexSections:(id)sections withContext:(id)context;
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(id)request:(int)request count:(int)count;
-(id)countKey;
@end

