/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class ImageResourceGroup, ImageResource;

__attribute__((visibility("hidden")))
@interface Resources : XXUnknownSuperclass {
	ImageResourceGroup* _socialButtonLike;
	ImageResourceGroup* _socialButtonViews;
	ImageResourceGroup* _socialButtonComment;
	ImageResource* _socialButtonCommentSmall;
	ImageResourceGroup* _socialButtonShare;
	ImageResource* _verifiedAccountIcon;
	ImageResource* _trendingAccountIcon;
	ImageResource* _verifiedTrendingAccountIcon;
	ImageResource* _privatePostIcon;
	ImageResource* _pinnedPostIcon;
	ImageResource* _postSettingsIcon;
	ImageResource* _videoPlayBig;
	ImageResource* _playSmall;
	ImageResource* _recommendationsHide;
	ImageResource* _recommendationsCheck;
	ImageResource* _recommendationsAddFriend;
	ImageResource* _recommendationsAddGroup;
	ImageResource* _watermarkYoutube;
	ImageResource* _watermarkCoub;
	ImageResource* _watermarkRutube;
	ImageResource* _watermarkPladform;
	ImageResource* _watermarkVimeo;
	ImageResource* _appWidgetTime;
	ImageResource* _appWidgetLocation;
}
@property(retain, nonatomic) ImageResource* appWidgetLocation;
@property(retain, nonatomic) ImageResource* appWidgetTime;
@property(retain, nonatomic) ImageResource* watermarkVimeo;
@property(retain, nonatomic) ImageResource* watermarkPladform;
@property(retain, nonatomic) ImageResource* watermarkRutube;
@property(retain, nonatomic) ImageResource* watermarkCoub;
@property(retain, nonatomic) ImageResource* watermarkYoutube;
@property(retain, nonatomic) ImageResource* recommendationsAddGroup;
@property(retain, nonatomic) ImageResource* recommendationsAddFriend;
@property(retain, nonatomic) ImageResource* recommendationsCheck;
@property(retain, nonatomic) ImageResource* recommendationsHide;
@property(retain, nonatomic) ImageResource* playSmall;
@property(retain, nonatomic) ImageResource* videoPlayBig;
@property(retain, nonatomic) ImageResource* postSettingsIcon;
@property(retain, nonatomic) ImageResource* pinnedPostIcon;
@property(retain, nonatomic) ImageResource* privatePostIcon;
@property(retain, nonatomic) ImageResource* verifiedTrendingAccountIcon;
@property(retain, nonatomic) ImageResource* trendingAccountIcon;
@property(retain, nonatomic) ImageResource* verifiedAccountIcon;
@property(retain, nonatomic) ImageResourceGroup* socialButtonShare;
@property(retain, nonatomic) ImageResource* socialButtonCommentSmall;
@property(retain, nonatomic) ImageResourceGroup* socialButtonComment;
@property(retain, nonatomic) ImageResourceGroup* socialButtonViews;
@property(retain, nonatomic) ImageResourceGroup* socialButtonLike;
-(void).cxx_destruct;
@end

