/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class ExtraInputPanelView;

__attribute__((visibility("hidden")))
@interface RootView : XXUnknownSuperclass {
	ExtraInputPanelView* _inputPanelView;
}
@property(retain, nonatomic) ExtraInputPanelView* inputPanelView;
-(void).cxx_destruct;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

