/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ListModelContext.h"

@class SearchPeopleFilter;

__attribute__((visibility("hidden")))
@interface SearchPeopleModelContext : ListModelContext {
	SearchPeopleFilter* _filter;
}
@property(retain, nonatomic) SearchPeopleFilter* filter;
-(void).cxx_destruct;
-(void)spawnCopy:(id)copy;
@end

