/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "KeyboardAppearanceEventHandler.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIViewControllerTransitioningDelegate.h"

@class UIView, NSString, SendMessagePopupView, UIImage, KeyboardAppearanceObserver;

__attribute__((visibility("hidden")))
@interface SendMessagePopupViewController : XXUnknownSuperclass <KeyboardAppearanceEventHandler, UIViewControllerTransitioningDelegate> {
	BOOL _emptyMessageBodyAllowed;
	BOOL _hidesStatusBar;
	UIImage* _attachmentImage;
	UIView* _backdropView;
	SendMessagePopupView* _popupView;
	KeyboardAppearanceObserver* _keyboardAppearanceObserver;
	id _cancelAction;
	id _sendAction;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL emptyMessageBodyAllowed;
@property(retain, nonatomic) UIImage* attachmentImage;
@property(copy, nonatomic) id sendAction;
@property(copy, nonatomic) id cancelAction;
@property(assign, nonatomic) BOOL hidesStatusBar;
@property(retain, nonatomic) KeyboardAppearanceObserver* keyboardAppearanceObserver;
@property(retain, nonatomic) SendMessagePopupView* popupView;
@property(retain, nonatomic) UIView* backdropView;
+(id)sendMessagePopupViewControllerWithCancelAction:(id)cancelAction sendAction:(id)action;
-(void).cxx_destruct;
-(id)animationControllerForDismissedController:(id)dismissedController;
-(id)animationControllerForPresentedController:(id)presentedController presentingController:(id)controller sourceController:(id)controller3;
-(void)keyboardAppearanceObserver:(id)observer handleKeyboardAppearanceEventWithInfo:(id)info previouslyTrackedAppearanceInfo:(id)info3;
-(void)handleSendButtonTap;
-(void)handleCancelButtonTap;
-(void)handleBackdropTap;
-(void)layoutPopupViewWithKeyboardAppearanceInfo:(id)keyboardAppearanceInfo;
-(void)showInViewController:(id)viewController;
-(BOOL)prefersStatusBarHidden;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

