/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Renderer.h"

@class VKPrivacySetting;

__attribute__((visibility("hidden")))
@interface SettingsPrivacyRenderer : Renderer {
}
@property(retain, nonatomic) VKPrivacySetting* domain;
+(void)build:(id)build;
+(void)prepareLayout:(id)layout;
+(void)initialize;
+(id)rendererElements;
-(void)setupCell:(id)cell;
@end

