/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseSectionedSettingsController.h"
#import "VKClient-Structs.h"
#import "UITextFieldDelegate.h"

@class NSString, UILabel, AuthModel, VKMInputTextCell;

__attribute__((visibility("hidden")))
@interface SettingsChangePasswordController : BaseSectionedSettingsController <UITextFieldDelegate> {
	AuthModel* _authModel;
	VKMInputTextCell* _cellOldPassword;
	VKMInputTextCell* _cellNewPassword;
	VKMInputTextCell* _cellRepeatPassword;
	UILabel* _errorLabel;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) AuthModel* authModel;
@property(retain, nonatomic) UILabel* errorLabel;
@property(retain, nonatomic) VKMInputTextCell* cellRepeatPassword;
@property(retain, nonatomic) VKMInputTextCell* cellNewPassword;
@property(retain, nonatomic) VKMInputTextCell* cellOldPassword;
-(void).cxx_destruct;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)textFieldDidChange:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)actionSavePassword:(id)password;
-(void)resetSections;
-(void)resetBarButton;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(Class)cellClass;
@end

