/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UICollectionViewComponentState.h"
#import "VKClient-Structs.h"

@class NSArray, MOScrollPagingMediator;

__attribute__((visibility("hidden")))
@interface ShopProductGalleryCollectionViewComponentState : UICollectionViewComponentState {
	NSArray* _photos;
	MOScrollPagingMediator* _mediator;
}
@property(copy, nonatomic) NSArray* photos;
@property(retain, nonatomic) MOScrollPagingMediator* mediator;
-(void).cxx_destruct;
@end

