/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class VKMImageView;

__attribute__((visibility("hidden")))
@interface StickerSelectionCell : XXUnknownSuperclass {
	VKMImageView* _imageView;
}
@property(retain, nonatomic) VKMImageView* imageView;
-(void).cxx_destruct;
-(void)prepareForReuse;
-(void)setSelected:(BOOL)selected;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

