/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "StoryMediaPickerViewControllerDelegate.h"
#import "VKClient-Structs.h"
#import "CameraPreviewViewDelegate.h"
#import "CameraManagerDelegate.h"
#import "MaskAssetsLoaderDelegate.h"
#import "MaskLoaderObserver.h"
#import "MasksContainerControllerDelegate.h"
#import "VKMController.h"
#import "MaskLoaderDimProgressViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class VKMask, CameraPreviewView, CameraCaptureButton, MasksSectionsModel, MaskLoaderDimProgressView, UIView, UISwipeGestureRecognizer, UIButton, MasksButton, NSDate, MasksSwipeView, MaskAuthorView, NSTimer, KVOObserver, UILabel, MaskAssetsLoader, MasksContainerController, NSString, MaskLoader, UIImpactFeedbackGenerator, CameraManager, UILongPressGestureRecognizer;
@protocol StoryCameraViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface StoryCameraViewController : VKMController <CameraManagerDelegate, StoryMediaPickerViewControllerDelegate, UIGestureRecognizerDelegate, MasksContainerControllerDelegate, MaskLoaderObserver, CameraPreviewViewDelegate, MaskLoaderDimProgressViewDelegate, MaskAssetsLoaderDelegate> {
	BOOL _trackVolumeButtonForCapture;
	BOOL _skipVolumeChange;
	BOOL _masksPanelShown;
	BOOL _fromSwipe;
	BOOL _wasAppearedOnce;
	id<StoryCameraViewControllerDelegate> _delegate;
	CameraCaptureButton* _captureButton;
	UIButton* _cancelButton;
	UIButton* _flashModeButton;
	UIButton* _settingsButton;
	CameraManager* _cameraManager;
	CameraPreviewView* _cameraPreviewView;
	UIButton* _photoLibraryButton;
	UIButton* _flipCameraButton;
	UIView* _insertNoAccessViewAboveMeView;
	UILongPressGestureRecognizer* _captureButtonLongPressGesture;
	float _captureLongPressGestureBeginY;
	float _zoomFactorAtContinuedChangeBeginning;
	UIImpactFeedbackGenerator* _feedbackGenerator;
	NSTimer* _recordingProgressUpdateTimer;
	NSDate* _videoRecordingStartTime;
	NSDate* _videoRecordingStopTime;
	KVOObserver* _audioSessionObserver;
	float _initialSystemVolume;
	UIView* _volumeView;
	MasksSectionsModel* _masksSectionModel;
	MasksContainerController* _masksContainerController;
	MaskLoader* _maskLoader;
	MaskLoaderDimProgressView* _maskLoaderDimProgressView;
	MasksButton* _masksButton;
	UIButton* _masksRemoveButton;
	UISwipeGestureRecognizer* _maskPanelSwipeUpGesture;
	UISwipeGestureRecognizer* _maskPanelSwipeDownGesture;
	UILabel* _maskHintLabel;
	VKMask* _startingMask;
	MaskAssetsLoader* _maskAssetsLoader;
	MaskAuthorView* _maskAuthorView;
	MasksSwipeView* _masksSwipeView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) CameraCaptureButton* captureButton;
@property(assign, nonatomic) __weak id<StoryCameraViewControllerDelegate> delegate;
@property(assign, nonatomic) BOOL wasAppearedOnce;
@property(assign, nonatomic) BOOL fromSwipe;
@property(retain, nonatomic) MasksSwipeView* masksSwipeView;
@property(retain, nonatomic) MaskAuthorView* maskAuthorView;
@property(retain, nonatomic) MaskAssetsLoader* maskAssetsLoader;
@property(retain, nonatomic) VKMask* startingMask;
@property(retain, nonatomic) UILabel* maskHintLabel;
@property(retain, nonatomic) UISwipeGestureRecognizer* maskPanelSwipeDownGesture;
@property(retain, nonatomic) UISwipeGestureRecognizer* maskPanelSwipeUpGesture;
@property(retain, nonatomic) UIButton* masksRemoveButton;
@property(retain, nonatomic) MasksButton* masksButton;
@property(retain, nonatomic) MaskLoaderDimProgressView* maskLoaderDimProgressView;
@property(retain, nonatomic) MaskLoader* maskLoader;
@property(retain, nonatomic) MasksContainerController* masksContainerController;
@property(retain, nonatomic) MasksSectionsModel* masksSectionModel;
@property(assign, nonatomic) BOOL masksPanelShown;
@property(retain, nonatomic) UIView* volumeView;
@property(assign, nonatomic) BOOL skipVolumeChange;
@property(assign, nonatomic) float initialSystemVolume;
@property(retain, nonatomic) KVOObserver* audioSessionObserver;
@property(retain, nonatomic) NSDate* videoRecordingStopTime;
@property(retain, nonatomic) NSDate* videoRecordingStartTime;
@property(retain, nonatomic) NSTimer* recordingProgressUpdateTimer;
@property(assign, nonatomic) BOOL trackVolumeButtonForCapture;
@property(retain, nonatomic) UIImpactFeedbackGenerator* feedbackGenerator;
@property(assign, nonatomic) float zoomFactorAtContinuedChangeBeginning;
@property(assign, nonatomic) float captureLongPressGestureBeginY;
@property(retain, nonatomic) UILongPressGestureRecognizer* captureButtonLongPressGesture;
@property(retain, nonatomic) UIView* insertNoAccessViewAboveMeView;
@property(retain, nonatomic) UIButton* flipCameraButton;
@property(retain, nonatomic) UIButton* photoLibraryButton;
@property(retain, nonatomic) CameraPreviewView* cameraPreviewView;
@property(retain, nonatomic) CameraManager* cameraManager;
@property(retain, nonatomic) UIButton* settingsButton;
@property(retain, nonatomic) UIButton* flashModeButton;
@property(retain, nonatomic) UIButton* cancelButton;
-(void).cxx_destruct;
-(void)hideMaskHintLabel;
-(void)showMaskHintLabelWithText:(id)text;
-(void)showOrHideMaskHintLabelForMask:(id)mask;
-(void)model:(id)model willStartLoadingWithContext:(id)context;
-(void)modelLoadingChanged:(id)changed;
-(void)model:(id)model updated:(id)updated;
-(void)tryInitializeMaskAssetsLoaderIfNotAlready;
-(BOOL)statsMasksModelURLandModelVersionAreReady;
-(id)statsMasksModelVersion;
-(id)statsMasksModelURL;
-(void)dismissMaskLoaderDimProgressViewAndAttachSwipeGesturesToPreview;
-(void)presentMaskLoaderDimProgressViewAndAttachSwipeGesturesToIt;
-(void)tryEnableMasksButtonAndSwipeGestures;
-(void)applyMask:(id)mask withJsonPath:(id)jsonPath;
-(void)applyMaskAndDismissProgressIfBothAssetsAndMaskAreReady;
-(void)maskAssetsLoaderHandleFailedOrCanceled;
-(void)maskAssetsLoaderCanceled:(id)canceled;
-(void)maskAssetsLoaderFailed:(id)failed;
-(void)maskAssetsLoaderFinished:(id)finished;
-(void)maskAssetsLoaderUpdatedProgress:(id)progress;
-(void)maskLoader:(id)loader masksCacheCleanedMaskWithIden:(id)iden;
-(void)maskLoader:(id)loader canceledLoadingMask:(id)mask;
-(void)maskLoader:(id)loader failedLoadingMask:(id)mask;
-(void)maskLoader:(id)loader finishLoadingMask:(id)mask;
-(void)maskLoader:(id)loader loadingMask:(id)mask updatedProgress:(id)progress;
-(void)updateDimProgressViewProgress;
-(void)maskLoader:(id)loader startLoadingMask:(id)mask;
-(void)maskLoader:(id)loader changeCurrentMask:(id)mask;
-(void)masksContainerController:(id)controller didSelectMask:(id)mask;
-(void)changeMask:(id)mask;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(void)storyMediaPickerViewController:(id)controller didFinishWithAsset:(id)asset;
-(void)cameraManager:(id)manager changedMaskLoaded:(BOOL)loaded;
-(void)cameraManager:(id)manager didFinishRecordingToOutputFileAtURL:(id)url error:(id)error;
-(void)cameraManager:(id)manager didStarRecordingToOutputFileAtURL:(id)url;
-(void)cameraManager:(id)manager didProcessCapturedPhoto:(id)photo metadata:(id)metadata;
-(void)cameraManagerDidCapturePhoto:(id)cameraManager;
-(void)cameraManagerWillCapturePhoto:(id)cameraManager;
-(void)actionSettingsButton:(id)button;
-(void)actionGrantCameraAndMicAccessButton:(id)button;
-(void)animateToVideoRecordingState;
-(void)actionCaptureButtonLongPressGesture:(id)gesture;
-(void)actionCaptureButton:(id)button;
-(void)actionPhotoLibraryButton:(id)button;
-(void)actionFlipCameraButton:(id)button;
-(void)actionFlashModeButton:(id)button;
-(void)actionCancelButton:(id)button;
-(void)hideMaskPanel;
-(void)actionCameraPreviewTapGestureWhileMasksPanelIsShown:(id)shown;
-(void)showMasksPanelGUI;
-(void)actionMaskButtonOrSwipe:(id)swipe;
-(void)loadAssetsIntoMaskEngineIfTheyAreReady;
-(void)actionMasksRemoveButton:(id)button;
-(void)getLastPhoto:(id)photo;
-(void)showNeedsPhotosPermissionAlert;
-(void)presentMediaPickerViewController;
-(void)resetUIAfterRecording;
-(void)updateVideoRecordingProgress;
-(void)stopRecordingProgressUpdateTimer;
-(void)startRecordingProgressUpdateTimer;
-(void)unfreezeCameraPreview;
-(void)freezeCameraPreview;
-(void)stopVideoRecording;
-(void)startVideoRecording;
-(void)capturePhoto;
-(void)switchFlashMode;
-(void)flipCamera;
-(void)updateFlashModeAndFlipCameraButtonsAppearanceForCurrentCameraDevice;
-(void)setSystemVolume:(float)volume;
-(void)removeMPVolumeViewHidingSystemVolumeHUD;
-(void)addMPVolumeViewHidingSystemVolumeHUD;
-(void)notificationSystemVolumeDidChange:(id)notificationSystemVolume;
-(void)tearDownVolumeButtonHandler;
-(void)setupVolumeButtonHandler;
-(id)initialCameraConfig;
-(void)maskLoaderDimProgressViewBlankTap:(id)tap;
-(void)maskLoaderDimProgressViewPressCancel:(id)cancel;
-(void)cameraPreviewViewAttemptToFlipCamera:(id)flipCamera;
-(void)cameraPreviewView:(id)view attemptToFocusAtPoint:(CGPoint)point;
-(void)cameraPreviewView:(id)view attemptToZoomWithScale:(float)scale;
-(unsigned)supportedInterfaceOrientations;
-(int)preferredStatusBarUpdateAnimation;
-(int)preferredStatusBarStyle;
-(void)VKMControllerStatusBarUpdate:(BOOL)update;
-(BOOL)prefersStatusBarHidden;
-(void)showNoAccessView;
-(void)setPhotoLibraryButtonHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)setFlipCameraButtonHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)setFlashModeButtonHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)maskPanelSwipeGesture:(id)gesture;
-(void)actionMaskAuthorButton:(id)button;
-(void)swipeToMaskWithStepFromCurrent:(int)current;
-(void)viewDidLoad;
-(BOOL)masksAvailable;
-(id)initWithMain:(id)main andModel:(id)model startingMask:(id)mask fromSwipe:(BOOL)swipe;
-(void)dealloc;
@end

