/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ViewControllerCollectionViewCell.h"
#import "VKClient-Structs.h"

@class StoryFullscreenViewController;

__attribute__((visibility("hidden")))
@interface StoryFullscreenViewControllerCell : ViewControllerCollectionViewCell {
}
@property(readonly, assign, nonatomic) StoryFullscreenViewController* viewController;
+(id)instatiateViewController;
@end

