/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMAccessibilityTableView.h"


__attribute__((visibility("hidden")))
@interface TableViewWithoutTopSectionSeparator : VKMAccessibilityTableView {
	BOOL _hideAllTopSectionSeparators;
}
@property(assign, nonatomic) BOOL hideAllTopSectionSeparators;
-(BOOL)_shouldDrawSeparatorAtTopOfSection:(unsigned)section;
@end

