/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class TextKitLayer, CALayer;

__attribute__((visibility("hidden")))
@interface TextKitLabelLayer : XXUnknownSuperclass {
	TextKitLayer* _textLayer;
	CALayer* _backgroundLayer;
}
@property(readonly, assign, nonatomic) CALayer* backgroundLayer;
@property(readonly, assign, nonatomic) TextKitLayer* textLayer;
-(void).cxx_destruct;
-(void)layoutSublayers;
-(id)init;
@end

