/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TitleMenuCell.h"

@class VKMImageView;

__attribute__((visibility("hidden")))
@interface UserMenuCell : TitleMenuCell {
	VKMImageView* _image;
	VKMImageView* _onlineIcon;
}
@property(retain, nonatomic) VKMImageView* onlineIcon;
@property(retain, nonatomic) VKMImageView* image;
+(id)image:(id)image statId:(id)anId title:(id)title select:(id)select;
-(void).cxx_destruct;
-(void)renderUser:(id)user;
-(void)layoutSubviews;
-(void)dealloc;
@end

