/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSNumber;

__attribute__((visibility("hidden")))
@interface VideoAlbumsInfo : XXUnknownSuperclass {
	BOOL _forceAlbums;
	BOOL _hasUploaded;
	NSNumber* _ownerId;
	int _albumsCount;
}
@property(assign, nonatomic) int albumsCount;
@property(assign, nonatomic) BOOL hasUploaded;
@property(assign, nonatomic) BOOL forceAlbums;
@property(retain, nonatomic) NSNumber* ownerId;
-(void).cxx_destruct;
-(void)enumerateSections:(id)sections;
-(BOOL)hasSelection;
@end

