/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMCell.h"

@class VKMImageView, UILabel;

__attribute__((visibility("hidden")))
@interface VideoAlbumCell : VKMCell {
	VKMImageView* _thumbnailView;
	UILabel* _albumTitleLabel;
	UILabel* _countLabel;
}
@property(readonly, retain, nonatomic) UILabel* countLabel;
@property(readonly, retain, nonatomic) UILabel* albumTitleLabel;
@property(readonly, retain, nonatomic) VKMImageView* thumbnailView;
+(void)prerender:(id)prerender;
-(void).cxx_destruct;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

