/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"
#import "StatsData.h"

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ViewPostStatsData : XXUnknownSuperclass <StatsData> {
	NSMutableArray* _events;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* events;
-(void).cxx_destruct;
-(id)request;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)hasEvents;
-(id)JSONRepresentation;
-(void)viewPostWithId:(id)anId duration:(double)duration ref:(id)ref trackCode:(id)code;
-(void)viewPost:(id)post duration:(double)duration ref:(id)ref;
-(void)registerEvent:(id)event batch:(BOOL)batch;
-(id)init;
@end

