/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class UIViewController;

__attribute__((visibility("hidden")))
@interface ViewControllerCollectionViewCell : XXUnknownSuperclass {
	UIViewController* _viewController;
}
@property(readonly, assign, nonatomic) UIViewController* viewController;
+(id)instatiateViewController;
-(void).cxx_destruct;
-(void)removeViewControllerFromParentViewController;
-(void)addViewControllerToParentViewController:(id)parentViewController;
-(id)initWithFrame:(CGRect)frame;
@end

