/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VKAccountInfoVKLiveParams : VKRenderable {
	NSString* _scheme;
	NSString* _store_url;
}
@property(retain, nonatomic) NSString* store_url;
@property(retain, nonatomic) NSString* scheme;
-(void).cxx_destruct;
-(BOOL)process:(id)process context:(id)context;
@end

