/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class UIImageView, AVCaptureSession;

@interface VKAPCameraCollectionViewCell : XXUnknownSuperclass {
	AVCaptureSession* _session;
	UIImageView* _cameraIcon;
}
@property(retain, nonatomic) AVCaptureSession* session;
@property(retain, nonatomic) UIImageView* cameraIcon;
-(void).cxx_destruct;
-(id)initWithFrame:(CGRect)frame;
@end

