/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MOSQLite, NSDictionary, NSObject, NSNumber;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface VKDB : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _queue;
	NSNumber* _oid;
	MOSQLite* _db;
	NSDictionary* _states;
}
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* queue;
@property(retain, nonatomic) MOSQLite* db;
@property(retain, nonatomic) NSNumber* oid;
@property(retain) NSDictionary* states;
-(void)friendLoadUpcomingBirthdays:(id)birthdays;
-(void)friendList:(id)list add:(BOOL)add user:(id)user;
-(void)friendUpsert:(id)upsert;
-(void)friendDelete:(id)aDelete;
-(void)friendLoadBirthdays:(id)birthdays;
-(void)friendLoad:(id)load list:(id)list;
-(void)friendReset:(id)reset list:(id)list;
-(void)flistUpsert:(id)upsert;
-(void)flistDelete:(id)aDelete;
-(void)flistLoad:(id)load;
-(void)flistReset:(id)reset;
-(void)_usersAdd:(id)add;
-(BOOL)validateFriendsCount:(int)count;
-(BOOL)stateFriendsFresh;
-(int)state:(int)state;
-(BOOL)stateMissing:(int)missing;
-(BOOL)state:(int)state dateMissingOrOlder:(int)older;
-(void)_stateUpdateDateNow:(int)now;
-(void)_stateUpdate:(int)update value:(int)value;
-(BOOL)stateLoaded;
-(void)_notify:(id)notify;
-(void)logSchema;
-(void)load;
-(BOOL)_schemaApply;
-(BOOL)_migrate;
-(void)dealloc;
-(id)initWithPath:(id)path;
@end

