/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomainDerived.h"

@class NSString, VKDomain;
@protocol VKSource;

__attribute__((visibility("hidden")))
@interface VKMenuSubtitleItem : VKDomainDerived {
	NSString* _subtitle;
	int _flags;
}
@property(assign, nonatomic) int flags;
@property(retain, nonatomic) NSString* subtitle;
@property(retain, nonatomic) VKDomain<VKSource>* domain;
-(void).cxx_destruct;
@end

