/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MainModel, AFHTTPRequestOperation, NSMutableArray, NSObject;
@protocol VKMLoaderDelegate, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface VKMLoader : XXUnknownSuperclass {
	int offset;
	int discover;
	BOOL cancelled;
	BOOL touched;
	NSObject<OS_dispatch_queue>* queue;
	BOOL _complete;
	MainModel* _main;
	NSMutableArray* _items;
	id<VKMLoaderDelegate> _delegate;
	AFHTTPRequestOperation* _op;
}
@property(assign, nonatomic) __weak id<VKMLoaderDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL complete;
@property(readonly, retain, nonatomic) MainModel* main;
@property(retain, nonatomic) NSMutableArray* items;
@property(retain, nonatomic) AFHTTPRequestOperation* op;
-(void).cxx_destruct;
-(void)cancel;
-(void)discover:(int)discover;
-(void)touch;
-(void)load;
-(id)processResultsInBackground:(id)background data:(id)data;
-(id)requestForOffset:(int)offset count:(int)count success:(id)success failure:(id)failure;
-(id)initWithMain:(id)main;
@end

