/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMSiteAction.h"

@class NSURL;

__attribute__((visibility("hidden")))
@interface VKMNeedValidationSiteAction : VKMSiteAction {
	NSURL* _redirect_url;
	id _handler;
}
@property(copy, nonatomic) id handler;
@property(retain, nonatomic) NSURL* redirect_url;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)complete:(int)complete userId:(id)anId token:(id)token;
-(void)cancel;
-(id)targetURL;
-(void)dealloc;
@end

