/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MainModel, VKIdentity, VKMController, UINavigationController, StatsRef, StatContext;
@protocol VKMNavRoot;

__attribute__((visibility("hidden")))
@interface VKMNavContext : XXUnknownSuperclass {
	BOOL _preserveModal;
	BOOL _preserveStatsContext;
	MainModel* _main;
	id<VKMNavRoot> _rootNav;
	UINavigationController* _navController;
	VKMController* _controller;
	VKIdentity* _sourceIden;
	StatContext* _statsContext;
	StatsRef* _statsRef;
}
@property(assign, nonatomic) BOOL preserveStatsContext;
@property(assign, nonatomic) BOOL preserveModal;
@property(retain, nonatomic) StatsRef* statsRef;
@property(retain, nonatomic) StatContext* statsContext;
@property(retain, nonatomic) VKIdentity* sourceIden;
@property(retain, nonatomic) VKMController* controller;
@property(retain, nonatomic) UINavigationController* navController;
@property(retain, nonatomic) id<VKMNavRoot> rootNav;
@property(retain, nonatomic) MainModel* main;
+(id)applicationNavRoot;
-(void).cxx_destruct;
-(id)prevViewController;
-(id)topViewController;
-(BOOL)routeSource:(id)source;
-(BOOL)routeSourceObject:(id)object;
-(BOOL)routeURL:(id)url browser:(BOOL)browser;
-(BOOL)routeLink:(id)link browser:(BOOL)browser;
-(BOOL)handleRouteResult:(id)result browser:(BOOL)browser;
-(void)safariVC:(id)vc;
-(void)webAppBrowser:(id)browser;
-(void)browser:(id)browser;
-(void)presentStoryFullscreenControllerWithUsersStoryIdens:(id)usersStoryIdens startFromPage:(int)page fromSource:(id)source;
-(void)presentStoriesEditorViewControllerWithMask:(id)mask;
-(void)presentVideoPlayerViewControllerForVideo:(id)video adsItem:(id)item fromFeedVideoView:(id)feedVideoView navDelegate:(id)delegate;
-(void)presentVideoPlayerViewControllerForVideo:(id)video;
-(void)photoFeed:(id)feed thumbnails:(id)thumbnails;
-(void)dismissModal:(BOOL)modal completion:(id)completion;
-(void)dismissModal:(BOOL)modal;
-(void)modal:(id)modal animated:(BOOL)animated;
-(void)modal:(id)modal resolver:(id)resolver animated:(BOOL)animated transitionDelegate:(id)delegate modalPresentationStyle:(int)style;
-(void)modal:(id)modal resolver:(id)resolver animated:(BOOL)animated;
-(void)swapTopViewController:(id)controller;
-(void)hideModalsAnimated:(BOOL)animated completeBlock:(id)block;
-(void)pop;
-(void)pop:(BOOL)pop;
-(void)popTo:(id)to animated:(BOOL)animated;
-(void)popTo:(id)to;
-(void)push:(id)push;
-(void)push:(id)push animated:(BOOL)animated;
-(void)push:(id)push resolver:(id)resolver animated:(BOOL)animated;
-(void)replace:(id)replace;
-(void)reset:(id)reset;
-(void)resetMulti:(id)multi;
-(id)withPreserveStatsContext:(BOOL)preserveStatsContext;
-(void)clearModals;
-(id)foregroundModel;
-(BOOL)isCurrentContext;
@end

