/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"

@protocol PrettyCardsStats;

__attribute__((visibility("hidden")))
@interface VKPrettyCardsComponent : Component5 {
	id<PrettyCardsStats> _stats;
}
@property(retain, nonatomic) id<PrettyCardsStats> stats;
+(id)cards:(id)cards stats:(id)stats;
-(void).cxx_destruct;
-(id)nodeForState:(id)state context:(id)context;
-(id)cards;
@end

