/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomain.h"

@class VKAdData, VKRemoteActionOpenUrl, VKAppInternalNotificationButton, NSString, VKRemoteImageAssetGroup;

__attribute__((visibility("hidden")))
@interface VKPrettyCardsCard : VKDomain {
	NSString* _card_id;
	NSString* _title;
	NSString* _price;
	NSString* _price_old;
	NSString* _card_data;
	VKAdData* _adData;
	VKRemoteImageAssetGroup* _images;
	VKAppInternalNotificationButton* _button;
	VKRemoteActionOpenUrl* _action;
}
@property(retain, nonatomic) VKRemoteActionOpenUrl* action;
@property(retain, nonatomic) VKAppInternalNotificationButton* button;
@property(retain, nonatomic) VKRemoteImageAssetGroup* images;
@property(retain, nonatomic) VKAdData* adData;
@property(retain, nonatomic) NSString* card_data;
@property(retain, nonatomic) NSString* price_old;
@property(retain, nonatomic) NSString* price;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* card_id;
-(void).cxx_destruct;
-(BOOL)process:(id)process context:(id)context;
@end

