/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"


__attribute__((visibility("hidden")))
@interface VKSubscriptionPromoParagraphView : XXUnknownSuperclass {
}
-(id)initWithFrame:(CGRect)frame image:(id)image title:(id)title stringAttachImage:(id)image4;
-(id)initWithFrame:(CGRect)frame image:(id)image title:(id)title;
@end

