export THEOS_DEVICE_IP=192.168.0.104
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VkMessagesLock
VkMessagesLock_FILES = Tweak.xm
VkMessagesLock_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
