THEOS_DEVICE_IP=192.168.0.102
include $(THEOS)/makefiles/common.mk

export THEOS_DEVICE_IP=192.168.0.102

TWEAK_NAME = iappsDefender
iappsDefender_FILES = Tweak.xm Activation/Activation.m Activation/ActivationKeyAlert.m
iappsDefender_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk

