include $(THEOS)/makefiles/common.mk
export THEOS_DEVICE_IP=192.168.0.103

TWEAK_NAME = EnglishAudioLearn
EnglishAudioLearn_FILES = Tweak.xm
EnglishAudioLearn_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
