export THEOS_DEVICE_IP=192.168.0.102
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Facetune2Hack
Facetune2Hack_FILES = Tweak.xm
Facetune2Hack_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweakNO.mk
