export THEOS_DEVICE_IP=192.168.0.105
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VKVoiceChanger
VKVoiceChanger_FILES = Tweak.xm
VKVoiceChanger_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
