/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "Cydia-Structs.h"


__attribute__((visibility("hidden")))
@interface CydiaLoadingView : UIView {
	MenesObjectHandle<UIActivityIndicatorView, 0> spinner_;
	MenesObjectHandle<UILabel, 0> label_;
	MenesObjectHandle<UIView, 0> container_;
}
-(id).cxx_construct;
-(void).cxx_destruct;
-(id)initWithFrame:(CGRect)frame;
@end

