/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Cydia-Structs.h"


__attribute__((visibility("hidden")))
@interface CydiaOperation : NSObject {
	MenesObjectHandle<NSString, 0> operator_;
	MenesObjectHandle<NSString, 0> value_;
}
+(BOOL)isKeyExcludedFromWebScript:(const char*)webScript;
+(id)_attributeKeys;
-(id).cxx_construct;
-(void).cxx_destruct;
-(id)value;
-(id)operator;
-(id)attributeKeys;
-(id)initWithOperator:(const char*)anOperator value:(const char*)value;
@end

