/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "Cydia-Structs.h"


__attribute__((visibility("hidden")))
@interface CyteViewController : UIViewController {
	id delegate_;
	BOOL loaded_;
	MenesObjectHandle<UIColor, 0> color_;
}
-(id).cxx_construct;
-(void).cxx_destruct;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)setPageColor:(id)color;
-(id)navigationURL;
-(void)unloadData;
-(void)reloadData;
-(void)setView:(id)view;
-(void)releaseSubviews;
-(BOOL)hasLoaded;
-(void)viewWillAppear:(BOOL)view;
-(id)delegate;
-(void)setDelegate:(id)delegate;
@end

