include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VKMessageDecoder
VKMessageDecoder_FILES = Tweak.xm
VKMessageDecoder_FRAMEWORKS = UIKit Foundation CoreFoundation

include $(THEOS_MAKE_PATH)/tweak.mk

SUBPROJECTS += vkmessagedecoderprefs
include $(THEOS_MAKE_PATH)/aggregate.mk
