export THEOS_DEVICE_IP=192.168.0.100
export THEOS_DEVICE_PORT=22

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = MimoHack
MimoHack_FILES = Tweak.xm
MimoHack_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
