include $(THEOS)/makefiles/common.mk
export THEOS_DEVICE_IP=192.168.0.103

TWEAK_NAME = NewVKAppTabBarMode
NewVKAppTabBarMode_FILES = Tweak.xm
NewVKAppTabBarMode_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk

