include $(THEOS)/makefiles/common.mk

TWEAK_NAME = InstaLikesIDSelector
InstaLikesIDSelector_FILES = Tweak.xm
InstaLikesIDSelector_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
SUBPROJECTS += instalikesidselectsettings
include $(THEOS_MAKE_PATH)/aggregate.mk
