/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ActionOptionsProviderActionBuilder.h"

@class VKPost;

__attribute__((visibility("hidden")))
@interface ActionOptionsProviderPost : ActionOptionsProviderActionBuilder {
	BOOL _share;
	BOOL _control;
	BOOL _publish;
	BOOL _popOndelete;
	VKPost* _post;
}
@property(readonly, assign, nonatomic) BOOL popOndelete;
@property(readonly, assign, nonatomic) BOOL publish;
@property(readonly, assign, nonatomic) BOOL control;
@property(readonly, assign, nonatomic) BOOL share;
@property(readonly, assign, nonatomic) VKPost* post;
+(id)optionsForDetailPost:(id)detailPost;
+(id)optionsForPost:(id)post;
+(id)publishOptionsForPost:(id)post;
+(id)shareOptionsForPost:(id)post;
+(id)optionsForPost:(id)post share:(BOOL)share control:(BOOL)control publish:(BOOL)publish popOnDelete:(BOOL)aDelete;
-(void).cxx_destruct;
-(void)fillOptionsForBuilder:(id)builder context:(id)context;
@end

