/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMLiveController.h"
#import "vkclient-Structs.h"
#import "ApplicationModelDelegate.h"

@class AppFriendsInviter, ApplicationModel, NSString;

__attribute__((visibility("hidden")))
@interface AppBaseController : VKMLiveController <ApplicationModelDelegate> {
	BOOL tracked;
	AppFriendsInviter* _friendsInviter;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) ApplicationModel* model;
@property(retain, nonatomic) AppFriendsInviter* friendsInviter;
-(void).cxx_destruct;
-(id)actionContextForApplicationModel:(id)applicationModel;
-(void)actionsButtonTapped:(id)tapped;
-(void)model:(id)model updated:(id)updated;
-(BOOL)route:(id)route;
-(void)openFriendsSelectionScreenForApp:(id)app;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(int)VKMTableStyle;
-(int)VKMTableSearchMode;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(id)initWithMain:(id)main andModel:(id)model;
-(void)dealloc;
@end

