/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMCell.h"

@class UILabel, VKAPIAppWithFriendsPlaying, NSMutableArray;

__attribute__((visibility("hidden")))
@interface AppFriendsPlayingCell : VKMCell {
	UILabel* _friendsPlayingLabel;
	NSMutableArray* _avatars;
}
@property(readonly, retain, nonatomic) VKAPIAppWithFriendsPlaying* domain;
@property(readonly, retain, nonatomic) NSMutableArray* avatars;
@property(readonly, retain, nonatomic) UILabel* friendsPlayingLabel;
+(void)prerender:(id)prerender;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(id)createSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

