/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomain.h"

@class Index, NSString, UIColor;

__attribute__((visibility("hidden")))
@interface AppsListDomain : VKDomain {
	Class _cellClass;
	Class _applicationCellClass;
	Index* _applications;
	NSString* _title;
	UIColor* _galleryBackgroundColor;
}
@property(readonly, assign, nonatomic) Class applicationCellClass;
@property(readonly, retain, nonatomic) UIColor* galleryBackgroundColor;
@property(copy, nonatomic) NSString* title;
@property(retain, nonatomic) Index* applications;
-(Class)cellClass;
-(id)domainFilteredWithPredicate:(id)predicate;
-(BOOL)process:(id)process context:(id)context;
-(void)dealloc;
@end

