/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DomainEditAttachment.h"
#import "vkclient-Structs.h"

@class VKAudio;

__attribute__((visibility("hidden")))
@interface AudioEditAttachment : DomainEditAttachment {
}
@property(retain, nonatomic) VKAudio* domain;
-(void)renderView:(id)view;
-(id)createViewForStyle:(XXStruct_9zIMjA)style;
@end

