/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AudioRenderer.h"
#import "vkclient-Structs.h"


__attribute__((visibility("hidden")))
@interface AudioRendererAttach : AudioRenderer {
}
+(id)pickAudioImageUrl:(id)url;
+(void)t;
+(id)rendererElements;
-(id)audio;
-(BOOL)cellSelected:(id)selected;
@end

