/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PhotoUploadContext.h"
#import "vkclient-Structs.h"

@class NSDictionary, NSData, VKIdentity;

__attribute__((visibility("hidden")))
@interface AudioPlaylistCoverPhotoUploadContext : PhotoUploadContext {
	VKIdentity* _playlistIden;
	NSDictionary* _cropParams;
	NSData* _preparedData;
	CGAffineTransform _forcedCrop;
}
@property(retain, nonatomic) VKIdentity* playlistIden;
@property(retain, nonatomic) NSData* preparedData;
@property(retain, nonatomic) NSDictionary* cropParams;
@property(assign, nonatomic) CGAffineTransform forcedCrop;
+(id)photoContextWithSession:(id)session assetData:(id)data;
-(id)createOperation;
-(id)requestForSaving:(id)saving;
-(BOOL)handleResultServerData:(id)data uploadData:(id)data2 saveData:(id)data3;
-(id)uploadBodyFieldName;
-(id)requestForUploadServer;
-(void)willUseImage:(id)image;
-(void)loadUploadData:(id)data;
-(void)dealloc;
@end

