/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DefaultHighlightButton.h"
#import "vkclient-Structs.h"

@class CAShapeLayer, UIColor;

__attribute__((visibility("hidden")))
@interface AudioOverlayButton : DefaultHighlightButton {
	UIColor* _circleFillColor;
	float _overlayCornerRadius;
	UIColor* _overlayFillColor;
	CAShapeLayer* _overlayLayer;
	CAShapeLayer* _roundLayer;
	CGSize _circleSize;
}
@property(retain, nonatomic) UIColor* overlayFillColor;
@property(assign, nonatomic) float overlayCornerRadius;
@property(retain, nonatomic) UIColor* circleFillColor;
@property(assign, nonatomic) CGSize circleSize;
@property(retain, nonatomic) CAShapeLayer* roundLayer;
@property(retain, nonatomic) CAShapeLayer* overlayLayer;
-(void)layoutSubviews;
-(void)createSublayers;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

