/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"

@class NSNumber, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface AudioBlock : VKRenderable {
	NSNumber* _blockId;
	NSString* _title;
	NSString* _subtitle;
	NSString* _source;
	float _contentOffsetXForRestoringInReusableCell;
}
@property(assign, nonatomic) float contentOffsetXForRestoringInReusableCell;
@property(readonly, assign, nonatomic) NSArray* items;
@property(copy, nonatomic) NSString* source;
@property(copy, nonatomic) NSString* subtitle;
@property(copy, nonatomic) NSString* title;
@property(retain, nonatomic) NSNumber* blockId;
-(void).cxx_destruct;
-(BOOL)process:(id)process context:(id)context;
@end

