/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMLiveController.h"
#import "vkclient-Structs.h"

@class AudioCatalogModel;

__attribute__((visibility("hidden")))
@interface AudioCatalogController : VKMLiveController {
}
@property(retain, nonatomic) AudioCatalogModel* model;
-(void)model:(id)model updated:(id)updated;
-(void)actionSearch:(id)search;
-(BOOL)VKMRoute:(id)route context:(id)context;
-(id)audioAudiosSpecialBlockHeaderView;
-(void)viewDidLoad;
-(id)initWithMain:(id)main andModel:(id)model;
@end

