/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMLiveController.h"
#import "vkclient-Structs.h"

@class AudioAlbumModel;

__attribute__((visibility("hidden")))
@interface AudioAlbumController : VKMLiveController {
}
@property(retain, nonatomic) AudioAlbumModel* model;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(id)tableView:(id)view targetIndexPathForMoveFromRowAtIndexPath:(id)indexPath toProposedIndexPath:(id)proposedIndexPath;
-(BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(void)audioRendererSelectedAudio:(id)audio cell:(id)cell quick:(BOOL)quick;
-(int)VKMControllerModalAutoClosePosition;
-(int)VKMLiveAudioContext;
-(void)viewDidLoad;
-(void)VKMTableUpdatedIndex;
@end

