/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Model.h"
#import "RMOpusPlayerDelegate.h"
#import "AVAudioSessionDelegate.h"

@class VKAudioMessage, NSString, RMOpusPlayer, AFHTTPRequestOperation;

__attribute__((visibility("hidden")))
@interface AudioMessagePlayer : Model <RMOpusPlayerDelegate, AVAudioSessionDelegate> {
	VKAudioMessage* _audioMessage;
	RMOpusPlayer* _player;
	int _state;
	AFHTTPRequestOperation* _downloadOp;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int state;
@property(retain, nonatomic) RMOpusPlayer* player;
@property(retain, nonatomic) AFHTTPRequestOperation* downloadOp;
@property(retain, nonatomic) VKAudioMessage* audioMessage;
+(id)with:(id)with audioMessage:(id)message;
-(void)opusPlayerDidFinishPlaying:(id)opusPlayer;
-(void)switchTo:(int)to;
-(void)downloadAndPlay;
-(void)actualPlay;
-(void)stop;
-(void)pause;
-(void)play;
-(void)dealloc;
@end

