/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AttachmentView.h"
#import "AudioPlayerObserver.h"
#import "vkclient-Structs.h"

@class AudioPlayer, NSString, VKAudio, UIButton, UILabel;
@protocol AudioAttachmentDelegate;

__attribute__((visibility("hidden")))
@interface AudioAttachmentView : AttachmentView <AudioPlayerObserver> {
	VKAudio* _audio;
	id<AudioAttachmentDelegate> _delegate;
	AudioPlayer* _player;
	UIButton* _button;
	UILabel* _duration;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) id<AudioAttachmentDelegate> delegate;
@property(retain, nonatomic) VKAudio* audio;
@property(retain, nonatomic) UILabel* duration;
@property(retain, nonatomic) UIButton* button;
@property(retain, nonatomic) AudioPlayer* player;
-(void)model:(id)model willStartLoadingWithContext:(id)context;
-(void)modelLoadingChanged:(id)changed;
-(void)model:(id)model updated:(id)updated;
-(void)playerChangedItem:(id)item;
-(void)playerUpdated:(id)updated;
-(void)toggle:(id)toggle;
-(void)update;
-(void)render:(id)render;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame main:(id)main duration:(BOOL)duration;
@end

