/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ListModel.h"


__attribute__((visibility("hidden")))
@interface AudioPlaylistsModel : ListModel {
	BOOL _attachMode;
	int _filter;
}
@property(assign, nonatomic, getter=isAudioAttachMode) BOOL attachMode;
@property(assign, nonatomic) int filter;
+(id)requestWithOwner:(id)owner filter:(int)filter;
+(id)requestWithOwner:(id)owner;
-(void)fillActionsForBuilder:(id)builder playlist:(id)playlist;
-(void)editPlaylist:(id)playlist builder:(id)builder;
-(void)deletePlaylist:(id)playlist builder:(id)builder;
-(void)updateUnfollowPlaylist:(id)playlist builder:(id)builder;
-(void)updateFollowPlaylist:(id)playlist withFollowedIden:(id)followedIden builder:(id)builder;
-(void)addPlaylist:(id)playlist source:(id)source builder:(id)builder;
-(void)handleReorderAudioPlaylists:(id)playlists :(id)arg2;
-(void)handleUpdateAudioPlaylistCover:(id)cover :(id)arg2;
-(void)handleEditAudioPlaylist:(id)playlist :(id)arg2;
-(void)handleAddAudioPlaylist:(id)playlist :(id)arg2;
-(void)handleDeleteAudioPlaylist:(id)playlist :(id)arg2;
-(void)handleFollowAudioPlaylist:(id)playlist :(id)arg2;
-(void)registerForEvents:(id)events;
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(id)process:(id)process;
-(id)request:(int)request count:(int)count;
-(id)countKey;
-(id)setupAttachMode;
-(id)setupSearch;
-(id)setupFilter:(int)filter;
-(BOOL)isManagedPlaylistsSection;
-(id)spawnContext:(id)context;
@end

