/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AudioBlockCellWithCollectionViewItemCell.h"
#import "VKClient-Structs.h"
#import "VKMCollectionCell.h"

@class UILabel, NSString, VKMImageView;

__attribute__((visibility("hidden")))
@interface AudioImageAndTitleItemCollectionCell : VKMCollectionCell <AudioBlockCellWithCollectionViewItemCell> {
	VKMImageView* _imageView;
	UILabel* _titleLabel;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) VKMImageView* imageView;
+(CGSize)cellSize;
-(void).cxx_destruct;
-(void)prepareForReuse;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

