/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LoadingModel.h"
#import "AVAudioSessionDelegate.h"

@class AVPlayer, MOPlaylist, AVPlayerItem, VKAudio, UIImage, NSOperation, BackgroundTaskWrapper, NSString;

__attribute__((visibility("hidden")))
@interface AudioPlayer : LoadingModel <AVAudioSessionDelegate> {
	BOOL active;
	BOOL remote;
	AVPlayer* _player;
	AVPlayerItem* _playerItem;
	MOPlaylist* _playlist;
	VKAudio* _audio;
	int _state;
	UIImage* _coverImage;
	NSOperation* _op;
	BackgroundTaskWrapper* _task;
	int _context;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIImage* coverImage;
@property(assign, nonatomic) int state;
@property(retain, nonatomic) VKAudio* audio;
@property(retain, nonatomic) MOPlaylist* playlist;
@property(retain) AVPlayerItem* playerItem;
@property(retain) AVPlayer* player;
@property(assign, nonatomic) int context;
@property(readonly, retain, nonatomic) BackgroundTaskWrapper* task;
@property(retain, nonatomic) NSOperation* op;
+(id)requestForAudio:(id)audio handler:(id)handler;
+(void)updateNowPlaying:(id)playing;
-(BOOL)isPlaying;
-(BOOL)isCurrentAudio:(id)audio;
-(BOOL)isPlayingAudio:(id)audio;
-(void)playList:(id)list from:(id)from toggle:(BOOL)toggle force:(BOOL)force context:(int)context;
-(void)previous;
-(void)next;
-(void)advance:(BOOL)advance force:(BOOL)force;
-(void)toggle;
-(void)stop;
-(void)pause;
-(void)play;
-(void)playFromStart;
-(void)startPlayback;
-(void)playDelayed:(id)delayed;
-(void)handleAssetMetadata;
-(void)reset:(BOOL)reset force:(BOOL)force stop:(BOOL)stop;
-(void)cancel;
-(void)switchTo:(int)to force:(BOOL)force;
-(void)broadcastCancel;
-(void)broadcast;
-(void)broadcastDelayed:(id)delayed;
-(void)playCurrent;
-(void)playURL:(id)url;
-(void)complete:(id)complete;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)handleRemoteControlEvent:(id)event;
-(void)notificationAudioSessioInterruption:(id)interruption;
-(void)deactivate;
-(void)activate;
-(void)dealloc;
-(id)initWithSession:(id)session;
@end

