/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKClient-Structs.h"
#import "TrackingBoundsView.h"
#import "VKThumbnailView.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "VKVideoPlayerViewDelegate.h"

@class UIImage, NSURL, VKDomain, RoundedProgressOverlayView, NSString, UIActivityIndicatorView, VKAVVideoPlayerView, VKMImageView;
@protocol VKThumbnailable, AutoplayedVideoViewDelegate;

__attribute__((visibility("hidden")))
@interface AutoplayedBaseView : XXUnknownSuperclass <VKVideoPlayerViewDelegate, VKThumbnailView, TrackingBoundsView> {
	BOOL _autoplay;
	BOOL _started;
	id<AutoplayedVideoViewDelegate> _delegate;
	VKMImageView* _previewImage;
	VKAVVideoPlayerView* _playerView;
	RoundedProgressOverlayView* _progressOverlay;
	VKDomain<VKThumbnailable>* _domain;
	int _renderedSize;
	float _trackingBoundsPercentsVisible;
	UIActivityIndicatorView* _activity;
	NSURL* _currentURL;
}
@property(readonly, assign, nonatomic) UIImage* image;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) float trackingBoundsPercentsVisible;
@property(assign, nonatomic) int renderedSize;
@property(retain, nonatomic) VKDomain<VKThumbnailable>* domain;
@property(readonly, assign, nonatomic) RoundedProgressOverlayView* progressOverlay;
@property(readonly, assign, nonatomic) VKAVVideoPlayerView* playerView;
@property(readonly, assign, nonatomic) VKMImageView* previewImage;
@property(assign, nonatomic) __weak id<AutoplayedVideoViewDelegate> delegate;
@property(assign, nonatomic) BOOL started;
@property(assign, nonatomic) BOOL autoplay;
@property(retain, nonatomic) NSURL* currentURL;
@property(retain, nonatomic) UIActivityIndicatorView* activity;
-(void).cxx_destruct;
-(void)setLooped:(BOOL)looped;
-(void)play;
-(void)renderPlayerURL:(id)url;
-(void)viewTrackingBoundsDidChange:(float)viewTrackingBounds previousValue:(float)value;
-(BOOL)shouldDisplayWithPriority;
-(void)videoPlayerPositionUpdated:(id)updated;
-(void)videoPlayerReadyToKeepUp:(id)keepUp;
-(void)videoPlayerIsStalling:(id)stalling;
-(void)videoPlayerFailedForDisplay:(id)display;
-(BOOL)videoPlayerCanStartPlaying:(id)playing;
-(void)videoPlayerDidDisplayVideoLayer:(id)videoPlayer;
-(void)attach:(id)attach previewVariant:(id)variant;
-(int)previewAspectMode;
-(void)attachPreview:(id)preview;
-(void)pause;
-(void)reuse;
-(void)setupProgressThin:(BOOL)thin;
-(void)renderVideoHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)tapped:(id)tapped;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

