/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKClient-Structs.h"
#import "AutoplayedBaseView.h"

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface AutoplayedVideoView : AutoplayedBaseView {
	UILabel* _durationLabel;
	UIImageView* _playButton;
}
@property(retain, nonatomic) UIImageView* playButton;
@property(retain, nonatomic) UILabel* durationLabel;
-(void).cxx_destruct;
-(void)videoPlayerFailedForDisplay:(id)display;
-(void)videoPlayerPositionUpdated:(id)updated;
-(void)videoPlayerDidDisplayVideoLayer:(id)videoPlayer;
-(void)renderVideoHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)attach:(id)attach previewVariant:(id)variant;
-(void)tapped:(id)tapped;
-(int)previewAspectMode;
-(BOOL)shouldDisplayWithPriority;
-(id)initWithFrame:(CGRect)frame;
@end

