/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, Brush, UISlider;

__attribute__((visibility("hidden")))
@interface BrushSizeSlider : XXUnknownSuperclass {
	UISlider* _slider;
	Brush* _brush;
	UIView* _brushPreview;
}
@property(retain, nonatomic) Brush* brush;
@property(assign, nonatomic) float maximumValue;
@property(assign, nonatomic) float minimumValue;
@property(assign, nonatomic) float value;
@property(retain, nonatomic) UISlider* slider;
@property(retain, nonatomic) UIView* brushPreview;
-(void).cxx_destruct;
-(id)initWithFrame:(CGRect)frame;
@end

