/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CameraCaptureButtonTip, EmptyStateView, UIButton, CameraCaptureButton, UIImageView;

__attribute__((visibility("hidden")))
@interface CameraControlsView : XXUnknownSuperclass {
	CameraCaptureButton* _captureButton;
	UIButton* _photoLibraryButton;
	UIButton* _flipCameraButton;
	UIButton* _flashButton;
	EmptyStateView* _noAccessView;
	CameraCaptureButtonTip* _captureButtonTip;
	UIImageView* _focusView;
}
@property(retain, nonatomic) EmptyStateView* noAccessView;
@property(retain, nonatomic) UIButton* flashButton;
@property(retain, nonatomic) UIImageView* focusView;
@property(retain, nonatomic) UIButton* flipCameraButton;
@property(retain, nonatomic) UIButton* photoLibraryButton;
@property(retain, nonatomic) CameraCaptureButtonTip* captureButtonTip;
@property(retain, nonatomic) CameraCaptureButton* captureButton;
-(void).cxx_destruct;
-(void)showNoAccessView;
-(void)setPhotoLibraryButtonAssetImage:(id)image;
-(void)showFocusViewAtPoint:(CGPoint)point andHideAfterDelay:(double)delay;
-(void)setCameraCaptureButtonTipHidden:(BOOL)hidden animated:(BOOL)animated delay:(double)delay;
-(void)hideCameraCaptureButtonTip;
-(void)showCameraCaptureButtonTipAfterDelay:(double)delay;
-(void)setPhotoLibraryButtonHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)setFlipCameraButtonHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)setFlashButtonHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)initializeNoAccessView;
-(void)initializeFocusView;
-(void)initializePhotoLibraryButton;
-(void)initializeFlipCameraButton;
-(void)initializeCaptureButton;
-(void)initializeSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

