/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKClient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, CAShapeLayer;

__attribute__((visibility("hidden")))
@interface CameraCaptureButton : XXUnknownSuperclass {
	unsigned _captureButtonState;
	float _progress;
	UIView* _containerView;
	CAShapeLayer* _mainCircleLayer;
	CAShapeLayer* _progressCircleLayer;
}
@property(retain, nonatomic) UIView* containerView;
@property(assign, nonatomic) float progress;
@property(assign, nonatomic) unsigned captureButtonState;
@property(retain, nonatomic) CAShapeLayer* progressCircleLayer;
@property(retain, nonatomic) CAShapeLayer* mainCircleLayer;
+(id)buttonWithDefaultFrameSize;
+(float)diameterForCaptureButtonState:(unsigned)captureButtonState;
+(float)lineWidthForCaptureButtonState:(unsigned)captureButtonState;
-(void).cxx_destruct;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setCaptureButtonState:(unsigned)state animated:(BOOL)animated;
-(id)bezierPathForCaptureButtonState:(unsigned)captureButtonState;
-(id)bezierPathForCaptureButtonState:(unsigned)captureButtonState progress:(float)progress;
-(id)initWithFrame:(CGRect)frame;
@end

