/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMGroupedCell.h"


__attribute__((visibility("hidden")))
@interface ChatEditItemLeaveCell : VKMGroupedCell {
}
+(void)prerender:(id)prerender;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

