/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKGroupedItem.h"


__attribute__((visibility("hidden")))
@interface ChatEditItemLeave : VKGroupedItem {
	BOOL _participant;
}
@property(assign, nonatomic) BOOL participant;
-(Class)cellClass;
@end

