/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKGroupedItem.h"


__attribute__((visibility("hidden")))
@interface ChatEditItemPushSound : VKGroupedItem {
	BOOL _enabled;
	BOOL _on;
}
@property(assign, nonatomic) BOOL on;
@property(assign, nonatomic) BOOL enabled;
-(Class)cellClass;
@end

