/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKGroupedItem.h"


__attribute__((visibility("hidden")))
@interface ChatEditItemAttachments : VKGroupedItem {
}
-(Class)cellClass;
@end

