/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "MessageCell.h"
#import "MessageRendererDelegate.h"

@class UILabel, VKMImageView, NSString, UIImageView, MessageRenderer;

__attribute__((visibility("hidden")))
@interface ChatCell : MessageCell <MessageRendererDelegate> {
	BOOL _callout;
	MessageRenderer* _renderer;
	UIImageView* _bg;
	UILabel* _time;
	VKMImageView* _avatar;
	UIImageView* _sent;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL callout;
@property(retain, nonatomic) UILabel* time;
@property(retain, nonatomic) UIImageView* bg;
@property(retain, nonatomic) MessageRenderer* renderer;
@property(retain, nonatomic) UIImageView* sent;
@property(retain, nonatomic) VKMImageView* avatar;
+(void)prerender:(id)prerender multi:(BOOL)multi;
+(void)initialize;
-(id)messageNavigation;
-(void)actionMultiUserTapped:(id)tapped;
-(void)messageUpdated:(id)updated;
-(void)updateReadState;
-(CGPoint)accessoryPosition;
-(BOOL)isAccessibilityElement;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(void)willTransitionToState:(unsigned)state;
-(CGRect)bounds;
-(void)prepareForReuse;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setBG;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)dealloc;
-(id)initWithDelegate:(id)delegate multidialog:(BOOL)multidialog selfdialog:(BOOL)selfdialog identifier:(id)identifier;
@end

