/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LoadingModel.h"

@class ChatEditModelContext, NSString, NSSet, NSNumber;

__attribute__((visibility("hidden")))
@interface ChatEditModel : LoadingModel {
	NSString* _changeTitle;
	NSSet* _addUsers;
	NSNumber* _removeUser;
	NSNumber* _pushSound;
	NSNumber* _pushMute;
}
@property(retain, nonatomic) NSNumber* pushMute;
@property(retain, nonatomic) NSNumber* pushSound;
@property(retain, nonatomic) NSNumber* removeUser;
@property(retain, nonatomic) NSSet* addUsers;
@property(retain, nonatomic) NSString* changeTitle;
@property(retain, nonatomic) ChatEditModelContext* lastContext;
+(void)fillMuteVariants:(id)variants withCompleteVariant:(id)completeVariant;
+(id)requestForEditChat:(id)editChat title:(id)title add:(id)add remove:(id)remove sound:(id)sound mute:(id)mute deviceId:(id)anId;
-(void)invalidateChatUsers;
-(void)updateTitle:(id)title add:(id)add remove:(id)remove sound:(id)sound mute:(id)mute;
-(void)handleUserKick:(id)kick :(id)arg2;
-(BOOL)shouldLoad:(id)load;
-(id)componentForObject:(id)object withContext:(id)context;
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(id)requestForContext:(id)context;
-(id)spawnContext:(id)context;
-(void)registerForEvents:(id)events;
-(void)dealloc;
@end

