/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ListModel.h"


__attribute__((visibility("hidden")))
@interface CheckinsModel : ListModel {
}
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(id)request:(int)request count:(int)count;
-(id)countKey;
-(id)spawnContext:(id)context;
@end

