/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "vkclient-Structs.h"
#import "NSCopying.h"

@class Component5Node, ReusableViewsPool;
@protocol VKMNavDelegate;

__attribute__((visibility("hidden")))
@interface Component5Context : XXUnknownSuperclass <NSCopying> {
	ReusableViewsPool* _viewPool;
	Component5Node* _node;
	id<VKMNavDelegate> _navDelegate;
	double _reuse;
}
@property(assign, nonatomic) __weak id<VKMNavDelegate> navDelegate;
@property(assign, nonatomic) double reuse;
@property(retain, nonatomic) Component5Node* node;
@property(retain, nonatomic) ReusableViewsPool* viewPool;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
@end

