/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface CustomCellBackgroundView : XXUnknownSuperclass {
	UIEdgeInsets insets;
	CGGradientRef gradient_;
	int _position;
	UIColor* _borderColor;
	UIColor* _fillColor;
}
@property(retain, nonatomic) UIColor* fillColor;
@property(retain, nonatomic) UIColor* borderColor;
@property(assign, nonatomic) int position;
+(CGGradientRef)defaultBlueGradient;
+(CGGradientRef)whiteGradient;
+(CGGradientRef)blackGradient;
-(void)drawRect:(CGRect)rect;
-(BOOL)isOpaque;
-(void)useGradient:(CGGradientRef)gradient;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

