/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ItemModel.h"

@class Index;

__attribute__((visibility("hidden")))
@interface DefaultProfileModel : ItemModel {
	Index* _profileInfoIndex;
	id _completedItem;
}
@property(retain, nonatomic) id completedItem;
@property(retain, nonatomic) Index* profileInfoIndex;
-(id)recreateProfileIndex:(id)index;
-(void)renderProfileInfo;
-(id)componentForContentItem:(id)contentItem;
-(id)componentForGiftsItem:(id)giftsItem;
-(id)componentForProfileItem:(id)profileItem;
-(id)componentForObject:(id)object withContext:(id)context;
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(void)dealloc;
@end

