/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface DetailMoreCell : XXUnknownSuperclass {
	UILabel* _label;
}
@property(retain, nonatomic) UILabel* label;
-(void).cxx_destruct;
-(void)renderMore:(int)more total:(int)total;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

