/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, UILabel;

__attribute__((visibility("hidden")))
@interface DetailCounter : XXUnknownSuperclass {
	UILabel* _title;
	UIImage* _normal;
	UIImage* _selected;
}
@property(retain, nonatomic) UIImage* selected;
@property(retain, nonatomic) UIImage* normal;
@property(retain, nonatomic) UILabel* title;
+(float)widthWithTitle:(id)title;
-(void).cxx_destruct;
-(id)initWithImageName:(id)imageName;
@end

