/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DomainEditAttachment.h"

@class VKDoc;

__attribute__((visibility("hidden")))
@interface DocEditAttachment : DomainEditAttachment {
}
@property(retain, nonatomic) VKDoc* domain;
-(void)renderView:(id)view;
-(id)createViewForStyle:(id)style;
@end

