/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UploadEditAttachment.h"

@class DocsPhotoUploadContext;

__attribute__((visibility("hidden")))
@interface DocsPhotoUploadEditAttachment : UploadEditAttachment {
}
@property(retain, nonatomic) DocsPhotoUploadContext* context;
-(float)defaultAttachmentRenderHeight;
-(float)domainAttachmentImageRatio;
-(id)createViewForStyle:(id)style;
@end

