/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UploadEditAttachment.h"
#import "vkclient-Structs.h"

@class VKAudioMessage, DocsAudioMessageUploadContext;

__attribute__((visibility("hidden")))
@interface DocsAudioMessageUploadEditAttachment : UploadEditAttachment {
}
@property(retain, nonatomic) VKAudioMessage* domain;
@property(retain, nonatomic) DocsAudioMessageUploadContext* context;
@end

