/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UploadEditAttachment.h"
#import "vkclient-Structs.h"

@class DocsSketchUploadContext, ClientBasedUploadOperation;

__attribute__((visibility("hidden")))
@interface DocsSketchUploadEditAttachment : UploadEditAttachment {
}
@property(readonly, retain, nonatomic) ClientBasedUploadOperation* operation;
@property(retain, nonatomic) DocsSketchUploadContext* context;
-(id)domain;
@end

