/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class UIView;

@protocol DraggableAttachment <NSObject>
@property(readonly, assign, nonatomic) float maxZoomScale;
@property(readonly, assign, nonatomic) float minZoomScale;
@property(assign, nonatomic) float rotation;
@property(assign, nonatomic) float zoomScale;
@property(readonly, assign, nonatomic) BOOL horizontalPanAllowed;
@property(readonly, assign, nonatomic) BOOL verticalPanAllowed;
@property(readonly, assign, nonatomic) BOOL pannable;
@property(readonly, assign, nonatomic) BOOL rotatable;
@property(readonly, assign, nonatomic) BOOL zoomable;
@property(readonly, assign, nonatomic) UIView* view;
@optional
-(BOOL)canBeginInteractions;
-(void)didEndInteractions;
-(void)willBeginInteractions;
@end

