/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class Component5;

__attribute__((visibility("hidden")))
@interface EmbedComponentState : XXUnknownSuperclass {
	BOOL _under;
	Component5* _container;
	Component5* _componentToEmbed;
}
@property(assign, nonatomic) BOOL under;
@property(retain, nonatomic) Component5* componentToEmbed;
@property(retain, nonatomic) Component5* container;
-(void).cxx_destruct;
@end

