/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface EventManager : XXUnknownSuperclass {
}
+(void)fireEvent:(id)event session:(id)session context:(id)context;
+(id)contextFromNotification:(id)notification;
+(id)eventFromNotification:(id)notification;
@end

