/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MultiIndexModel.h"

@class Index;

__attribute__((visibility("hidden")))
@interface FavUsersModel : MultiIndexModel {
	Index* _online;
	Index* _all;
}
@property(retain, nonatomic) Index* all;
@property(retain, nonatomic) Index* online;
-(void)handleFavorites:(id)favorites :(id)arg2;
-(id)removeFavorite:(id)favorite updateBuilder:(id)builder;
-(id)addFavorite:(id)favorite updateBuilder:(id)builder;
-(id)editingActionForIndex:(id)index withIndexPath:(id)indexPath;
-(int)editingStyleForForTable:(id)table index:(id)index indexPath:(id)path;
-(id)countKeyForMode:(unsigned)mode;
-(id)indexForMode:(unsigned)mode;
-(unsigned)modes;
-(void)registerForEvents:(id)events;
-(id)updatedIndex:(id)index data:(id)data context:(id)context;
-(id)requestForContext:(id)context;
-(id)countKey;
-(void)dealloc;
@end

