/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString, NSArray;

@protocol FBAuthRequest <NSObject>
@property(readonly, retain, nonatomic) NSString* apiVersion;
@property(readonly, retain, nonatomic) NSArray* permissions;
@property(readonly, retain, nonatomic) NSString* appId;
-(id)authParameters;
@end

