/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface FBAuthResponse : XXUnknownSuperclass {
	NSString* _token;
	NSArray* _permissions;
}
@property(retain, nonatomic) NSArray* permissions;
@property(retain, nonatomic) NSString* token;
+(id)responseWithCallbackURL:(id)callbackURL error:(id*)error;
+(id)responseWithToken:(id)token permissions:(id)permissions;
-(void).cxx_destruct;
-(id)description;
@end

