/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBAuthStrategy.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol URLInteropHandler;

__attribute__((visibility("hidden")))
@interface FBURLInteropAuthStrategy : XXUnknownSuperclass <FBAuthStrategy> {
	id<URLInteropHandler> _interopHandler;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) id<URLInteropHandler> interopHandler;
-(void).cxx_destruct;
-(id)targetURLForRequest:(id)request;
-(void)attemptAuth:(id)auth handler:(id)handler;
-(id)initWithInteropHandler:(id)interopHandler;
@end

