/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface FixedNavigationController : XXUnknownSuperclass {
}
-(id)childForStatusBar;
-(BOOL)prefersStatusBarHidden;
-(int)preferredStatusBarStyle;
-(id)childViewControllerForStatusBarStyle;
-(id)childViewControllerForStatusBarHidden;
-(void)notificationWindowDidBecomeKeyWindow:(id)notificationWindow;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

