/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "EditAttachment.h"

@class NSMutableSet, NSMutableArray;

__attribute__((visibility("hidden")))
@interface FwdEditAttachment : EditAttachment {
	NSMutableSet* _mids;
	NSMutableArray* _messages;
}
@property(retain, nonatomic) NSMutableArray* messages;
@property(retain, nonatomic) NSMutableSet* mids;
-(void)addMessages:(id)messages;
-(void)renderView:(id)view;
-(id)createViewForStyle:(XXStruct_9zIMjA)style;
-(void)dealloc;
@end

