/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Renderer.h"

@class GiftSendButtonRenderable;

__attribute__((visibility("hidden")))
@interface GiftSendButtonRenderer : Renderer {
}
@property(retain, nonatomic) GiftSendButtonRenderable* domain;
+(void)build:(id)build;
+(void)prepareLayout:(id)layout;
+(void)t;
+(id)rendererElements;
-(void)setupCell:(id)cell;
-(void)sendGift:(id)gift;
@end

