/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ProfileWallController.h"
#import "VKProfileMarketGalleryDelegate.h"

@class GroupModel, VKHUD, NSString;

__attribute__((visibility("hidden")))
@interface GroupWallController : ProfileWallController <VKProfileMarketGalleryDelegate> {
	GroupModel* _profile;
	VKHUD* _actionHUD;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) VKHUD* actionHUD;
@property(retain, nonatomic) GroupModel* profile;
-(void)profileMarketGallery:(id)gallery didSelectProduct:(id)product;
-(void)profileMarketGalleryDidTapShowAll:(id)profileMarketGallery;
-(void)modelLoadingChanged:(id)changed;
-(void)model:(id)model updated:(id)updated;
-(void)actionProfileAppButton:(id)button;
-(void)actionProfileInfo:(id)info;
-(void)actionShowActions:(id)actions;
-(void)actionProfileViewBlock:(id)block;
-(id)controllerForBlock:(int)block;
-(void)actionProfileViewStatus:(id)status;
-(void)actionProfileViewMessage:(id)message;
-(void)actionProfileViewProfilePhoto:(id)photo;
-(void)clearHUD:(BOOL)hud;
-(id)VKMControllerStatsRef;
-(void)VKMScrollViewReset;
-(void)VKMControllerTouch;
-(int)VKMLiveAudioContext;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(BOOL)postOptionsEnabled;
-(id)postContext;
-(void)updateProfile;
-(void)dealloc;
-(id)initWithMain:(id)main andGroup:(id)group;
@end

