/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "IGLResource.h"
#import "IGLTexture.h"
#import "vkclient-Structs.h"
#import "IGLResource.h"

@class NSString;

@protocol IGLTexture <IGLResource>
-(void)readImage:(id)image;
-(void)loadWithSize:(CGSize)size;
-(CGSize)size;
-(unsigned)texture;
@end

@interface IGLTexture : IGLResource <IGLTexture> {
	unsigned gl_texture;
	CGSize size;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)loadWithCGImage:(CGImageRef)cgimage;
-(void)readImage:(id)image;
-(void)loadWithSize:(CGSize)size;
-(CGSize)size;
-(unsigned)texture;
-(void)loadWithSize:(CGSize)size data:(void*)data;
-(void)unload;
@end

