/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5Controller.h"

@class ImageLoaderComponent, VKMImageView;

__attribute__((visibility("hidden")))
@interface ImageLoaderComponentController : Component5Controller {
}
@property(assign, nonatomic) __weak VKMImageView* view;
@property(retain, nonatomic) ImageLoaderComponent* component;
+(id)createView;
@end

