/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"

@class ImageResource;

__attribute__((visibility("hidden")))
@interface ImageResourceComponent : Component5 {
}
@property(retain, nonatomic) ImageResource* state;
+(id)imageResource:(id)resource;
-(id)nodeForState:(id)state context:(id)context;
@end

