/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5Controller.h"

@class ImageComponent, UIImageView;

__attribute__((visibility("hidden")))
@interface ImageComponentController : Component5Controller {
}
@property(assign, nonatomic) __weak UIImageView* view;
@property(retain, nonatomic) ImageComponent* component;
+(id)createView;
@end

