/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UniformContext, UIImage, Bezier;

__attribute__((visibility("hidden")))
@interface LayerDrawer : XXUnknownSuperclass {
	Bezier* _bezier;
	UniformContext* _uniformContext;
	UIImage* _brushImage;
	UIImage* _neonBrushCentreImage;
	float _scale;
	CGRect _rect;
}
@property(assign, nonatomic) CGRect rect;
@property(assign, nonatomic) float scale;
@property(retain, nonatomic) UIImage* neonBrushCentreImage;
@property(retain, nonatomic) UIImage* brushImage;
@property(retain, nonatomic) UniformContext* uniformContext;
@property(retain, nonatomic) Bezier* bezier;
-(void).cxx_destruct;
-(id)drawBezier:(id)bezier fromPoint:(unsigned)point withUniformContext:(id)uniformContext graphicsContext:(CGContextRef)context;
-(id)drawBezier:(id)bezier fromPoint:(unsigned)point withUniformContext:(id)uniformContext bottomImage:(id)image;
-(id)drawBezier:(id)bezier;
@end

