/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LookupFriendsModel.h"

@class GoogleContactsFeed, GmailContactsLoader;

__attribute__((visibility("hidden")))
@interface LookupFriendsModelGmail : LookupFriendsModel {
	GmailContactsLoader* _loader;
	GoogleContactsFeed* _contactsFeed;
}
@property(retain, nonatomic) GmailContactsLoader* loader;
@property(retain, nonatomic) GoogleContactsFeed* contactsFeed;
-(void).cxx_destruct;
-(id)lookupResponseWithData:(id)data context:(id)context;
-(id)requestForContext:(id)context;
-(BOOL)shouldLoad:(id)load;
-(void)loadFeed;
-(void)activate;
-(void)reset;
@end

