/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "VKMController.h"

@class Component5HostView;
@protocol TapableComponentHandler;

__attribute__((visibility("hidden")))
@interface LookupAddressbookTeaserViewController : VKMController {
	id<TapableComponentHandler> _buttonHandler;
	Component5HostView* _componentView;
}
@property(retain, nonatomic) id<TapableComponentHandler> buttonHandler;
@property(retain, nonatomic) Component5HostView* componentView;
-(void).cxx_destruct;
-(void)model:(id)model updated:(id)updated;
-(id)componentWithUsers:(id)users count:(unsigned)count;
-(void)viewWillLayoutSubviews;
-(void)loadView;
-(void)dealloc;
@end

