/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class Index, NSDate, MainNewsFeedModelContext;

__attribute__((visibility("hidden")))
@interface MainNewsFeedModelDeferredUpdate : XXUnknownSuperclass {
	Index* _index;
	MainNewsFeedModelContext* _context;
	NSDate* _creationDate;
}
@property(retain, nonatomic) NSDate* creationDate;
@property(retain, nonatomic) MainNewsFeedModelContext* context;
@property(retain, nonatomic) Index* index;
-(void).cxx_destruct;
@end

