/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NewsFeedController.h"
#import "vkclient-Structs.h"
#import "MainNewsFeedModelObserver.h"

@class NSString, FreshNewsButton, MainNewsFeedModel;

__attribute__((visibility("hidden")))
@interface MainNewsFeedController : NewsFeedController <MainNewsFeedModelObserver> {
	BOOL waitingUpdate;
	BOOL startedLoading;
	FreshNewsButton* _freshNewsPanel;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) MainNewsFeedModel* model;
@property(retain, nonatomic) FreshNewsButton* freshNewsPanel;
-(id)VKMControllerStatsRef;
-(int)VKMLiveAudioContext;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)updateUserActivityDate;
-(void)freshNewsButtonSetOffscreenHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)mainNewsFeedModel:(id)model didChangeDeferredUpdate:(id)update;
-(void)mainNewsFeedModelUnsyncedCountChangedFromValue:(id)value toValue:(id)value2;
-(void)actionSync:(id)sync;
-(void)syncTop;
-(void)syncRecent;
-(void)vkm_scrollToTop;
-(void)model:(id)model updated:(id)updated;
-(void)modelLoadingChanged:(id)changed;
-(void)actionTeaserButton:(id)button;
-(void)VKMScrollViewFullscreenUpdated:(BOOL)updated;
-(void)VKMScrollViewFullscreenUpdated;
-(void)scrollToTopAnimated:(BOOL)topAnimated;
-(void)checkFreshNews;
-(void)VKMControllerTouch;
-(void)viewWillLayoutSubviews;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
@end

