/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIView, NSString;

__attribute__((visibility("hidden")))
@interface MarketGallerySectionHeader : XXUnknownSuperclass {
	NSString* _title;
	unsigned _numberOfItems;
	UILabel* _titleLabel;
	UIView* _separator;
}
@property(assign, nonatomic) unsigned numberOfItems;
@property(copy, nonatomic) NSString* title;
@property(readonly, retain, nonatomic) UIView* separator;
@property(readonly, retain, nonatomic) UILabel* titleLabel;
-(id)labelAttributedTextWithTitle:(id)title numberOfItems:(unsigned)items;
-(void)layoutSubviews;
-(void)bindTitleLabelText;
-(void)setOpaque:(BOOL)opaque;
-(void)setBackgroundColor:(id)color;
-(id)createSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

