/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKClient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIFont, UITextField, NSString;
@protocol UITextFieldDelegateImproved;

__attribute__((visibility("hidden")))
@interface MBContactCollectionViewEntryCell : XXUnknownSuperclass {
	BOOL _enabled;
	id<UITextFieldDelegateImproved> _delegate;
	UIFont* _font;
	UITextField* _contactEntryTextField;
}
@property(retain, nonatomic) UIFont* font;
@property(assign, nonatomic) BOOL enabled;
@property(copy, nonatomic) NSString* text;
@property(assign, nonatomic) __weak id<UITextFieldDelegateImproved> delegate;
@property(assign, nonatomic) __weak UITextField* contactEntryTextField;
-(void).cxx_destruct;
-(BOOL)isFirstResponder;
-(float)widthForText:(id)text;
-(void)removeFocus;
-(void)setFocus;
-(void)reset;
-(void)setup;
-(void)layoutSubviews;
-(void)awakeFromNib;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
@end

