/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MBRoundProgressView : XXUnknownSuperclass {
	float _progress;
	BOOL _annular;
}
@property(assign, nonatomic, getter=isAnnular) BOOL annular;
@property(assign, nonatomic) float progress;
-(void)drawRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
-(id)init;
@end

