/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MCNearbyServiceBrowserDelegate <NSObject>
-(void)browser:(id)browser lostPeer:(id)peer;
-(void)browser:(id)browser foundPeer:(id)peer withDiscoveryInfo:(id)discoveryInfo;
@optional
-(void)browser:(id)browser didNotStartBrowsingForPeers:(id)peers;
@end

