/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModelAction.h"

@class VKDomain;

__attribute__((visibility("hidden")))
@interface ModelActionAdd : ModelAction {
	VKDomain* _added;
}
@property(retain, nonatomic) VKDomain* added;
@property(retain, nonatomic) VKDomain* target;
-(void)dealloc;
@end

