/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModelAction.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface ModelActionPushSourceSubscription : ModelAction {
	BOOL _subscribe;
}
@property(assign, nonatomic) BOOL subscribe;
@property(retain, nonatomic) NSNumber* target;
+(int)domainType;
-(id)actionSuccessMessage:(id)message;
-(BOOL)actionResultForData:(id)data context:(id)context;
-(id)actionRequestForContext:(id)context;
-(id)setupSubscribe:(BOOL)subscribe;
@end

