/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModelAction.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface ModelActionNewsSourceBan : ModelAction {
	BOOL _ban;
}
@property(assign, nonatomic) BOOL ban;
@property(retain, nonatomic) NSNumber* target;
+(int)domainType;
+(id)sourceId:(id)anId;
-(BOOL)actionResultForData:(id)data context:(id)context;
-(id)actionRequestForContext:(id)context;
@end

