/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModelActionEdit.h"

@class VKVideoAlbum;

__attribute__((visibility("hidden")))
@interface ModelActionEditVideoAlbum : ModelActionEdit {
}
@property(retain, nonatomic) VKVideoAlbum* target;
+(int)domainType;
-(BOOL)actionResultForData:(id)data context:(id)context;
-(id)actionRequestForContext:(id)context;
@end

