/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableDictionary, NSNumber, NSMutableArray, NSArray;

@interface MRJSONBuilder : XXUnknownSuperclass {
	NSString* _userId;
	NSMutableDictionary* _locationDict;
	NSMutableDictionary* _networkDict;
	NSMutableDictionary* _deviceDict;
	NSMutableDictionary* _userDict;
	NSMutableDictionary* _appDict;
	NSMutableDictionary* _appsDict;
	NSMutableDictionary* _dict;
	NSMutableDictionary* _settingsDict;
	NSMutableDictionary* _environmentDict;
	NSMutableDictionary* _environmentWifiDict;
	NSMutableArray* _eventItems;
	NSMutableArray* _customEventItems;
}
@property(copy, nonatomic) NSString* connectionType;
@property(copy, nonatomic) NSString* networkConnection;
@property(retain, nonatomic) NSNumber* simOperatorId;
@property(copy, nonatomic) NSString* operatorName;
@property(copy, nonatomic) NSString* operatorId;
@property(copy, nonatomic) NSString* simloc;
@property(retain, nonatomic) NSNumber* dpi;
@property(retain, nonatomic) NSNumber* density;
@property(retain, nonatomic) NSNumber* height;
@property(retain, nonatomic) NSNumber* width;
@property(copy, nonatomic) NSString* timezone;
@property(copy, nonatomic) NSString* euname;
@property(copy, nonatomic) NSString* lang;
@property(copy, nonatomic) NSString* osVer;
@property(copy, nonatomic) NSString* manufacture;
@property(copy, nonatomic) NSString* os;
@property(copy, nonatomic) NSString* device;
@property(retain, nonatomic) NSNumber* advertisingEnabled;
@property(copy, nonatomic) NSString* userId;
@property(retain, nonatomic) NSNumber* age;
@property(retain, nonatomic) NSNumber* gender;
@property(retain, nonatomic) NSArray* customUserIds;
@property(retain, nonatomic) NSArray* icqIds;
@property(retain, nonatomic) NSArray* emails;
@property(retain, nonatomic) NSArray* vkIds;
@property(retain, nonatomic) NSArray* okIds;
@property(copy, nonatomic) NSString* mrgsUserId;
@property(copy, nonatomic) NSString* mrgsAppId;
@property(copy, nonatomic) NSString* appName;
@property(copy, nonatomic) NSString* appLanguage;
@property(copy, nonatomic) NSString* appBuild;
@property(copy, nonatomic) NSString* appVersion;
@property(copy, nonatomic) NSString* MRGSDeviceId;
@property(copy, nonatomic) NSString* idfa;
@property(copy, nonatomic) NSString* mytrackerVersion;
@property(copy, nonatomic) NSString* vendorId;
@property(copy, nonatomic) NSString* trackerId;
@property(retain, nonatomic) NSNumber* customEventsSkipped;
@property(retain, nonatomic) NSNumber* timestampSend;
@property(retain, nonatomic) NSNumber* timestampBase;
-(void).cxx_destruct;
-(id)jsonString;
-(void)addEvent:(id)event;
-(void)setBssid:(id)bssid ssid:(id)ssid;
-(void)setLocationWithLatitude:(id)latitude longitude:(id)longitude accuracy:(id)accuracy speed:(id)speed timestamp:(id)timestamp;
-(void)setSettingsLaunchTimeout:(id)timeout;
-(void)setSettingsEnvironmentDisabled;
-(void)setSettingsLocationDisabled;
-(void)setSettingsLaunchDisabled;
-(id)init;
@end

