/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MTRGURLRequestProtocol <NSObject>
-(void)redirectRequestWithUrl:(id)url completionBlock:(id)block;
-(void)downloadRequestWithRequest:(id)request toFilePath:(id)filePath completionBlock:(id)block;
-(void)uploadRequestWithRequest:(id)request fromData:(id)data completionBlock:(id)block;
-(void)dataRequestWithRequest:(id)request completionBlock:(id)block;
@end

