/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MTRGSection.h"

@class NSMutableDictionary, MTRGImageData, NSString;

@interface MTRGAppwallSection : MTRGSection {
	BOOL _hasNotification;
	NSString* _title;
	MTRGImageData* _icon;
	MTRGImageData* _bubbleIcon;
	MTRGImageData* _gotoAppIcon;
	MTRGImageData* _itemHighlightIcon;
	NSMutableDictionary* _statusIcons;
}
@property(assign, nonatomic) BOOL hasNotification;
@property(retain, nonatomic) NSMutableDictionary* statusIcons;
@property(retain, nonatomic) MTRGImageData* itemHighlightIcon;
@property(retain, nonatomic) MTRGImageData* gotoAppIcon;
@property(retain, nonatomic) MTRGImageData* bubbleIcon;
@property(retain, nonatomic) MTRGImageData* icon;
@property(copy, nonatomic) NSString* title;
-(void).cxx_destruct;
-(id)findStatusIconImageData:(id)data;
@end

