/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface MTRGVastExtension : XXUnknownSuperclass {
	NSString* _type;
	NSString* _value;
}
@property(retain, nonatomic) NSString* value;
@property(retain, nonatomic) NSString* type;
-(void).cxx_destruct;
@end

