/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MTRGAbstractDataProvider.h"

@class CTTelephonyNetworkInfo, MTRGGCNetworkReachability, NSString;

@interface MTRGNetworkDataProvider : MTRGAbstractDataProvider {
	NSString* _connectionValue;
	NSString* _connectionType;
	CTTelephonyNetworkInfo* _coreTelephonyNetworkInfo;
	MTRGGCNetworkReachability* _reachabilityManager;
}
-(void).cxx_destruct;
-(void)dealloc;
-(id)connectionTypeWithConnectionValue:(id)connectionValue;
-(id)statusStringWithNetworkReachabilityStatus:(unsigned char)networkReachabilityStatus;
-(id)connectionTypeWithRadioAccessTechnology:(id)radioAccessTechnology;
-(void)updateConnection:(unsigned char)connection;
-(void)startMonitoring;
-(void)collectData;
-(id)init;
@end

