/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface MTRGURLSessionRedirectRequestHolder : XXUnknownSuperclass {
	BOOL _success;
	NSString* _url;
	id _completionBlock;
	unsigned _redirectsCount;
}
@property(assign, nonatomic) unsigned redirectsCount;
@property(assign, nonatomic) BOOL success;
@property(copy, nonatomic) id completionBlock;
@property(copy, nonatomic) NSString* url;
-(void).cxx_destruct;
@end

