/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NDialogEvent.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface NEventDialogError : NDialogEvent {
	NSString* _text;
}
@property(readonly, retain, nonatomic) NSString* text;
+(id)eventWithText:(id)text inDialog:(id)dialog;
-(id)eventText:(id)text;
-(void)dealloc;
@end

