/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ListModel.h"


__attribute__((visibility("hidden")))
@interface NewsSectionsModel : ListModel {
}
-(id)itemsToAppend:(id)append to:(id)to context:(id)context;
-(id)process:(id)process;
-(id)requestForContext:(id)context;
-(void)handleSetNewsFeedSections:(id)sections :(id)arg2;
-(void)registerForEvents:(id)events;
@end

