/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMLiveController.h"
#import "NewsSectionCellDelegate.h"

@class NewsSectionsModel, NSString;

__attribute__((visibility("hidden")))
@interface NewsSectionsController : VKMLiveController <NewsSectionCellDelegate> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NewsSectionsModel* model;
-(void)newsSectionCellDidChangeValue:(id)newsSectionCell;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)viewDidLoad;
@end

