/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NewsFeedModel.h"

@class VKNewsList;

__attribute__((visibility("hidden")))
@interface NewsListFeedModel : NewsFeedModel {
	VKNewsList* _list;
}
@property(retain, nonatomic) VKNewsList* list;
+(int)handlesSourcesBans;
-(id)feedStatContext;
-(id)feedRequestBuilderForContext:(id)context;
-(id)sourceString;
-(void)dealloc;
@end

