/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PanGestureDrivenDismissableTransitionViewController <NSObject>
-(BOOL)canBeginPanGestureDismissTransition;
-(id)viewForDismissTransitionAnimation;
-(id)viewForDismissTransitionPanGesture;
@optional
-(void)didFinishPanGestureDismissTransition;
-(void)willFinishPanGestureDismissTransition;
-(void)didFinishCancelPanGestureDismissTransition;
-(void)willCancelPanGestureDismissTransition;
-(void)didUpdatePanGestureDismissTransition:(float)transition;
-(void)willBeginPanGestureDismissTransition;
@end

