/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ThumbnailView.h"
#import "vkclient-Structs.h"

@class VKPhotoTags, UIView;
@protocol PhotoTagsViewDelegate;

__attribute__((visibility("hidden")))
@interface PhotoTagsView : ThumbnailView {
	BOOL ready;
	VKPhotoTags* _tags;
	UIView* _overlay;
	UIView* _viewport;
}
@property(assign, nonatomic) id<PhotoTagsViewDelegate> delegate;
@property(retain, nonatomic) VKPhotoTags* tags;
@property(retain, nonatomic) UIView* viewport;
@property(retain, nonatomic) UIView* overlay;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)highlight:(unsigned)highlight;
-(id)tagAtIndex:(unsigned)index;
-(void)selected:(id)selected;
-(void)hide:(id)hide;
-(void)setImage:(id)image;
-(void)update;
-(void)lazy;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

