/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FeedController.h"
#import "VKClient-Structs.h"


__attribute__((visibility("hidden")))
@interface PhotoFeedController : FeedController {
}
+(void)takePhoto:(id)photo postContext:(id)context handler:(id)handler;
+(void)takePhoto:(id)photo handler:(id)handler;
-(id)VKMControllerStatsRef;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)actionPhoto:(id)photo;
-(id)renderGroupForCell:(id)cell;
-(BOOL)VKMScrollViewFullscreenEnabled;
-(void)viewDidLoad;
-(int)VKMTableStyle;
-(void)actionTeaserButton:(id)button;
@end

