/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMLiveController.h"
#import "vkclient-Structs.h"

@class PhotoAlbumsEditModel;

__attribute__((visibility("hidden")))
@interface PhotoAlbumsController : VKMLiveController {
}
@property(retain, nonatomic) PhotoAlbumsEditModel* model;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)VKMRoute:(id)route context:(id)context;
-(void)actionAdd:(id)add;
-(int)VKMControllerModalAutoClosePosition;
-(void)viewDidLoad;
@end

