/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TextEditContext.h"

@class VKPhoto;

__attribute__((visibility("hidden")))
@interface PhotoEditContext : TextEditContext {
}
@property(retain, nonatomic) VKPhoto* domain;
-(unsigned)textLengthMax;
-(unsigned)textLengthMin;
-(id)title;
-(void)useDomain:(id)domain edit:(BOOL)edit;
-(id)confirmAction:(id)action;
@end

