/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "vkclient-Structs.h"

@class UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface PhotoHostProgressView : XXUnknownSuperclass {
	float _progress;
	BOOL _annular;
	UIActivityIndicatorView* _indeterminateActivity;
}
@property(assign, nonatomic, getter=isAnnular) BOOL annular;
@property(assign, nonatomic) float progress;
@property(retain, nonatomic) UIActivityIndicatorView* indeterminateActivity;
-(void)drawRect:(CGRect)rect;
-(void)setIndeterminate:(BOOL)indeterminate;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

