/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "PlaceCell.h"


__attribute__((visibility("hidden")))
@interface PlaceCurrentCell : PlaceCell {
}
+(id)statusForAddress:(id)address searching:(BOOL)searching;
-(void)attach:(id)attach expectedReuse:(double)reuse;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

