/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"
#import "vkclient-Structs.h"

@class PriorityButtonComponentState;

__attribute__((visibility("hidden")))
@interface PriorityButtonComponent : Component5 {
}
@property(retain, nonatomic) PriorityButtonComponentState* state;
+(id)buttonWithPriority:(unsigned)priority title:(id)title handler:(id)handler;
@end

