/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"
#import "VKTitleable.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface PrivacyVariant : VKRenderable <VKTitleable> {
	BOOL _selected;
	NSString* _title;
	NSString* _value;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL selected;
@property(copy, nonatomic) NSString* value;
@property(copy, nonatomic) NSString* title;
+(id)privacyWithValue:(id)value;
-(BOOL)disclosure;
-(Class)rendererClass;
-(void)dealloc;
@end

