/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSArray;

__attribute__((visibility("hidden")))
@interface ProfileInfoSection : XXUnknownSuperclass {
	NSString* _title;
	NSArray* _items;
}
@property(retain, nonatomic) NSArray* items;
@property(copy, nonatomic) NSString* title;
+(id)withTitle:(id)title;
-(id)addItemWithTitle:(id)title subtitle:(id)subtitle photo:(id)photo routeTarget:(id)target;
-(id)addItemWithTitle:(id)title subtitle:(id)subtitle photo:(id)photo;
-(id)addItemWithTitle:(id)title subtitle:(id)subtitle;
-(id)addItem:(id)item;
-(void)dealloc;
@end

