/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DefaultProfileModel.h"

@class StatContext, VKProfile;

__attribute__((visibility("hidden")))
@interface ProfileModel : DefaultProfileModel {
	StatContext* _stats_context;
}
@property(readonly, retain, nonatomic) VKProfile* item;
@property(retain, nonatomic) StatContext* stats_context;
-(void).cxx_destruct;
-(void)handleGiftAdd:(id)add :(id)arg2;
-(void)handleSubscribeLiveVideo:(id)video :(id)arg2;
-(void)handleSubscribe:(id)subscribe :(id)arg2;
-(void)handleFavorites:(id)favorites :(id)arg2;
-(void)handleEditProfile:(id)profile :(id)arg2;
-(void)handlePhotoUpload:(id)upload :(id)arg2;
-(void)handleDeletePhoto:(id)photo :(id)arg2;
-(void)handleBlacklist:(id)blacklist :(id)arg2;
-(void)handleFriend:(id)aFriend :(id)arg2;
-(void)handleStatus:(id)status :(id)arg2;
-(void)registerForEvents:(id)events;
-(void)fillPhotoActions:(id)actions;
-(void)fillProfileActions:(id)actions;
-(id)safeScreenName;
-(id)friendAction:(BOOL)action;
-(id)recreateProfileIndex:(id)index;
-(id)process:(id)process context:(id)context;
-(id)request;
-(id)withStatsContext:(id)statsContext;
@end

