/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSData, NSString;

__attribute__((visibility("hidden")))
@interface RMPhoneFormat : XXUnknownSuperclass {
	NSData* _data;
	NSString* _defaultCountry;
	NSString* _defaultCallingCode;
	NSMutableDictionary* _callingCodeOffsets;
	NSMutableDictionary* _callingCodeCountries;
	NSMutableDictionary* _callingCodeData;
	NSMutableDictionary* _countryCallingCode;
}
+(id)instance;
+(id)strip:(id)strip;
+(void)initialize;
-(void).cxx_destruct;
-(void)parseDataHeader;
-(id)callingCodeInfo:(id)info;
-(int)value16BE:(unsigned)be;
-(int)value16:(unsigned)a16;
-(unsigned)value32:(unsigned)a32;
-(BOOL)isPhoneNumberValid:(id)valid;
-(id)format:(id)format;
-(id)findCallingCodeInfo:(id)info;
-(id)countriesForCallingCode:(id)callingCode;
-(id)callingCodeForCountryCode:(id)countryCode;
-(id)defaultCallingCode;
-(id)initWithDefaultCountry:(id)defaultCountry;
-(id)init;
-(id)isoToCodeMap;
-(BOOL)isPhoneNumberValid:(id)valid forCode:(id)code;
-(id)format:(id)format forCode:(id)code;
@end

