/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import "vkclient-Structs.h"
#import "AnimatingIndicator.h"
#import "MBProgressHUDCustomView.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, RoundedProgressOverlayLayer, UIColor, RoundedProgressOverlayCircle, NSString, UIImageView;
@protocol RoundedProgressOverlayViewDelegate;

__attribute__((visibility("hidden")))
@interface RoundedProgressOverlayView : XXUnknownSuperclass <UIGestureRecognizerDelegate, MBProgressHUDCustomView, AnimatingIndicator> {
	int _rotationDegree;
	int _currentAnimationFrame;
	BOOL _isIndeterminate;
	BOOL _animated;
	UIColor* _overlayColor;
	UIColor* _strokeColor;
	NSString* _text;
	id<RoundedProgressOverlayViewDelegate> _delegate;
	float _pizzaRadius;
	float _strokeWidth;
	float _progress;
	float _speedFactor;
	RoundedProgressOverlayCircle* _circleLayer;
	RoundedProgressOverlayLayer* _progressLayer;
	UILabel* _textLabel;
	UIImageView* _crossImageView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL animated;
@property(assign, nonatomic) float speedFactor;
@property(assign, nonatomic) float progress;
@property(assign, nonatomic) float strokeWidth;
@property(assign, nonatomic) float pizzaRadius;
@property(assign, nonatomic) __weak id<RoundedProgressOverlayViewDelegate> delegate;
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) UIColor* strokeColor;
@property(retain, nonatomic) UIColor* overlayColor;
@property(retain, nonatomic) UIImageView* crossImageView;
@property(retain, nonatomic) UILabel* textLabel;
@property(retain, nonatomic) RoundedProgressOverlayLayer* progressLayer;
@property(retain, nonatomic) RoundedProgressOverlayCircle* circleLayer;
-(void).cxx_destruct;
-(BOOL)isAnimating;
-(void)stopAnimating;
-(void)startAnimating;
-(void)cancelTap:(id)tap;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)setIndeterminate:(BOOL)indeterminate;
-(void)clean;
-(void)layoutSublayersOfLayer:(id)layer;
-(void)setProgress:(float)progress animated:(BOOL)animated;
-(void)setBackgroundHidden:(BOOL)hidden;
-(void)setCancelHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)setCancelHidden:(BOOL)hidden;
-(void)setCancelationImage:(id)image;
-(void)setProgressLayerValue:(float)value to:(float)to animated:(BOOL)animated;
-(void)addRunningAnimation;
-(void)setHidden:(BOOL)hidden;
-(void)setDisplayLinkPaused:(BOOL)paused;
-(void)addSublayer:(id)sublayer;
-(void)setUp;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
@end

