/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIScrollViewDelegate.h"
#import "vkclient-Structs.h"

@class NSString;
@protocol ScrollToTopDetectionViewDelegate;

__attribute__((visibility("hidden")))
@interface ScrollToTopDetectionView : XXUnknownSuperclass <UIScrollViewDelegate> {
	id<ScrollToTopDetectionViewDelegate> _scrollToTopDelegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) id<ScrollToTopDetectionViewDelegate> scrollToTopDelegate;
-(BOOL)scrollViewShouldScrollToTop:(id)scrollView;
-(void)dealloc;
-(id)initDetectionViewWithWidth:(float)width;
@end

