/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKClient-Structs.h"
#import "UISearchBarDelegate.h"
#import "MarketSearchBarPanelDelegate.h"
#import "VKMController.h"

@class MarketCollectionsController, EventThrottler, MarketSearchBarPanelView, MainModel, NSString, MarketModel;
@protocol MarketCollectionsAdapter;

__attribute__((visibility("hidden")))
@interface SearchMarketCollectionsController : VKMController <UISearchBarDelegate, MarketSearchBarPanelDelegate> {
	MarketSorting_t _marketSortingOptions[3];
	MarketSearchBarPanelView* _searchBarPanel;
	EventThrottler* _eventThrottler;
	int _trackSearchTextChanges;
	MarketCollectionsController* _collectionsController;
	id<MarketCollectionsAdapter> _modeAdapter;
	MainModel* _mainModel;
	MarketModel* _marketModel;
	id _completionBlock;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) id completionBlock;
@property(readonly, retain, nonatomic) MarketModel* marketModel;
@property(readonly, retain, nonatomic) MainModel* mainModel;
@property(retain, nonatomic) id<MarketCollectionsAdapter> modeAdapter;
@property(readonly, retain, nonatomic) MarketCollectionsController* collectionsController;
@property(assign, nonatomic) int trackSearchTextChanges;
@property(retain, nonatomic) EventThrottler* eventThrottler;
@property(retain, nonatomic) MarketSearchBarPanelView* searchBarPanel;
-(void).cxx_destruct;
-(void)stopSearchingThrottler;
-(void)searchWithQuery:(id)query filter:(id)filter sort:(MarketSorting_t)sort;
-(unsigned)indexOfSort:(unsigned)sort;
-(void)toggleSortingDirectionAtIndex:(unsigned)index;
-(void)scrollToTop;
-(void)marketSearchBarPanel:(id)panel searchingOptionSelected:(id)selected previousSelectedOption:(id)option;
-(void)marketSearchBarPanelCancelButtonClicked:(id)clicked;
-(void)marketSearchBarPanel:(id)panel textDidChange:(id)text;
-(void)installSearchBar;
-(id)titleForSortingOption:(MarketSorting_t)sortingOption;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)installCollectionsController;
-(void)keyboardFrameChanged:(id)changed;
-(int)preferredStatusBarStyle;
-(void)viewDidLoad;
-(void)attachMainModel:(id)model marketModel:(id)model2 completionBlock:(id)block;
-(id)init;
-(void)dealloc;
@end

