/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMTableController.h"
#import "vkclient-Structs.h"
#import "SearchPeopleStatusSelectionViewControllerDelegate.h"

@class NSNumber, SearchPeopleFiltersLoadingView, SearchPeopleModel, NSString;

__attribute__((visibility("hidden")))
@interface SearchPeopleFiltersViewController : VKMTableController <SearchPeopleStatusSelectionViewControllerDelegate> {
	BOOL _ageFilterEnabled;
	NSNumber* _initialResultsCount;
	SearchPeopleFiltersLoadingView* _loadingView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SearchPeopleModel* model;
@property(retain, nonatomic) NSNumber* initialResultsCount;
@property(retain, nonatomic) SearchPeopleFiltersLoadingView* loadingView;
@property(assign, nonatomic) BOOL ageFilterEnabled;
-(void)modelLoadingChanged:(id)changed;
-(void)VKMTableDiscovered:(id)discovered cell:(id)cell;
-(void)model:(id)model updated:(id)updated;
-(void)VKMControllerTouch;
-(void)updateModel;
-(void)didUpdateAgeRange:(id)range;
-(void)ageFilterEnabledChanged:(id)changed;
-(void)sexChanged:(id)changed;
-(void)statusSelectionViewController:(id)controller didSelectStatus:(int)status;
-(void)selectStatus;
-(void)selectCity;
-(void)selectCountry;
-(void)actionShowResults:(id)results;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view statusSectionCellForRow:(int)row;
-(id)tableView:(id)view ageSectionCellForRow:(int)row;
-(id)tableView:(id)view sexSectionCellForRow:(int)row;
-(id)tableView:(id)view regionSectionCellForRow:(int)row;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)VKMNavigationBarStyle;
-(int)VKMControllerStatusBarStyle;
-(int)VKMTableStyle;
-(UIEdgeInsets)VKMControllerChromeInsetsAdjust:(UIEdgeInsets)adjust;
-(void)viewDidLoad;
-(void)loadView;
-(void)dealloc;
@end

