/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSArray;

__attribute__((visibility("hidden")))
@interface SectionItemsGroup : XXUnknownSuperclass {
	NSString* _title;
	NSArray* _items;
}
@property(readonly, copy, nonatomic) NSArray* items;
@property(readonly, copy, nonatomic) NSString* title;
+(id)groupWithTitle:(id)title items:(id)items;
-(void)dealloc;
-(id)initWithTitle:(id)title items:(id)items;
@end

