/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "vkclient-Structs.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface SeekSlider : XXUnknownSuperclass {
	UIImageView* _highlight;
}
@property(retain, nonatomic) UIImageView* highlight;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(void)dealloc;
@end

