/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface SeparatorWithBorders : XXUnknownSuperclass {
	unsigned _borders;
	UIColor* _borderColor;
}
@property(retain, nonatomic) UIColor* borderColor;
@property(assign, nonatomic) unsigned borders;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
@end

