/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "UICollectionViewComponent.h"

@class ShopProductGalleryCollectionViewComponentState;

__attribute__((visibility("hidden")))
@interface ShopProductGalleryCollectionViewComponent : UICollectionViewComponent {
}
@property(retain, nonatomic) ShopProductGalleryCollectionViewComponentState* state;
+(id)componentWithPhotos:(id)photos mediator:(id)mediator;
+(id)imageComponentWithPhoto:(id)photo size:(CGSize)size tapCallback:(id)callback;
@end

