/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "ChatController.h"

@class NSNumber;
@protocol VKSource;

__attribute__((visibility("hidden")))
@interface SingleUserChatController : ChatController {
	BOOL updated;
	id<VKSource> _source;
	NSNumber* _uid;
}
@property(retain, nonatomic) id<VKSource> source;
@property(retain, nonatomic) NSNumber* uid;
-(void)headerSelected;
-(void)selectedAdditionalUser:(id)user;
-(void)notificationUserUpdated:(id)updated;
-(void)loadUser;
-(void)chatRefreshTitle;
-(id)chatActivityComponent;
-(id)chatTitleText;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithMain:(id)main andUser:(id)user caching:(BOOL)caching;
@end

