/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"


__attribute__((visibility("hidden")))
@interface SnippetComponent : Component5 {
}
+(id)futureSnippet:(id)snippet completion:(id)completion;
+(id)snippet:(id)snippet type:(int)type;
+(id)snippet:(id)snippet;
+(id)bigSnippet:(id)snippet;
+(id)smallSnippet:(id)snippet;
+(id)descriptionForSnippet:(id)snippet type:(int)type;
+(id)descriptionForSmallSnippet:(id)smallSnippet;
+(id)descriptionForBigSnippet:(id)bigSnippet;
+(id)descriptionComponentForRating:(id)rating;
+(id)buttonComponent:(id)component;
+(id)snippetButtonWithText:(id)text handler:(id)handler;
+(id)separatedTextComponentWithTitle:(id)title description:(id)description;
+(id)combinedTextComponentWithTitle:(id)title description:(id)description numberOfLines:(unsigned)lines;
+(id)combinedTextWithTitle:(id)title description:(id)description styleSheet:(id)sheet;
+(id)descriptionTextStyleWithStyleSheet:(id)styleSheet;
+(id)titleTextStyleWithStyleSheet:(id)styleSheet;
+(id)tapableSnippetComponent:(id)component handler:(id)handler;
+(id)shadowDecoratedComponent:(id)component;
+(id)leftSnippetDecoratedPhotoComponent:(id)component;
+(id)topSnippetDecoratedPhotoComponent:(id)component;
+(id)snippetDecoratedComponentWithBackground:(id)background;
+(id)snippetDecoratedComponent:(id)component;
+(id)rightSnippetDecoratedComponent:(id)component;
+(id)leftSnippetDecoratedComponent:(id)component;
+(id)bottomSnippetDecoratedComponent:(id)component;
+(id)topSnippetDecoratedComponent:(id)component;
+(id)_snippetDecoratedComponent:(id)component image:(id)image;
@end

