/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SocialButtonsDataSource <NSObject>
-(void)actionShare:(id)share;
-(void)actionComment:(id)comment;
-(void)actionLike:(id)like;
-(BOOL)shared;
-(BOOL)liked;
-(int)numberOfViews;
-(int)numberOfShares;
-(int)numberOfComments;
-(int)numberOfLikes;
-(BOOL)canShowViews;
-(BOOL)canShare;
-(BOOL)canComment;
-(BOOL)canLike;
@end

