/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"


__attribute__((visibility("hidden")))
@interface SocialButtonsComponent : Component5 {
}
+(id)componentDetailWithDataSource:(id)dataSource;
+(id)componentWithDataSource:(id)dataSource;
@end

