/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"
#import "vkclient-Structs.h"


__attribute__((visibility("hidden")))
@interface SpacerComponent : Component5 {
}
+(id)height:(float)height;
+(id)width:(float)width;
+(id)size:(CGSize)size;
+(id)spacer;
+(id)emptyComponent:(id)component;
-(BOOL)isUtility;
@end

