/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface StatsUploadHelper : XXUnknownSuperclass {
	BOOL _empty;
	id _executeConfigurationBlock;
	id _failureBlock;
	id _successBlock;
}
@property(readonly, assign, nonatomic) BOOL empty;
@property(copy, nonatomic) id successBlock;
@property(copy, nonatomic) id failureBlock;
@property(copy, nonatomic) id executeConfigurationBlock;
+(void)uploadWithSession:(id)session;
+(id)helperForSession:(id)session;
-(void)handleExecuteSuccessWithData:(id)data;
-(void)handleExecuteFailure;
-(void)configureExectuteBuilder:(id)builder;
-(id)initWithSession:(id)session;
-(void)dealloc;
@end

