/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomain.h"

@class NSSet, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface StickerSuggestionsInfo : VKDomain {
	NSString* _baseURL;
	NSDictionary* _stickersForKey;
	NSSet* _availableStickersIds;
}
@property(retain, nonatomic) NSSet* availableStickersIds;
@property(retain, nonatomic) NSDictionary* stickersForKey;
@property(copy, nonatomic) NSString* baseURL;
-(void).cxx_destruct;
-(id)availableStickersIdsForStickersIds:(id)stickersIds;
-(id)suggestedStickersIdsForText:(id)text recentStickersIds:(id)ids;
-(id)stickersIdsForText:(id)text;
-(id)keyForText:(id)text;
-(id)signinficantTextForText:(id)text;
-(BOOL)process:(id)process context:(id)context;
@end

