/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"


@protocol StillImageSampleBufferProcessor
-(id)processImageDataSampleBufferFromStillCamera:(opaqueCMSampleBuffer*)stillCamera deviceOrientation:(int)orientation isFrontfacingCamera:(BOOL)camera writeMetadataTo:(id*)to;
@end

