/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "StoryFullscreenViewModel.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class StoryIdentity, UploadingStory, NSDate, UIImage, KVOObserver, AVURLAsset, NSString, NSURL, StoriesModel;
@protocol VKSource;

__attribute__((visibility("hidden")))
@interface StoryFullscreenModel : XXUnknownSuperclass <StoryFullscreenViewModel> {
	BOOL _can_comment;
	StoriesModel* _storiesModel;
	StoryIdentity* _storyIden;
	unsigned _storyState;
	unsigned _storyType;
	UIImage* _lowResPreviewImage;
	NSString* _photoStoryImageURL;
	NSString* _videoStoryFirstFrameURL;
	NSURL* _videoStoryFileURL;
	AVURLAsset* _videoStoryAsset;
	float _progress;
	id<VKSource> _source;
	NSDate* _date;
	KVOObserver* _uploadingStoryKVOObserver;
	UploadingStory* _uploadingStory;
	double _videoStoryDuration;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL can_comment;
@property(readonly, assign, nonatomic) int viewsCount;
@property(readonly, assign, nonatomic) NSDate* date;
@property(readonly, assign, nonatomic) id<VKSource> source;
@property(readonly, assign, nonatomic) double videoStoryDuration;
@property(readonly, assign, nonatomic) AVURLAsset* videoStoryAsset;
@property(readonly, assign, nonatomic) NSURL* videoStoryFileURL;
@property(readonly, assign, nonatomic) NSString* videoStoryFirstFrameURL;
@property(readonly, assign, nonatomic) NSString* photoStoryImageURL;
@property(readonly, assign, nonatomic) UIImage* lowResPreviewImage;
@property(readonly, assign, nonatomic) unsigned storyType;
@property(readonly, assign, nonatomic) StoryIdentity* storyIden;
@property(assign, nonatomic) __weak StoriesModel* storiesModel;
@property(assign, nonatomic) unsigned storyState;
@property(assign, nonatomic) float progress;
@property(retain, nonatomic) UploadingStory* uploadingStory;
@property(retain, nonatomic) KVOObserver* uploadingStoryKVOObserver;
-(void).cxx_destruct;
-(void)markStoryAsDeleted;
-(void)updateStoryIdentityVKIden:(id)iden;
-(void)setup;
-(id)initWithStoryIden:(id)storyIden weakStoriesModel:(id)model;
@end

