/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKClient-Structs.h"
#import "VKMImageView.h"


__attribute__((visibility("hidden")))
@interface StoryFullscreenPhotoImageView : VKMImageView {
	BOOL _imageLoaded;
	id _imageLoadedSuccessHandler;
}
@property(copy, nonatomic) id imageLoadedSuccessHandler;
@property(readonly, assign, nonatomic) BOOL imageLoaded;
-(void).cxx_destruct;
-(void)reuse;
-(void)loader:(id)loader complete:(id)complete;
@end

