/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "VKCollectionView.h"


__attribute__((visibility("hidden")))
@interface StoryFullscreenCollectionView : VKCollectionView {
	id _touchesBeganHandler;
	id _touchesCancelledHandler;
	id _touchesEndedHandler;
}
@property(copy, nonatomic) id touchesEndedHandler;
@property(copy, nonatomic) id touchesCancelledHandler;
@property(copy, nonatomic) id touchesBeganHandler;
-(void).cxx_destruct;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(id)initWithFrame:(CGRect)frame;
@end

