/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSURLConnectionDataDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "AVAssetResourceLoaderDelegate.h"

@class NSMutableData, NSMutableArray, NSHTTPURLResponse, NSObject, NSString, NSURLConnection;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface StoryAssetResourceLoaderDelegate : XXUnknownSuperclass <NSURLConnectionDataDelegate, AVAssetResourceLoaderDelegate> {
	NSString* _originalURLScheme;
	NSObject<OS_dispatch_queue>* _workingQueue;
	NSMutableData* _videoData;
	NSURLConnection* _connection;
	NSHTTPURLResponse* _response;
	NSMutableArray* _pendingRequests;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* workingQueue;
@property(retain, nonatomic) NSString* originalURLScheme;
@property(retain, nonatomic) NSMutableArray* pendingRequests;
@property(retain, nonatomic) NSHTTPURLResponse* response;
@property(retain, nonatomic) NSURLConnection* connection;
@property(retain, nonatomic) NSMutableData* videoData;
-(void).cxx_destruct;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)asyncOnWorkingQueue:(id)queue;
-(void)resourceLoader:(id)loader didCancelLoadingRequest:(id)request;
-(BOOL)resourceLoader:(id)loader shouldWaitForLoadingOfRequestedResource:(id)requestedResource;
-(BOOL)respondWithDataForRequest:(id)request;
-(void)fillInContentInformation:(id)contentInformation;
-(void)processPendingRequests;
-(void)dealloc;
-(id)initWithQueue:(id)queue;
-(id)init;
@end

