/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Component5.h"

@class TextComponentState;

__attribute__((visibility("hidden")))
@interface TextComponent : Component5 {
}
@property(retain, nonatomic) TextComponentState* state;
+(id)textWithSettings:(id)settings;
+(id)text:(id)text;
+(id)computedTextWithString:(id)string context:(id)context;
+(id)computedTextWithString:(id)string numberOfLines:(unsigned)lines alignment:(int)alignment context:(id)context;
+(id)computedTextWithString:(id)string numberOfLines:(unsigned)lines context:(id)context;
+(id)computedTextWithSettings:(id)settings context:(id)context;
+(id)computedTextWithString:(id)string numberOfLines:(unsigned)lines alignment:(int)alignment;
+(id)computedTextWithString:(id)string numberOfLines:(unsigned)lines;
+(id)computedTextWithString:(id)string;
+(id)computedTextWithSettings:(id)settings;
+(Class)nodeClass;
-(id)componentByAppendingComponent:(id)component;
-(id)nodeForState:(id)state context:(id)context;
@end

