/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor, VKRenderedText;

__attribute__((visibility("hidden")))
@interface TextComponentState : XXUnknownSuperclass {
	VKRenderedText* _text;
	UIColor* _backgroundColor;
}
@property(retain, nonatomic) UIColor* backgroundColor;
@property(retain, nonatomic) VKRenderedText* text;
-(void).cxx_destruct;
@end

