/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "EditController.h"
#import "vkclient-Structs.h"
#import "UITextViewDelegate.h"

@class NSString, MOTextView, TextEditContext;

__attribute__((visibility("hidden")))
@interface TextEditController : EditController <UITextViewDelegate> {
	float keyboardHeight;
	MOTextView* _textView;
	NSString* _textTitle;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) MOTextView* textView;
@property(retain, nonatomic) TextEditContext* context;
@property(retain, nonatomic) NSString* textTitle;
-(void)textViewDidChange:(id)textView;
-(int)VKMEditDataState;
-(void)VKMEditDataChanged:(BOOL)changed;
-(unsigned)supportedInterfaceOrientations;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)updateForOrientation;
-(void)VKMDismissModalSelf:(BOOL)aSelf;
-(void)notificationKeyboard:(id)keyboard;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)VKMControllerChromeInsetsApply;
-(void)dealloc;
-(id)initWithMain:(id)main andModel:(id)model;
@end

