/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class VKFeedVideo, VKFeedPhoto, NSArray;
@protocol PhotoStats;

__attribute__((visibility("hidden")))
@interface ThumbnailsComponentState : XXUnknownSuperclass {
	VKFeedPhoto* _feedPhoto;
	VKFeedVideo* _feedVideo;
	NSArray* _images;
	NSArray* _components;
	id<PhotoStats> _photoStats;
}
@property(retain, nonatomic) id<PhotoStats> photoStats;
@property(readonly, assign, nonatomic) NSArray* components;
@property(retain, nonatomic) NSArray* images;
@property(retain, nonatomic) VKFeedVideo* feedVideo;
@property(retain, nonatomic) VKFeedPhoto* feedPhoto;
-(void).cxx_destruct;
-(id)componentForImage:(id)image;
@end

