/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKThumbnailView.h"
#import "UIGestureRecognizerDelegate.h"
#import "VKClient-Structs.h"
#import "VKMImageView.h"

@class UIImage, UITapGestureRecognizer, VKDomain, NSString;
@protocol VKThumbnailable, ThumbnailViewDelegate;

__attribute__((visibility("hidden")))
@interface ThumbnailView : VKMImageView <UIGestureRecognizerDelegate, VKThumbnailView> {
	VKDomain<VKThumbnailable>* _domain;
	int _renderedSize;
	UITapGestureRecognizer* _recognizer;
	id<ThumbnailViewDelegate> _delegate;
}
@property(readonly, assign, nonatomic) UIImage* image;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<ThumbnailViewDelegate> delegate;
@property(retain, nonatomic) UITapGestureRecognizer* recognizer;
@property(assign, nonatomic) int renderedSize;
@property(retain, nonatomic) VKDomain<VKThumbnailable>* domain;
-(void).cxx_destruct;
-(id)navDelegate;
-(void)tapped:(id)tapped;
-(id)initWithFrame:(CGRect)frame;
@end

