/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"

@class Index;

__attribute__((visibility("hidden")))
@interface UICollectionViewComponentState : XXUnknownSuperclass {
	BOOL _pagingEnabled;
	Index* _index;
	float _pagingOffsets;
	CGPoint _contentOffset;
}
@property(assign, nonatomic) float pagingOffsets;
@property(assign, nonatomic, getter=isPagingEnabled) BOOL pagingEnabled;
@property(assign, nonatomic) CGPoint contentOffset;
@property(retain, nonatomic) Index* index;
-(void).cxx_destruct;
@end

