/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ClientBasedUploadContext.h"

@class VKSession, EventContext;

__attribute__((visibility("hidden")))
@interface UploadContext : ClientBasedUploadContext {
	VKSession* _session;
	EventContext* _eventContext;
}
@property(retain, nonatomic) EventContext* eventContext;
@property(retain, nonatomic) VKSession* session;
+(id)contextWithSession:(id)session;
-(void)dealloc;
@end

