/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKVideoPlayerHolder.h"
#import "VKMController.h"
#import "UIViewControllerTransitioningDelegate.h"
#import "FullScreenVideoPlayerControlsViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "PanGestureDrivenDismissableTransitionViewController.h"
#import "vkclient-Structs.h"

@class VKVideoPlayer, VKVideo, FullScreenVideoPlayerControlsView, UITapGestureRecognizer, NSTimer, KVOObserver, VideoPlayerModel, VideoContainerView, NSString;

__attribute__((visibility("hidden")))
@interface VideoPlayerViewController : VKMController <UIViewControllerTransitioningDelegate, FullScreenVideoPlayerControlsViewDelegate, UIGestureRecognizerDelegate, PanGestureDrivenDismissableTransitionViewController, VKVideoPlayerHolder> {
	BOOL _mustCreatePlayer;
	BOOL _manuallyPausedVideo;
	BOOL _scrubbing;
	BOOL _controlsHidden;
	BOOL _dismissTransitionInProgress;
	BOOL _showPlayPauseButtonAndScrubberOnNextTap;
	BOOL _playerCreatedHere;
	BOOL _viewDidAppearOnce;
	BOOL _wasPlayingBeforeScrubbing;
	BOOL _wasPlayingBeforeDisappear;
	BOOL _wasPlayingBeforeApplicationResignedActive;
	BOOL _audioPlayerWasPlayingBeforeAppear;
	BOOL _shouldAutoHideControlsAsSoonAsStateIsPlaying;
	VKVideoPlayer* _videoPlayer;
	id<UIViewControllerTransitioningDelegate> _transitionManager;
	VKVideo* _video;
	FullScreenVideoPlayerControlsView* _controlsView;
	UITapGestureRecognizer* _tapGestureRecognizer;
	NSTimer* _controlsHideDelayTimer;
	NSTimer* _scrubbingUpdateTimer;
	KVOObserver* _videoPlayerObserver;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) id<UIViewControllerTransitioningDelegate> transitionManager;
@property(assign, nonatomic) BOOL mustCreatePlayer;
@property(readonly, assign, nonatomic) VideoContainerView* videoContainerView;
@property(readonly, assign, nonatomic) VKVideoPlayer* videoPlayer;
@property(retain, nonatomic) VideoPlayerModel* model;
@property(retain, nonatomic) KVOObserver* videoPlayerObserver;
@property(assign, nonatomic) BOOL manuallyPausedVideo;
@property(assign, nonatomic) BOOL shouldAutoHideControlsAsSoonAsStateIsPlaying;
@property(assign, nonatomic) BOOL audioPlayerWasPlayingBeforeAppear;
@property(assign, nonatomic) BOOL wasPlayingBeforeApplicationResignedActive;
@property(assign, nonatomic) BOOL wasPlayingBeforeDisappear;
@property(assign, nonatomic) BOOL wasPlayingBeforeScrubbing;
@property(assign, nonatomic) BOOL viewDidAppearOnce;
@property(assign, nonatomic) BOOL playerCreatedHere;
@property(assign, nonatomic) BOOL showPlayPauseButtonAndScrubberOnNextTap;
@property(assign, nonatomic) BOOL dismissTransitionInProgress;
@property(assign, nonatomic) BOOL controlsHidden;
@property(assign, nonatomic) BOOL scrubbing;
@property(retain, nonatomic) NSTimer* scrubbingUpdateTimer;
@property(retain, nonatomic) NSTimer* controlsHideDelayTimer;
@property(retain, nonatomic) UITapGestureRecognizer* tapGestureRecognizer;
@property(retain, nonatomic) FullScreenVideoPlayerControlsView* controlsView;
@property(retain, nonatomic) VKVideo* video;
-(void).cxx_destruct;
-(void)modelLoadingChanged:(id)changed;
-(void)model:(id)model updated:(id)updated;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)willFinishPanGestureDismissTransition;
-(void)didFinishCancelPanGestureDismissTransition;
-(void)willCancelPanGestureDismissTransition;
-(void)willBeginPanGestureDismissTransition;
-(BOOL)canBeginPanGestureDismissTransition;
-(id)viewForDismissTransitionAnimation;
-(id)viewForDismissTransitionPanGesture;
-(void)fullScreenVideoPlayerControlsView:(id)view handleErrorOverlayRetryButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handleCommentsButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handleMoreButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handleShareButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handleLikeButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handleAddButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handleReplayButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handlePauseButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsView:(id)view handlePlayButtonTap:(id)tap;
-(void)fullScreenVideoPlayerControlsViewDidEndScrubbing:(id)fullScreenVideoPlayerControlsView;
-(void)fullScreenVideoPlayerControlsView:(id)view didScrubToValue:(float)value;
-(void)fullScreenVideoPlayerControlsViewWillBeginScrubbing:(id)fullScreenVideoPlayerControlsView;
-(void)fullScreenVideoPlayerControlsView:(id)view handleCloseButtonTap:(id)tap;
-(void)handleAudioSessionInterruptionNotification:(id)notification;
-(void)handleAudioSessionRouteChangeNotification:(id)notification;
-(void)handleApplicationDidBecomActiveNotification:(id)handleApplication;
-(void)handleApplicationWillResignActiveNotification:(id)handleApplication;
-(void)handleVideoViewTap:(id)tap;
-(void)handleVideoPlayerLoadedVideoTimeChanged:(double)changed;
-(void)handleVideoPlayerCurrentTimeChanged:(double)changed;
-(void)handleVideoPlayerStateChange:(id)change prevState:(id)state;
-(void)attachVideoPlayer:(id)player;
-(void)deattachCurrentVideoPlayer;
-(BOOL)canShowPlayPauseButton;
-(BOOL)canShowScrubber;
-(void)createPlayer;
-(void)ensureHasPlayer;
-(void)updateForVideoPlayerState;
-(void)tearDownVideoPlayerKVOObserver;
-(void)setupKVOObserverForPlayer:(id)player;
-(void)updateScrubberBufferProgressForLoadedTime:(double)loadedTime;
-(void)updatePlaybackDurationLabelsWithTotalDuration:(double)totalDuration currentTime:(double)time;
-(void)updateScrubberFromVideoPlayerCurrentTime;
-(void)updateVideoPlayerCurrentTimeFromScrubber;
-(void)hideControlsWithDelayIfNeeded;
-(void)setControlsHidden:(BOOL)hidden animated:(BOOL)animated afterDelay:(double)delay force:(BOOL)force;
-(void)setControlsHidden:(BOOL)hidden animated:(BOOL)animated afterDelay:(double)delay;
-(void)setControlsHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)viewWillTransitionToSize:(CGSize)view withTransitionCoordinator:(id)transitionCoordinator;
-(void)configureVideoPlayerVideoContainerViewIfNeeded:(id)needed;
-(BOOL)shouldAutorotate;
-(int)preferredInterfaceOrientationForPresentation;
-(void)viewWillLayoutSubviews;
-(int)preferredStatusBarStyle;
-(int)preferredStatusBarUpdateAnimation;
-(BOOL)prefersStatusBarHidden;
-(unsigned)supportedInterfaceOrientations;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithMain:(id)main andModel:(id)model;
@end

