/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "VKMLiveController.h"

@class VideoAlbumsModel, VideoAlbumsInfoToolbar;

__attribute__((visibility("hidden")))
@interface VideoAlbumsController : VKMLiveController {
	VideoAlbumsInfoToolbar* _toolbar;
}
@property(retain, nonatomic) VideoAlbumsModel* model;
@property(retain, nonatomic) VideoAlbumsInfoToolbar* toolbar;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)VKMRoute:(id)route context:(id)context;
-(void)actionAdd:(id)add;
-(void)dialogWithTitle:(id)title text:(id)text completeBlock:(id)block;
-(void)actionVideoAlbumsInfoSegment:(id)segment;
-(UIEdgeInsets)VKMControllerChromeInsetsAdjust:(UIEdgeInsets)adjust;
-(void)viewDidLoad;
-(void)VKMControllerSetAutocloseButton:(id)button;
-(void)loadView;
-(void)dealloc;
@end

