/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "VKClient-Structs.h"


__attribute__((visibility("hidden")))
@interface VideoQualityComponentState : XXUnknownSuperclass <NSCopying> {
	int _quality;
}
@property(assign, nonatomic) int quality;
-(id)copyWithZone:(NSZone*)zone;
@end

