/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "StatsEvent.h"

@class NSString, StatsRef;

__attribute__((visibility("hidden")))
@interface ViewPostEvent : XXUnknownSuperclass <StatsEvent> {
	NSString* _postId;
	StatsRef* _ref;
	double _duration;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) StatsRef* ref;
@property(readonly, assign, nonatomic) double duration;
@property(readonly, copy, nonatomic) NSString* postId;
+(id)post:(id)post duration:(double)duration ref:(id)ref;
+(id)postId:(id)anId duration:(double)duration ref:(id)ref;
-(id)initWithPostId:(id)postId duration:(double)duration ref:(id)ref;
-(void)dealloc;
@end

