/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "VKAPTabViewControllerProtocol.h"
#import "VideoAlbumController.h"

@class VKVideoAlbum, VKAPModel, NSString;

__attribute__((visibility("hidden")))
@interface VKAPVideoAlbumViewController : VideoAlbumController <VKAPTabViewControllerProtocol> {
	BOOL searchWorkaroundEnabled;
	id _expandParent;
	VKAPModel* _pickerModel;
	VKVideoAlbum* _selectedAlbum;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak VKAPModel* pickerModel;
@property(copy, nonatomic) id expandParent;
@property(retain, nonatomic) VKVideoAlbum* selectedAlbum;
-(void).cxx_destruct;
-(void)clearModelItemsAndReset;
-(void)openAlbumsPickerAction:(id)action;
-(void)updateTitleView;
-(id)scrollView;
-(BOOL)VKMScrollViewDisablePTR;
-(int)VKMTableSearchMode;
-(BOOL)VKMScrollViewShouldShowTeaser;
-(void)VKMNavigationBarUpdate;
-(void)viewWillAppear:(BOOL)view;
-(UIEdgeInsets)VKMControllerChromeInsetsAdjust:(UIEdgeInsets)adjust;
-(id)vkm_containerController;
-(void)searchControllerDidChangedActive:(id)searchController;
-(void)searchControllerChangedActive:(id)active;
@end

