/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface VKApplication : XXUnknownSuperclass {
}
+(float)topmostWindowLevel;
+(BOOL)force:(id)force;
-(BOOL)openURL:(id)url force:(BOOL)force;
-(void)_openURL:(id)url originatingView:(id)view completionHandler:(id)handler;
-(BOOL)openURL:(id)url;
@end

