/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomainDerived.h"

@class VKAPIApp, NSArray;

__attribute__((visibility("hidden")))
@interface VKAPIAppWithRequests : VKDomainDerived {
	NSArray* _requests;
}
@property(copy, nonatomic) NSArray* requests;
@property(readonly, retain, nonatomic) VKAPIApp* domain;
+(id)from:(id)from requests:(id)requests;
-(void)dealloc;
@end

