/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MainModel, NSDictionary;
@protocol VKAPNSHandlerDelegate;

__attribute__((visibility("hidden")))
@interface VKAPNSHandler : XXUnknownSuperclass {
	MainModel* _main;
	id<VKAPNSHandlerDelegate> _strongDelegate;
	NSDictionary* _payload;
	NSDictionary* _data;
}
@property(retain, nonatomic) NSDictionary* data;
@property(retain, nonatomic) NSDictionary* payload;
@property(retain, nonatomic) id<VKAPNSHandlerDelegate> strongDelegate;
@property(retain, nonatomic) MainModel* main;
+(id)userNotificationCategory;
-(void).cxx_destruct;
-(id)groupIdFromGroupId;
-(id)userIdFromUid;
-(void)notifyEventForGroupId:(id)groupId;
-(void)notifyEventForUserId:(id)userId completionBlock:(id)block;
-(void)notifyEventForUserId:(id)userId;
-(void)notifyAlert:(id)alert;
-(void)handleActionIdentifier:(id)identifier responseInfo:(id)info completionHandler:(id)handler;
-(void)handleActionIdentifier:(id)identifier completionHandler:(id)handler;
-(void)notify;
-(void)handle;
@end

