/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKAppInternalNotification.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VKAppInternalNotificationBubble : VKAppInternalNotification {
	NSString* _title;
	NSString* _message;
}
@property(copy, nonatomic) NSString* message;
@property(copy, nonatomic) NSString* title;
-(void).cxx_destruct;
@end

