/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol VKAPModelDelegate <NSObject>
-(void)vkapModelSelectedLimit:(id)limit;
-(void)vkapModelNeedDismissPicker:(id)picker;
-(void)vkapModelNeedUpdateToolbar:(id)toolbar;
-(void)vkapModel:(id)model shouldUpdateTitle:(id)title;
-(void)vkapModel:(id)model didChangeTab:(int)tab;
@end

