/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface VKAudioPlayerModel : XXUnknownSuperclass {
	BOOL _shuffle;
	BOOL _repeat;
	int _selectedItemIndex;
	NSArray* _playerItemsStraight;
	NSArray* _playerItemsShuffled;
}
@property(assign, nonatomic) BOOL repeat;
@property(assign, nonatomic) BOOL shuffle;
@property(assign, nonatomic) int selectedItemIndex;
@property(retain, nonatomic) NSArray* playerItemsShuffled;
@property(retain, nonatomic) NSArray* playerItemsStraight;
+(id)from:(id)from context:(int)context playlistIden:(id)iden;
-(void).cxx_destruct;
-(id)nowPlayingItems;
-(int)prevIndex;
-(int)nextIndex;
-(void)shuffle:(BOOL)shuffle;
-(void)repeat:(BOOL)repeat;
-(void)select:(unsigned)select;
-(void)insertItems:(id)items afterObject:(id)object;
-(BOOL)insert:(id)insert at:(unsigned)at context:(int)context playlistIden:(id)iden;
-(BOOL)remove:(unsigned)remove;
-(BOOL)move:(unsigned)move to:(unsigned)to;
-(BOOL)selectedItemIsLast;
-(int)indexOfObject:(id)object;
-(id)objectAtIndex:(int)index;
-(id)itemSearchByAVPlayerItem:(id)item;
-(int)numberOfItems;
-(id)shuffleArray:(id)array;
-(id)playerItemsArrayFrom:(id)from context:(int)context playlistIden:(id)iden;
-(void)insertNext:(id)next context:(int)context playlistIden:(id)iden;
-(id)initWithList:(id)list context:(int)context playlistIden:(id)iden;
@end

