/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomain.h"
#import "vkclient-Structs.h"

@class VKAudioThumb, NSString;

__attribute__((visibility("hidden")))
@interface VKAudioPlaylistAlbum : VKDomain {
	NSString* _title;
	VKAudioThumb* _thumb;
}
@property(retain, nonatomic) VKAudioThumb* thumb;
@property(retain, nonatomic) NSString* title;
-(id)pickSingleImageUrlForSize:(CGSize)size scale:(float)scale;
-(BOOL)process:(id)process context:(id)context;
-(void)dealloc;
@end

