/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIButton;

__attribute__((visibility("hidden")))
@interface VKAudioMoreButton : XXUnknownSuperclass {
	UILabel* _durationLabel;
	UIButton* _moreButton;
}
@property(retain, nonatomic) UIButton* moreButton;
@property(retain, nonatomic) UILabel* durationLabel;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(id)createSubviews;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

