/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import "VKGifAVWriterDelegate.h"
#import "VKGifAVDecoderDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "VKGifAVReaderDelegate.h"

@class VKGifAVReader, NSURLSessionConfiguration, VKGifAVWriter, VKGifAVDecoder, NSString, NSURL;
@protocol VKAVGifConverterDelegate;

__attribute__((visibility("hidden")))
@interface VKAVGifConverter : XXUnknownSuperclass <VKGifAVReaderDelegate, VKGifAVDecoderDelegate, VKGifAVWriterDelegate> {
	id<VKAVGifConverterDelegate> _delegate;
	NSURL* _sourceURL;
	NSURLSessionConfiguration* _sessionConfiguration;
	NSURL* _targetURL;
	VKGifAVReader* _reader;
	VKGifAVDecoder* _decoder;
	VKGifAVWriter* _writer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<VKAVGifConverterDelegate> delegate;
@property(retain, nonatomic) VKGifAVWriter* writer;
@property(retain, nonatomic) VKGifAVDecoder* decoder;
@property(retain, nonatomic) VKGifAVReader* reader;
@property(retain, nonatomic) NSURL* targetURL;
@property(retain, nonatomic) NSURL* sourceURL;
@property(retain, nonatomic) NSURLSessionConfiguration* sessionConfiguration;
+(id)converterWithSessionConfiguration:(id)sessionConfiguration;
+(id)converter;
-(void).cxx_destruct;
-(void)gifWriter:(id)writer didFinishedWithFileURL:(id)fileURL videoSize:(CGSize)size;
-(void)gifDecoderDidFinishDecoding:(id)gifDecoder;
-(BOOL)gifDecoder:(id)decoder didDecodeFrame:(id)frame;
-(void)gifAVReader:(id)reader didFoundTotalGifBytes:(long long)bytes;
-(void)gifAVReader:(id)reader didFailedWithError:(id)error;
-(void)gifAVReader:(id)reader didFetchData:(id)data withProgress:(float)progress;
-(void)convertGifWithURL:(id)url outputFileURL:(id)url2;
-(void)convertGifWithURL:(id)url;
-(void)reuse;
-(id)initWithSessionConfiguration:(id)sessionConfiguration;
-(void)dealloc;
@end

