/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol VKConfigurationReader <NSObject>
-(id)dictionary;
-(BOOL)boolForKey:(id)key;
-(id)stringForKey:(id)key;
-(id)objectForKey:(id)key;
@end

