/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface VKCurrency : VKRenderable {
	NSNumber* _id;
	NSString* _name;
}
@property(copy, nonatomic) NSString* name;
@property(retain, nonatomic) NSNumber* id;
+(id)currencyWithID:(id)anId name:(id)name;
+(void)load;
-(BOOL)process:(id)process context:(id)context;
-(void)dealloc;
@end

