/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKFeed.h"

@class NSDictionary, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface VKFeedAds : VKFeed {
	BOOL _statsImperssionHandled;
	BOOL _statsLoadHandled;
	NSArray* _ads;
	NSString* _ads_debug;
	NSString* _title;
	NSDictionary* _ads_statistics;
}
@property(assign, nonatomic) BOOL statsLoadHandled;
@property(assign, nonatomic) BOOL statsImperssionHandled;
@property(retain, nonatomic) NSDictionary* ads_statistics;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* ads_debug;
@property(retain, nonatomic) NSArray* ads;
-(id)statusForSource:(id)source;
-(void)acceptSources:(id)sources;
-(id)firstItem;
-(int)type;
-(BOOL)process:(id)process context:(id)context;
-(void)dealloc;
@end

