/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

__attribute__((visibility("hidden")))
@interface VKGifDecodedFrame : XXUnknownSuperclass {
	UIImage* _frameImage;
	int _frameDelay;
	int _frameNumber;
}
@property(assign, nonatomic) int frameNumber;
@property(assign, nonatomic) int frameDelay;
@property(retain, nonatomic) UIImage* frameImage;
-(void).cxx_destruct;
-(id)description;
@end

