/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"
#import "vkclient-Structs.h"


@protocol VKGifAVWriterDelegate <NSObject>
-(void)gifWriter:(id)writer didFinishedWithFileURL:(id)fileURL videoSize:(CGSize)size;
@end

