/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class VKWikiPage, PriceRange, NSNumber, VKCurrency;

__attribute__((visibility("hidden")))
@interface VKGroupMarketInfo : XXUnknownSuperclass {
	BOOL _enabled;
	NSNumber* _contactID;
	VKCurrency* _currency;
	NSNumber* _mainAlbumID;
	PriceRange* _priceRange;
	VKWikiPage* _wiki;
}
@property(readonly, retain, nonatomic) VKWikiPage* wiki;
@property(readonly, retain, nonatomic) PriceRange* priceRange;
@property(readonly, retain, nonatomic) NSNumber* mainAlbumID;
@property(readonly, assign, nonatomic, getter=isEnabled) BOOL enabled;
@property(readonly, retain, nonatomic) VKCurrency* currency;
@property(readonly, retain, nonatomic) NSNumber* contactID;
+(id)parse:(id)parse;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

