/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomain.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface VKGroupsCatalogInfo : VKDomain {
	BOOL _enabled;
	NSArray* _categories;
}
@property(retain, nonatomic) NSArray* categories;
@property(assign, nonatomic) BOOL enabled;
-(id)categoryIds;
-(BOOL)process:(id)process context:(id)context;
-(void)dealloc;
@end

