/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKImageFilter.h"
#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface VKImageFilterVKMImageType : XXUnknownSuperclass <VKImageFilter> {
	XXStruct_UOIMaD _type;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) XXStruct_UOIMaD type;
+(id)imageType:(XXStruct_UOIMaD)type;
-(id)infoString;
-(id)process:(id)process;
-(id)initWithImageType:(XXStruct_UOIMaD)imageType;
@end

