/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface VKImageVariant : XXUnknownSuperclass {
	NSString* _src;
	int _width;
	int _height;
	int _type;
}
@property(assign, nonatomic) int type;
@property(assign, nonatomic) int height;
@property(assign, nonatomic) int width;
@property(retain, nonatomic) NSString* src;
+(id)variantForType:(int)type src:(id)src;
+(id)parsePhotoVariant:(id)variant;
-(float)ratio;
-(id)description;
-(void)dealloc;
@end

