/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKTextPage.h"
#import "VKDomain.h"

@class NSURL, VKLink, NSString;

__attribute__((visibility("hidden")))
@interface VKLinkPage : VKDomain <VKTextPage> {
	VKLink* _link;
	NSURL* _url;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSURL* url;
@property(retain, nonatomic) VKLink* link;
+(id)pageForLink:(id)link;
-(id)URLForTextPage;
-(void)dealloc;
@end

