/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TimerTargetDelegate.h"
#import "Model.h"

@class TimerTarget, NSString;

__attribute__((visibility("hidden")))
@interface VKLookupSourceFake : Model <TimerTargetDelegate> {
	TimerTarget* _timer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) TimerTarget* timer;
-(void).cxx_destruct;
-(id)fakeUsers;
-(id)fakeUser;
-(void)timerTargetFired:(id)fired;
-(void)stop;
-(void)start;
-(void)activate;
-(void)dealloc;
@end

