/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMBrowserTarget.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VKMHtmlTarget : VKMBrowserTarget {
	NSString* _html;
}
@property(retain, nonatomic) NSString* html;
+(id)targetWithHTML:(id)html;
-(void)reload;
-(id)targetURL;
-(id)title;
-(void)stop;
-(void)load;
-(void)dealloc;
@end

