/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class VKMLabelRender;

__attribute__((visibility("hidden")))
@interface VKMLabel : XXUnknownSuperclass {
	VKMLabelRender* _render;
	VKMLabelRender* _renderHighlighted;
}
@property(retain, nonatomic) VKMLabelRender* renderHighlighted;
@property(retain, nonatomic) VKMLabelRender* render;
-(id)accessibilityLabel;
-(BOOL)isAccessibilityElement;
-(void)drawRect:(CGRect)rect;
-(void)render:(id)render;
-(void)dealloc;
@end

