/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMImageView.h"
#import "vkclient-Structs.h"

@class ActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface VKMStickerPreviewImageView : VKMImageView {
	ActivityIndicatorView* _loadingIndicator;
}
@property(retain, nonatomic) ActivityIndicatorView* loadingIndicator;
-(void)reuse;
-(void)stopLoadingAnimation;
-(void)startLoadingAnimation;
-(void)loader:(id)loader complete:(id)complete;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

