/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface VKMStoreUtils : XXUnknownSuperclass {
}
+(BOOL)updatedDialog:(id)dialog withData:(id)data;
+(BOOL)updatedDialog:(id)dialog withTitle:(id)title photo:(id)photo;
+(BOOL)updatedMessage:(id)message preview:(BOOL)preview withDialogOrMessageData:(id)dialogOrMessageData;
+(void)restoreDeleted:(id)deleted;
+(void)markDeleted:(id)deleted;
+(BOOL)updateUser:(id)user withData:(id)data force:(BOOL)force;
@end

