/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "vkclient-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UISegmentedControl;

__attribute__((visibility("hidden")))
@interface VKMTableViewSearchHeaderView : XXUnknownSuperclass {
	UISegmentedControl* _scopes;
}
@property(retain, nonatomic) UISegmentedControl* scopes;
-(void)layoutSubviews;
-(void)setSegments:(id)segments;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

