/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKMStoreContext.h"
#import "VKLPSUpdateVisitor.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VKMUpdateContext : VKMStoreContext <VKLPSUpdateVisitor> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(BOOL)readStateForMessage:(id)message withPeer:(id)peer incoming:(BOOL)incoming context:(id)context;
-(void)messagesCounter:(id)counter;
-(void)user:(id)user typingInChat:(id)chat context:(id)context;
-(void)user:(id)user online:(BOOL)online flags:(unsigned)flags context:(id)context;
-(void)chatUpdated:(id)updated user:(BOOL)user context:(id)context;
-(void)message:(id)message restored:(BOOL)restored read:(id)read did:(id)did uid:(id)uid date:(id)date title:(id)title body:(id)body att:(BOOL)att randomId:(id)anId context:(id)context;
-(void)readUpdatePeer:(id)peer beforeMid:(id)mid incoming:(BOOL)incoming context:(id)context;
-(void)messageRemoved:(id)removed context:(id)context;
-(void)messageUpdated:(id)updated read:(BOOL)read context:(id)context;
-(void)updateMessage:(id)message read:(BOOL)read context:(id)context;
-(void)updateWithLPSParser:(id)lpsparser andData:(id)data complete:(id)complete;
-(id)collectMessagesWithData:(id)data;
-(void)updateRemoveDay:(id)day;
-(void)updateMarkDialog:(id)dialog untilMid:(id)mid complete:(id)complete;
-(void)updateMarkReadMessages:(id)messages complete:(id)complete;
-(void)updateMessagesMarks:(id)marks update:(id)update;
-(void)updateDeleteMessages:(id)messages complete:(id)complete;
-(void)processRemoveMessage:(id)message update:(id)update;
-(void)updateMarkDeleteDialog:(id)dialog complete:(id)complete;
-(void)updateMessagesWithData:(id)data justSent:(id)sent preview:(BOOL)preview complete:(id)complete;
-(void)updateMessagesWithData:(id)data dialog:(id)dialog previousMID:(id)mid lastPage:(BOOL)page user:(id)user complete:(id)complete;
-(void)processMessageData:(id)data did:(id)did setHead:(BOOL)head checkHead:(BOOL)head4 justSent:(id)sent preview:(BOOL)preview withDialogData:(BOOL)dialogData updatData:(id)data8 updates:(id)updates;
-(void)updateDialogsWithData:(id)data dialogs:(id)dialogs previousMID:(id)mid lastPage:(BOOL)page complete:(id)complete;
-(void)updateDialogWithData:(id)data dialogId:(id)anId complete:(id)complete;
-(void)processDialogData:(id)data updateData:(id)data2 updates:(id)updates;
-(void)processSetHead:(id)head forDialog:(id)dialog updates:(id)updates;
-(id)predicateForMessagesListWithIds:(id)ids previousMID:(id)mid lastMID:(id)mid3 lastPage:(BOOL)page messagesForDID:(id)did;
-(void)updateOwnersWithData:(id)data complete:(id)complete;
-(void)updateUsersWithData:(id)data complete:(id)complete;
-(id)processUsersData:(id)data groupsData:(id)data2;
@end

