/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "vkclient-Structs.h"


__attribute__((visibility("hidden")))
@interface VKMUI : XXUnknownSuperclass {
}
+(id)topMostWindow;
+(BOOL)windowIsUtility:(id)utility;
+(void)hideStatusBar:(BOOL)bar animation:(int)animation inApplicationContext:(id)applicationContext;
+(void)tableViewCell:(id)cell forceSeparatorInset:(UIEdgeInsets)inset;
+(id)tableViewForCell:(id)cell;
+(void)navigationItem:(id)item useRightBarButtonItem:(id)item2;
+(void)alignNavTitleSubview:(id)subview desiredWidth:(float)width;
+(void)bump:(id)bump;
+(void)twitch:(id)twitch;
+(void)shake:(id)shake;
+(void)animateWithKeyboard:(id)keyboard delay:(double)delay options:(unsigned)options animations:(id)animations completion:(id)completion;
+(id)sample:(id)sample image:(id)image;
+(int)countSubviews:(id)subviews;
+(id)debugAlign:(id)align inWindow:(id)window;
+(void)debugScrollToTopInWindow:(id)window;
+(void)dumpView:(id)view;
+(void)hint:(id)hint;
+(id)actionButtonOfPriority:(unsigned)priority title:(id)title target:(id)target action:(SEL)action;
+(XXStruct_Xx1ZfA)actionButtonPropertiesOfPriority:(unsigned)priority;
+(id)actionButtonFont;
+(void)addLightBlurBackgroundForView:(id)view;
+(id)lightBlurView;
+(id)searchBarWithDarkStyle:(BOOL)darkStyle;
+(id)menuSectionHeader:(id)header;
+(id)sectionHeaderLabel:(CGRect)label;
+(id)separator:(id)separator host:(id)host bottom:(BOOL)bottom;
+(id)separator:(id)separator host:(id)host bottom:(BOOL)bottom nohighlight:(BOOL)nohighlight inset:(float)inset;
+(id)blueSelectedBackground;
+(id)loadingAnimation:(BOOL)animation;
+(id)onlineView;
+(void)profileButton:(id)button renderSelected:(BOOL)selected;
+(id)profileButton:(BOOL)button;
+(id)composeBarButtonItem:(id)item action:(SEL)action;
+(id)plusBarButtonItem:(id)item action:(SEL)action;
+(id)actionsButton:(id)button action:(SEL)action;
+(id)doneButton:(id)button action:(SEL)action;
+(id)barButtonImage:(id)image target:(id)target action:(SEL)action;
+(id)avatarBorder;
+(void)customizePasswordField:(id)field;
+(void)customizeSearchBarContainedInNavigationBar:(id)navigationBar;
+(void)customizeWhiteNavigationBar:(id)bar;
+(void)customizeNavigationBar:(id)bar customized:(BOOL)customized;
+(void)setupNavigationBarAppearance;
+(void)setupWithInterfaceOrientation:(int)interfaceOrientation;
@end

