/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SiteActionController.h"
#import "vkclient-Structs.h"


__attribute__((visibility("hidden")))
@interface VKP2PSendWebViewController : SiteActionController {
}
-(void)viewWillAppear:(BOOL)view;
-(void)configureLeftBarButtonItem;
-(void)configureNavigationItemTitleView;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithMain:(id)main andModel:(id)model;
@end

