/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface VKPhotoDetails : XXUnknownSuperclass {
	BOOL _user_likes;
	BOOL _user_reposted;
	BOOL _missing;
	int _likes_count;
	int _comments_count;
	int _reposts_count;
	int _tags_count;
}
@property(assign, nonatomic) BOOL missing;
@property(assign, nonatomic) BOOL user_reposted;
@property(assign, nonatomic) BOOL user_likes;
@property(assign, nonatomic) int tags_count;
@property(assign, nonatomic) int reposts_count;
@property(assign, nonatomic) int comments_count;
@property(assign, nonatomic) int likes_count;
+(id)missing;
+(id)likes:(id)likes comments:(id)comments reposts:(id)reposts userReposted:(id)reposted tags:(id)tags user:(id)user;
-(void)offsetComments:(int)comments;
@end

