/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomainDerived.h"
#import "VKPhotoEdit.h"

@class VKPhoto, NSString;

__attribute__((visibility("hidden")))
@interface VKPhotoEditItem : VKDomainDerived <VKPhotoEdit> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) VKPhoto* domain;
-(id)photoEditDescription;
-(id)photoEditTitle;
-(id)photoEditThumbnail;
-(BOOL)isEqualItemId:(id)anId;
-(BOOL)isEqualIdentity:(id)identity;
-(Class)rendererClass;
@end

