/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKRenderable.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface VKPhotoRow : VKRenderable {
	NSArray* _photos;
}
@property(retain, nonatomic) NSArray* photos;
-(Class)cellClass;
-(void)dealloc;
@end

