/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomain.h"
#import "VKThumbnailable.h"
#import "VKSourceStatus.h"
#import "vkclient-Structs.h"

@class VKGeo, VKText, VKAttachments, NSNumber, VKIdentity, NSArray, VKPostSource, NSString, NSDictionary;
@protocol VKSource;

__attribute__((visibility("hidden")))
@interface VKPost : VKDomain <VKThumbnailable, VKSourceStatus> {
	BOOL _can_publish_privacy;
	BOOL _can_delete;
	BOOL _can_edit;
	BOOL _can_pin;
	BOOL _can_publish;
	BOOL _final_post;
	NSNumber* _from_id;
	unsigned _date;
	VKText* _text;
	VKGeo* _geo;
	NSNumber* _signer_id;
	VKAttachments* _attachments;
	int _sourceData;
	int _post_type;
	NSNumber* _created_by;
	VKIdentity* _reply_post;
	NSArray* _cop_history;
	VKPost* _cop_post;
	id<VKSource> _source;
	id<VKSource> _signer;
	int _statusMask;
	VKPostSource* _post_source;
	NSString* _post_identity;
	NSDictionary* _statistics;
	XXStruct_86WktA _comments;
	XXStruct_uR0cxB _likes;
	XXStruct_86WktA _reposts;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSDictionary* statistics;
@property(retain, nonatomic) NSString* post_identity;
@property(retain, nonatomic) VKPostSource* post_source;
@property(assign, nonatomic) int statusMask;
@property(retain, nonatomic) id<VKSource> signer;
@property(retain, nonatomic) id<VKSource> source;
@property(retain, nonatomic) VKPost* cop_post;
@property(retain, nonatomic) NSArray* cop_history;
@property(retain, nonatomic) VKIdentity* reply_post;
@property(assign, nonatomic) BOOL final_post;
@property(retain, nonatomic) NSNumber* created_by;
@property(assign, nonatomic) BOOL can_publish;
@property(assign, nonatomic) int post_type;
@property(assign, nonatomic) BOOL can_pin;
@property(assign, nonatomic) BOOL can_edit;
@property(assign, nonatomic) BOOL can_delete;
@property(assign, nonatomic) BOOL can_publish_privacy;
@property(assign, nonatomic) int sourceData;
@property(retain, nonatomic) VKAttachments* attachments;
@property(retain, nonatomic) NSNumber* signer_id;
@property(retain, nonatomic) VKGeo* geo;
@property(assign, nonatomic) XXStruct_86WktA reposts;
@property(assign, nonatomic) XXStruct_uR0cxB likes;
@property(assign, nonatomic) XXStruct_86WktA comments;
@property(retain, nonatomic) VKText* text;
@property(assign, nonatomic) unsigned date;
@property(retain, nonatomic) NSNumber* from_id;
+(void)initialize;
-(void)updatePinned:(BOOL)pinned;
-(void)acceptSources:(id)sources;
-(void)offsetComments:(int)comments;
-(void)updateReposts:(int)reposts user:(BOOL)user;
-(void)updateLikes:(id)likes companion:(id)companion user:(BOOL)user;
-(void)updateLike:(BOOL)like;
-(id)companionPhoto;
-(id)repostTargetItem;
-(id)repostTargetIdentity;
-(id)statusForSource:(id)source;
-(id)thumbnailUrl;
-(BOOL)process:(id)process context:(id)context;
-(void)domainOnEditCopy:(id)copy;
-(void)dealloc;
-(BOOL)canBeUsedAsInitialForDetail;
@end

