/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface VKPPSelectButton : XXUnknownSuperclass {
}
+(id)selectButton;
+(void)initialize;
-(void)animateSelected:(BOOL)selected;
-(void)selectButtonToggle:(id)toggle;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)setHighlighted:(BOOL)highlighted;
@end

