/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PHAsset;

@interface VKPPAssetImageView : XXUnknownSuperclass {
	PHAsset* _asset;
}
@property(retain, nonatomic) PHAsset* asset;
-(void)dealloc;
@end

