/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKClient-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "VKPPAssetPresenter.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDataSource.h"

@class VKPPModel, NSString, NSMutableSet;

@interface VKPPThumbsCollectionView : XXUnknownSuperclass <UIGestureRecognizerDelegate, UICollectionViewDelegate, UICollectionViewDataSource, VKPPAssetPresenter> {
	CGSize assetGridThumbnailSize;
	int photosInRow;
	BOOL viewDidScroll;
	BOOL _fullScreenPicker;
	BOOL _showCamera;
	VKPPModel* _model;
	NSMutableSet* _pannedURLs;
	CGRect _previousPreheatRect;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL fullScreenPicker;
@property(retain, nonatomic) VKPPModel* model;
@property(assign, nonatomic) CGRect previousPreheatRect;
@property(assign, nonatomic) BOOL showCamera;
@property(retain, nonatomic) NSMutableSet* pannedURLs;
-(void).cxx_destruct;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)collectionView:(id)view didSelectItemAtIndexPath:(id)indexPath;
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;
-(int)extraIndex;
-(CGAffineTransform)assetTransform;
-(void)handleAssetPresented:(BOOL)presented;
-(id)viewForPresentedAsset;
-(void)notificationTargetEdit:(id)edit;
-(void)notificationSelectedAsset:(id)asset;
-(void)notificationResetAssets:(id)assets;
-(void)handlePanGesture:(id)gesture;
-(id)thumbForAssetIndex:(unsigned)assetIndex;
-(void)actionThumbnailSelected:(id)selected;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame model:(id)model;
@end

