/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSString;

@interface VKPPStickyNavigationModalTransitioning : XXUnknownSuperclass <UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate> {
	BOOL _reverse;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL reverse;
+(id)sharedTransitioning;
-(id)animationControllerForDismissedController:(id)dismissedController;
-(id)animationControllerForPresentedController:(id)presentedController presentingController:(id)controller sourceController:(id)controller3;
-(void)animateTransition:(id)transition;
-(double)transitionDuration:(id)duration;
-(void)presentController:(id)controller fromController:(id)controller2 animated:(BOOL)animated;
@end

