/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomain.h"

@class VKCountry, NSDate, NSString, VKUser, VKCity, VKNameRequest;

__attribute__((visibility("hidden")))
@interface VKProfileInfo : VKDomain {
	NSString* _first_name;
	NSString* _last_name;
	NSString* _maiden_name;
	int _sex;
	int _relation;
	VKUser* _relation_partner;
	NSDate* _bdate;
	int _bdate_visibility;
	NSString* _home_town;
	VKCountry* _country;
	VKCity* _city;
	VKNameRequest* _name_request;
}
@property(retain, nonatomic) VKNameRequest* name_request;
@property(retain, nonatomic) VKCity* city;
@property(retain, nonatomic) VKCountry* country;
@property(retain, nonatomic) NSString* home_town;
@property(assign, nonatomic) int bdate_visibility;
@property(retain, nonatomic) NSDate* bdate;
@property(retain, nonatomic) VKUser* relation_partner;
@property(assign, nonatomic) int relation;
@property(assign, nonatomic) int sex;
@property(retain, nonatomic) NSString* maiden_name;
@property(retain, nonatomic) NSString* last_name;
@property(retain, nonatomic) NSString* first_name;
-(BOOL)isEqual:(id)equal;
-(BOOL)process:(id)process context:(id)context;
-(void)domainOnEditCopy:(id)copy;
-(void)dealloc;
@end

