/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSError, VKRequest, NSDictionary;

__attribute__((visibility("hidden")))
@interface VKRequestResult : XXUnknownSuperclass {
	VKRequest* _request;
	NSError* _urlError;
	int _result;
	id _response;
	NSDictionary* _errors;
}
@property(retain, nonatomic) NSDictionary* errors;
@property(retain, nonatomic) id response;
@property(assign, nonatomic) int result;
@property(retain, nonatomic) NSError* urlError;
@property(retain, nonatomic) VKRequest* request;
+(id)resultWithJSONResponse:(id)jsonresponse request:(id)request;
+(id)resultWithError:(id)error request:(id)request;
+(id)resultWithResult:(int)result request:(id)request;
-(void).cxx_destruct;
-(int)resultWithExecuteErrors;
@end

