/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "StatsManagerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class ViewPostStatsManager, AdsStatsManager, NotificationsManager, VKClient, CommonStatsManager, VKConnectivityState, StickersRecentModel, VKOnlineStore, VKStats, VKPushSettings, VKGroupState, VideoUploadManager, ActivityModel, NSNumber, NSString, NSArray, StoreStockManager, ExternalAdsStatsManager, VKDB, VKMStore, NSURL;

__attribute__((visibility("hidden")))
@interface VKSession : XXUnknownSuperclass <StatsManagerDelegate> {
	BOOL _pendingIntroAfterSignup;
	BOOL _stickersGlobalPromotion;
	NSString* _token;
	NSNumber* _userId;
	NSString* _APNSToken;
	NSURL* _userDataDirectoryURL;
	VKPushSettings* _pushSettings;
	VKMStore* _store;
	VKClient* _client;
	VKStats* _stats;
	VKGroupState* _groups;
	NotificationsManager* _notifications;
	VKConnectivityState* _connectivity;
	ActivityModel* _weakActivity;
	VKDB* _db;
	VKOnlineStore* _online;
	CommonStatsManager* _statsManager;
	AdsStatsManager* _adsStatsManager;
	ExternalAdsStatsManager* _externalAdsStatsManager;
	ViewPostStatsManager* _viewPostStatsManager;
	StoreStockManager* _storeStockManager;
	StickersRecentModel* _stickersRecentModel;
	VideoUploadManager* _videoUploadManager;
	id _pendingProfileAsset;
	NSString* _pendingFacebookToken;
	int _lastKnownMainNewsfeedModelMode;
	int _forcedMainNewsfeedModelMode;
	int _stickersStoreNewItems;
	NSString* _stickersVersionHash;
	int _pendingAuthEventType;
	NSArray* _domains;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int pendingAuthEventType;
@property(retain, nonatomic) NSString* stickersVersionHash;
@property(assign, nonatomic) int stickersStoreNewItems;
@property(assign, nonatomic) BOOL stickersGlobalPromotion;
@property(assign, nonatomic) int forcedMainNewsfeedModelMode;
@property(assign, nonatomic) int lastKnownMainNewsfeedModelMode;
@property(assign, nonatomic) BOOL pendingIntroAfterSignup;
@property(retain, nonatomic) NSString* pendingFacebookToken;
@property(retain, nonatomic) id pendingProfileAsset;
@property(readonly, retain, nonatomic) VideoUploadManager* videoUploadManager;
@property(readonly, retain, nonatomic) StickersRecentModel* stickersRecentModel;
@property(readonly, retain, nonatomic) StoreStockManager* storeStockManager;
@property(readonly, retain, nonatomic) ViewPostStatsManager* viewPostStatsManager;
@property(readonly, retain, nonatomic) ExternalAdsStatsManager* externalAdsStatsManager;
@property(readonly, retain, nonatomic) AdsStatsManager* adsStatsManager;
@property(readonly, retain, nonatomic) CommonStatsManager* statsManager;
@property(readonly, retain, nonatomic) VKOnlineStore* online;
@property(readonly, retain, nonatomic) VKDB* db;
@property(assign, nonatomic) ActivityModel* weakActivity;
@property(readonly, retain, nonatomic) VKConnectivityState* connectivity;
@property(readonly, retain, nonatomic) NotificationsManager* notifications;
@property(readonly, retain, nonatomic) VKGroupState* groups;
@property(readonly, retain, nonatomic) VKStats* stats;
@property(readonly, retain, nonatomic) VKClient* client;
@property(readonly, retain, nonatomic) VKMStore* store;
@property(readonly, retain, nonatomic) NSURL* userDataDirectoryURL;
@property(retain, nonatomic) NSString* APNSToken;
@property(readonly, copy, nonatomic) NSNumber* userId;
@property(copy, nonatomic) NSString* token;
@property(retain, nonatomic) VKPushSettings* pushSettings;
@property(readonly, retain, nonatomic) NSArray* domains;
+(id)storedSession;
+(void)store:(id)store;
+(id)sessionWithUserId:(id)userId andToken:(id)token;
+(BOOL)open:(id)open;
-(void)statsManager:(id)manager didRegisterEvent:(id)event;
-(void)setSessionUser:(id)user;
-(void)trackAuthEventForUser:(id)user withType:(int)type;
-(void)changePushSettings:(id)settings;
-(void)updateToken:(id)token;
-(id)actionDomainForType:(int)type;
-(int)adminLevelFor:(id)aFor;
-(BOOL)isAdminFor:(id)aFor;
-(BOOL)isOwner:(id)owner;
-(void)dealloc;
-(id)initWithUserId:(id)userId andToken:(id)token;
-(BOOL)routeToActivity:(id)activity context:(int)context;
-(BOOL)routeToRequest:(id)request context:(int)context;
-(BOOL)routeToApp:(id)app url:(id)url source:(id)source context:(int)context;
-(BOOL)routeToAppId:(id)appId platfromId:(id)anId installed:(BOOL)installed installUrl:(id)url url:(id)url5 source:(id)source requestName:(id)name context:(int)context;
-(void)openAppStoreForProductId:(id)productId source:(id)source;
-(BOOL)routeFeedAds:(id)ads;
-(BOOL)routeFeedAds:(id)ads item:(id)item;
-(BOOL)routeFeedAds:(id)ads item:(id)item card:(id)card;
-(BOOL)routeSnapper:(id)snapper;
@end

