/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSNumber;

__attribute__((visibility("hidden")))
@interface VKSnippetRating : XXUnknownSuperclass {
	NSNumber* _stars;
	NSNumber* _reviews;
	NSString* _descr;
}
@property(retain, nonatomic) NSString* descr;
@property(retain, nonatomic) NSNumber* reviews;
@property(retain, nonatomic) NSNumber* stars;
-(void).cxx_destruct;
@end

