/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class VKDomain, UIImage;
@protocol VKThumbnailable;

@protocol VKThumbnailView <NSObject>
@property(readonly, assign, nonatomic) UIImage* image;
@property(assign, nonatomic) int renderedSize;
@property(retain, nonatomic) VKDomain<VKThumbnailable>* domain;
@end

