/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomainDerived.h"

@class VKTopic;

__attribute__((visibility("hidden")))
@interface VKTopicAtt : VKDomainDerived {
}
@property(retain, nonatomic) VKTopic* domain;
-(id)attachmentIco;
-(id)attachmentImage;
-(id)attachmentStatus:(BOOL)status;
-(id)attachmentTitle;
-(id)attachmentPlaceholder;
-(Class)rendererClass;
@end

