/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKDomainDerived.h"
#import "vkclient-Structs.h"


__attribute__((visibility("hidden")))
@interface VKVideoAutoplay : VKDomainDerived {
	XXStruct_pwHToB _position;
}
@property(assign, nonatomic) XXStruct_pwHToB position;
@end

