/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSError;

__attribute__((visibility("hidden")))
@interface VKVideoPlayerStateBuilder : XXUnknownSuperclass {
	BOOL _hasDisplayed;
	BOOL _preparedToPlay;
	BOOL _failedToPlay;
	BOOL _isAtEndOfVideo;
	unsigned _timeControlStatus;
	unsigned _desiredRateState;
	NSError* _error;
}
@property(copy, nonatomic) NSError* error;
@property(assign, nonatomic) BOOL isAtEndOfVideo;
@property(assign, nonatomic) BOOL failedToPlay;
@property(assign, nonatomic) BOOL preparedToPlay;
@property(assign, nonatomic) BOOL hasDisplayed;
@property(assign, nonatomic) unsigned desiredRateState;
@property(assign, nonatomic) unsigned timeControlStatus;
+(id)builderWithState:(id)state;
+(id)builder;
-(void).cxx_destruct;
-(id)build;
-(id)withError:(id)error;
-(id)withIsAtEndOfVideo:(BOOL)video;
-(id)withFailedToPlay:(BOOL)play;
-(id)withPreparedToPlay:(BOOL)play;
-(id)withHasDisplayed:(BOOL)hasDisplayed;
-(id)withDesiredRateState:(unsigned)desiredRateState;
-(id)withTimeControlStatus:(unsigned)timeControlStatus;
-(id)initWithState:(id)state;
-(id)init;
@end

