/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TimerTargetDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "VMRecordingSessionDelegate.h"

@class TimerTarget, VKOpusRecorder, NSString, VMSessionManager, AVAudioPlayer;
@protocol VMRecordingDelegate;

__attribute__((visibility("hidden")))
@interface VMRecording : XXUnknownSuperclass <VMRecordingSessionDelegate, TimerTargetDelegate> {
	id<VMRecordingDelegate> _delegate;
	VMSessionManager* _VMSessionManager;
	VKOpusRecorder* _recorder;
	AVAudioPlayer* _beginRecordSoundPlayer;
	TimerTarget* _timer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) VMSessionManager* VMSessionManager;
@property(assign, nonatomic) __weak id<VMRecordingDelegate> delegate;
@property(retain, nonatomic) TimerTarget* timer;
@property(retain, nonatomic) AVAudioPlayer* beginRecordSoundPlayer;
@property(retain, nonatomic) VKOpusRecorder* recorder;
-(void).cxx_destruct;
-(void)timerTargetFired:(id)fired;
-(void)recordingSessionGetCloseToEar:(id)ear;
-(void)recordingSessionGetAwayFromEar:(id)ear;
-(void)recordingSessionApplicationResignActiveOrInterrupted:(id)interrupted;
-(id)stopRecordingAndGetOpusRecord;
-(void)startRecorder;
-(void)startRecoringIsFromRiseToRecord:(BOOL)record;
-(void)dealloc;
@end

