/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Renderer.h"

@class VKWallExtra;

__attribute__((visibility("hidden")))
@interface WallExtraRenderer : Renderer {
}
@property(retain, nonatomic) VKWallExtra* domain;
+(void)prepareLayout:(id)layout;
-(void)renderCell:(id)cell;
-(void)setupCell:(id)cell;
@end

