/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface _AFURLSessionTaskSwizzling : XXUnknownSuperclass {
}
+(void)swizzleResumeAndSuspendMethodForClass:(Class)aClass;
+(void)load;
-(void)af_suspend;
-(void)af_resume;
-(int)state;
@end

