/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AFURLSessionManager.h"
#import "VK_Music-Structs.h"
#import "NSSecureCoding.h"
#import "NSCopying.h"

@class AFHTTPResponseSerializer, AFHTTPRequestSerializer, NSURL;
@protocol AFURLResponseSerialization, AFURLRequestSerialization;

@interface AFHTTPSessionManager : AFURLSessionManager <NSSecureCoding, NSCopying> {
	NSURL* _baseURL;
	AFHTTPRequestSerializer<AFURLRequestSerialization>* _requestSerializer;
}
@property(retain, nonatomic) AFHTTPResponseSerializer<AFURLResponseSerialization>* responseSerializer;
@property(retain, nonatomic) AFHTTPRequestSerializer<AFURLRequestSerialization>* requestSerializer;
@property(retain, nonatomic) NSURL* baseURL;
+(BOOL)supportsSecureCoding;
+(id)manager;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)description;
-(id)dataTaskWithHTTPMethod:(id)httpmethod URLString:(id)string parameters:(id)parameters success:(id)success failure:(id)failure;
-(id)DELETE:(id)aDelete parameters:(id)parameters success:(id)success failure:(id)failure;
-(id)PATCH:(id)patch parameters:(id)parameters success:(id)success failure:(id)failure;
-(id)PUT:(id)put parameters:(id)parameters success:(id)success failure:(id)failure;
-(id)POST:(id)post parameters:(id)parameters constructingBodyWithBlock:(id)block success:(id)success failure:(id)failure;
-(id)POST:(id)post parameters:(id)parameters success:(id)success failure:(id)failure;
-(id)HEAD:(id)head parameters:(id)parameters success:(id)success failure:(id)failure;
-(id)GET:(id)get parameters:(id)parameters success:(id)success failure:(id)failure;
-(id)initWithBaseURL:(id)baseURL sessionConfiguration:(id)configuration;
-(id)initWithSessionConfiguration:(id)sessionConfiguration;
-(id)initWithBaseURL:(id)baseURL;
-(id)init;
@end

