/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AFURLConnectionOperation.h"
#import "VK_Music-Structs.h"

@class AFHTTPResponseSerializer, NSError, NSHTTPURLResponse, NSRecursiveLock;
@protocol AFURLResponseSerialization;

@interface AFHTTPRequestOperation : AFURLConnectionOperation {
	AFHTTPResponseSerializer<AFURLResponseSerialization>* _responseSerializer;
	id _responseObject;
	NSError* _responseSerializationError;
}
@property(retain, nonatomic) AFHTTPResponseSerializer<AFURLResponseSerialization>* responseSerializer;
@property(retain, nonatomic) NSRecursiveLock* lock;
@property(retain, nonatomic) NSError* responseSerializationError;
@property(retain, nonatomic) id responseObject;
@property(retain, nonatomic) NSHTTPURLResponse* response;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)pause;
-(void)setCompletionBlockWithSuccess:(id)success failure:(id)failure;
-(id)error;
-(id)initWithRequest:(id)request;
@end

