/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"
#import "NSStreamDelegate.h"
#import "VK_Music-Structs.h"

@class AFHTTPBodyPart, NSError, NSInputStream, NSMutableArray, NSEnumerator, NSOutputStream, NSMutableData, NSString;

@interface AFMultipartBodyStream : XXUnknownSuperclass <NSCopying, NSStreamDelegate> {
	id<NSStreamDelegate> delegate;
	unsigned streamStatus;
	NSError* streamError;
	unsigned _numberOfBytesInPacket;
	NSInputStream* _inputStream;
	unsigned _stringEncoding;
	NSMutableArray* _HTTPBodyParts;
	NSEnumerator* _HTTPBodyPartEnumerator;
	AFHTTPBodyPart* _currentHTTPBodyPart;
	NSOutputStream* _outputStream;
	NSMutableData* _buffer;
	double _delay;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic, getter=isEmpty) BOOL empty;
@property(readonly, assign, nonatomic) unsigned long long contentLength;
@property(retain, nonatomic) NSInputStream* inputStream;
@property(assign, nonatomic) double delay;
@property(assign, nonatomic) unsigned numberOfBytesInPacket;
@property(retain, nonatomic) NSMutableData* buffer;
@property(retain, nonatomic) NSOutputStream* outputStream;
@property(retain, nonatomic) AFHTTPBodyPart* currentHTTPBodyPart;
@property(retain, nonatomic) NSEnumerator* HTTPBodyPartEnumerator;
@property(retain, nonatomic) NSMutableArray* HTTPBodyParts;
@property(assign, nonatomic) unsigned stringEncoding;
-(void)setStreamError:(id)error;
-(id)streamError;
-(void)setStreamStatus:(unsigned)status;
-(unsigned)streamStatus;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)_setCFClientFlags:(unsigned long)flags callback:(/*function-pointer*/ void*)callback context:(XXStruct_K1psTC*)context;
-(void)_unscheduleFromCFRunLoop:(CFRunLoopRef)cfrunLoop forMode:(CFStringRef)mode;
-(void)_scheduleInCFRunLoop:(CFRunLoopRef)cfrunLoop forMode:(CFStringRef)mode;
-(void)removeFromRunLoop:(id)runLoop forMode:(id)mode;
-(void)scheduleInRunLoop:(id)runLoop forMode:(id)mode;
-(BOOL)setProperty:(id)property forKey:(id)key;
-(id)propertyForKey:(id)key;
-(void)close;
-(void)open;
-(BOOL)hasBytesAvailable;
-(BOOL)getBuffer:(char**)buffer length:(unsigned*)length;
-(int)read:(char*)read maxLength:(unsigned)length;
-(void)appendHTTPBodyPart:(id)part;
-(void)setInitialAndFinalBoundaries;
-(id)initWithStringEncoding:(unsigned)stringEncoding;
@end

