/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AFHTTPRequestSerializer.h"
#import "VK_Music-Structs.h"


@interface AFPropertyListRequestSerializer : AFHTTPRequestSerializer {
	unsigned _format;
	unsigned _writeOptions;
}
@property(assign, nonatomic) unsigned writeOptions;
@property(assign, nonatomic) unsigned format;
+(id)serializerWithFormat:(unsigned)format writeOptions:(unsigned)options;
+(id)serializer;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)requestBySerializingRequest:(id)request withParameters:(id)parameters error:(id*)error;
@end

