/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL;

@interface ANSCompressLogOperation : XXUnknownSuperclass {
	NSURL* _uncompressedLogURL;
	NSURL* _compressedLogURL;
}
@property(retain, nonatomic) NSURL* uncompressedLogURL;
@property(retain, nonatomic) NSURL* compressedLogURL;
-(void).cxx_destruct;
-(id)compressedURLForUncompressedURL:(id)uncompressedURL;
-(void)main;
-(id)initWithUncompressedLogURL:(id)uncompressedLogURL compressedLogURL:(id)url;
@end

