/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface ANSEventFilter : XXUnknownSuperclass {
}
+(int)javaHashCodeForString:(id)string;
-(BOOL)shouldDiscardEventWithInstallationID:(id)installationID forSamplingFactor:(int)samplingFactor;
-(BOOL)samplingEnabledForEventType:(id)eventType;
-(BOOL)shouldDiscardEvent:(id)event betaToken:(id)token installationID:(id)anId withFactor:(int)factor;
@end

