/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class FABCertificatePinner, NSMutableDictionary;

@interface ANSNetworkRetryHandler : XXUnknownSuperclass {
	FABCertificatePinner* _certPinner;
	NSMutableDictionary* _retryTimerMap;
}
@property(readonly, assign, nonatomic) NSMutableDictionary* retryTimerMap;
@property(readonly, assign, nonatomic) FABCertificatePinner* certPinner;
-(void).cxx_destruct;
-(id)timerForIdentifier:(id)identifier initialRetryValue:(double)value;
-(void)handleCompletedRequest:(id)request withResponse:(id)response forIdentifier:(id)identifier maxRetries:(unsigned)retries error:(id)error completionHandler:(id)handler;
-(void)handleCompletedRequest:(id)request withResponse:(id)response forIdentifier:(id)identifier error:(id)error completionHandler:(id)handler;
-(id)errorWithCode:(int)code forIdentifier:(id)identifier request:(id)request handlerError:(id)error;
-(double)retryValueForResponse:(id)response;
-(void)handleChallenge:(id)challenge fromURLSession:(id)urlsession completionHandler:(id)handler;
-(id)sharedFabricSDK;
-(id)init;
@end

