/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FABKit.h"

@class ANSAnswersController, NSString;

@interface Answers : XXUnknownSuperclass <FABKit> {
	ANSAnswersController* _answersController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) ANSAnswersController* answersController;
+(void)initializeIfNeeded;
+(id)kitBuildVersion;
+(id)kitDisplayVersion;
+(id)bundleIdentifier;
+(void)logCustomEventWithName:(id)name customAttributes:(id)attributes;
+(void)logSearchWithQuery:(id)query customAttributes:(id)attributes;
+(void)logContentViewWithName:(id)name contentType:(id)type contentId:(id)anId customAttributes:(id)attributes;
+(void)logRating:(id)rating contentName:(id)name contentType:(id)type contentId:(id)anId customAttributes:(id)attributes;
+(void)logStartCheckoutWithPrice:(id)price currency:(id)currency itemCount:(id)count customAttributes:(id)attributes;
+(void)logAddToCartWithPrice:(id)price currency:(id)currency itemName:(id)name itemType:(id)type itemId:(id)anId customAttributes:(id)attributes;
+(void)logLevelEnd:(id)end score:(id)score success:(id)success customAttributes:(id)attributes;
+(void)logLevelStart:(id)start customAttributes:(id)attributes;
+(void)logPurchaseWithPrice:(id)price currency:(id)icurrency success:(id)success itemName:(id)name itemType:(id)type itemId:(id)anId customAttributes:(id)attributes;
+(void)logShareWithMethod:(id)method contentName:(id)name contentType:(id)type contentId:(id)anId customAttributes:(id)attributes;
+(void)logLoginWithMethod:(id)method success:(id)success customAttributes:(id)attributes;
+(void)logSignUpWithMethod:(id)method success:(id)success customAttributes:(id)attributes;
+(void)logInviteWithMethod:(id)method customAttributes:(id)attributes;
+(void)logPreviousSessionCrashedOnDate:(id)date;
+(void)startWithBetaToken:(id)betaToken;
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)startWithBetaToken:(id)betaToken;
-(void)configureLogging;
@end

