/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BFCancellationToken, NSObject;

@interface BFCancellationTokenRegistration : XXUnknownSuperclass {
	BOOL _disposed;
	BFCancellationToken* _token;
	id _cancellationObserverBlock;
	NSObject* _lock;
}
@property(assign, nonatomic) BOOL disposed;
@property(retain, nonatomic) NSObject* lock;
@property(copy, nonatomic) id cancellationObserverBlock;
@property(assign, nonatomic) __weak BFCancellationToken* token;
+(id)registrationWithToken:(id)token delegate:(id)delegate;
-(void).cxx_destruct;
-(void)throwIfDisposed;
-(void)notifyDelegate;
-(void)dispose;
-(id)init;
@end

