/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VK_Music-Structs.h"

@class NSTimer;

@interface CCHLinkGestureRecognizer : XXUnknownSuperclass {
	float _allowableMovement;
	int _result;
	NSTimer* _timer;
	double _minimumPressDuration;
	CGPoint _initialPoint;
}
@property(assign, nonatomic) float allowableMovement;
@property(assign, nonatomic) double minimumPressDuration;
@property(retain, nonatomic) NSTimer* timer;
@property(assign, nonatomic) CGPoint initialPoint;
@property(assign, nonatomic) int result;
-(void).cxx_destruct;
-(BOOL)touchIsCloseToInitialPoint:(id)initialPoint;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)longPressed:(id)pressed;
-(void)reset;
-(void)setUp;
-(id)initWithTarget:(id)target action:(SEL)action;
-(id)init;
@end

