/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"
#import "VK_Music-Structs.h"

@class NSDictionary, NSURLCache;

@interface CLSURLSessionConfiguration : XXUnknownSuperclass <NSCopying> {
	NSDictionary* _additionalHeaders;
	NSURLCache* _URLCache;
	unsigned _cookiePolicy;
}
@property(assign, nonatomic) BOOL sessionSendsLaunchEvents;
@property(assign, nonatomic) unsigned HTTPCookieAcceptPolicy;
@property(retain, nonatomic) NSURLCache* URLCache;
@property(copy, nonatomic) NSDictionary* HTTPAdditionalHeaders;
+(id)backgroundSessionConfigurationWithIdentifier:(id)identifier;
+(id)backgroundSessionConfiguration:(id)configuration;
+(id)ephemeralSessionConfiguration;
+(id)defaultSessionConfiguration;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
@end

