/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DDLogFormatter.h"

@class NSArray, DDLoggingContextSet, NSString;

@interface DDContextWhitelistFilterLogFormatter : XXUnknownSuperclass <DDLogFormatter> {
	DDLoggingContextSet* _contextSet;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSArray* whitelist;
-(void).cxx_destruct;
-(id)formatLogMessage:(id)message;
-(BOOL)isOnWhitelist:(unsigned)whitelist;
-(void)removeFromWhitelist:(unsigned)whitelist;
-(void)addToWhitelist:(unsigned)whitelist;
-(id)init;
@end

