/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DDLogFileManager <NSObject>
@property(assign) unsigned long long logFilesDiskQuota;
@property(assign) unsigned maximumNumberOfLogFiles;
-(id)createNewLogFile;
-(id)sortedLogFileInfos;
-(id)sortedLogFileNames;
-(id)sortedLogFilePaths;
-(id)unsortedLogFileInfos;
-(id)unsortedLogFileNames;
-(id)unsortedLogFilePaths;
-(id)logsDirectory;
@optional
-(void)didRollAndArchiveLogFile:(id)file;
-(void)didArchiveLogFile:(id)file;
@end

