/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"
#import "VK_Music-Structs.h"

@class NSString, NSDate;

@interface DDLogMessage : XXUnknownSuperclass <NSCopying> {
	NSString* _message;
	unsigned _level;
	unsigned _flag;
	int _context;
	NSString* _file;
	NSString* _fileName;
	NSString* _function;
	unsigned _line;
	id _tag;
	int _options;
	NSDate* _timestamp;
	NSString* _threadID;
	NSString* _threadName;
	NSString* _queueLabel;
}
@property(readonly, assign, nonatomic) NSString* queueLabel;
@property(readonly, assign, nonatomic) NSString* threadName;
@property(readonly, assign, nonatomic) NSString* threadID;
@property(readonly, assign, nonatomic) NSDate* timestamp;
@property(readonly, assign, nonatomic) int options;
@property(readonly, assign, nonatomic) id tag;
@property(readonly, assign, nonatomic) unsigned line;
@property(readonly, assign, nonatomic) NSString* function;
@property(readonly, assign, nonatomic) NSString* fileName;
@property(readonly, assign, nonatomic) NSString* file;
@property(readonly, assign, nonatomic) int context;
@property(readonly, assign, nonatomic) unsigned flag;
@property(readonly, assign, nonatomic) unsigned level;
@property(readonly, assign, nonatomic) NSString* message;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithMessage:(id)message level:(unsigned)level flag:(unsigned)flag context:(int)context file:(id)file function:(id)function line:(unsigned)line tag:(id)tag options:(int)options timestamp:(id)timestamp;
@end

