/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableString;

@interface FABURLBuilder : XXUnknownSuperclass {
	NSMutableString* _URLString;
	unsigned _queryParams;
}
@property(assign, nonatomic) unsigned queryParams;
@property(retain, nonatomic) NSMutableString* URLString;
+(id)URLWithBase:(id)base;
-(void).cxx_destruct;
-(id)URL;
-(void)appendValue:(id)value forQueryParam:(id)queryParam;
-(void)escapeAndAppendComponent:(id)component;
-(void)appendComponent:(id)component;
-(id)escapeString:(id)string;
-(id)init;
@end

