/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FlurryDataSenderBase.h"
#import "FlurryHttpAsyncTaskDelegate.h"

@class FlurryDataSenderIndex, NSString;

@interface FlurryPulseCBReportSender : FlurryDataSenderBase <FlurryHttpAsyncTaskDelegate> {
	FlurryDataSenderIndex* _pulseCBReportDataIndex;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FlurryDataSenderIndex* pulseCBReportDataIndex;
+(id)pulseCBReportDataKey;
+(Class)httpAsyncTaskClass;
+(void)cleanup;
+(id)instance;
+(void)setupInstanceWithQueue:(id)queue;
-(void).cxx_destruct;
-(void)retransmitNotSentBlocks;
-(void)didCompleteAllTasks;
-(void)requestSuccessComplete:(id)complete withResponse:(id)response;
-(void)requestSuccessful:(id)successful withResponse:(id)response;
-(void)requestDidCancel:(id)request withResponse:(id)response;
-(void)requestDidFail:(id)request withResponse:(id)response;
-(void)sendData:(id)data withIdentifier:(id)identifier;
-(void)sendPulseReportsData:(id)data;
-(void)removeStoredDataWithIdentifier:(id)identifier;
-(id)storePulseCBReportData:(id)data withGrpupId:(id)grpupId;
-(void)setup;
-(id)initWithQueue:(id)queue;
@end

