/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FlurrySessionInfo : XXUnknownSuperclass {
}
+(id)agentVersion;
+(void)setMaxSessions:(int)sessions;
+(int)maxSessions;
+(int)maxTransactions;
+(int)maxErrors;
+(int)maxEventCounts;
+(int)maxEventLogCount;
+(int)maxSessionProperties;
+(int)maxOriginSets;
@end

