/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class NSMutableDictionary, NSString, NSObject;
@protocol OS_dispatch_queue;

@interface FlurryDataSenderIndex : XXUnknownSuperclass <NSCoding> {
	BOOL _sentReportSuccessfully;
	NSMutableDictionary* _indexMap;
	NSString* _fileName;
	NSObject<OS_dispatch_queue>* _indexMapQueue;
}
@property(assign, nonatomic) BOOL sentReportSuccessfully;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* indexMapQueue;
@property(retain, nonatomic) NSString* fileName;
@property(retain, nonatomic) NSMutableDictionary* indexMap;
+(id)instantiatedIndexWithIndexFile:(id)indexFile;
-(void).cxx_destruct;
-(id)notSentBlocksForDataKey:(id)dataKey;
-(BOOL)discardOldBlocksForDataKey:(id)dataKey;
-(BOOL)discardOutdatedBlocksForDataKey:(id)dataKey;
-(void)setupForCurrentDataKey:(id)currentDataKey;
-(void)removeBlockInfoWithIdentifier:(id)identifier forDataKey:(id)dataKey;
-(void)addBlockInfo:(id)info forDataKey:(id)dataKey;
-(void)saveState;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)init;
@end

