/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class VK_ProfileInfoModel, NSString;

__attribute__((visibility("hidden")))
@interface VK_AuthorizationCache : XXUnknownSuperclass {
	VK_ProfileInfoModel* _userInfo;
	NSString* _passKey;
}
@property(retain, nonatomic) NSString* passKey;
@property(retain, nonatomic) VK_ProfileInfoModel* userInfo;
-(void).cxx_destruct;
-(void)removeData;
-(void)loadData;
-(void)saveData;
@end

