/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_ApiResponse.h"

@class VK_AlbumInfoModel;

__attribute__((visibility("hidden")))
@interface VK_AlbumResponse : VK_ApiResponse {
	VK_AlbumInfoModel* _data;
}
@property(retain, nonatomic) VK_AlbumInfoModel* data;
+(void)internalInitMapping:(id)mapping;
-(void).cxx_destruct;
@end

