/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_BaseViewController.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VK_ArtistViewController : VK_BaseViewController {
	NSString* _artistId;
}
@property(retain, nonatomic) NSString* artistId;
-(void).cxx_destruct;
@end

