/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_FavoritesManagerOperation.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VK_AddFavoriteTrackOperation : VK_FavoritesManagerOperation {
	NSString* _trackId;
}
@property(retain, nonatomic) NSString* trackId;
-(void).cxx_destruct;
-(id)internalCreateRequest;
@end

