/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VK_DataAuthorizationHandler.h"

@class NSString, VK_LoaderViewController;

__attribute__((visibility("hidden")))
@interface VK_AuthorizationHandler : XXUnknownSuperclass <VK_DataAuthorizationHandler> {
	BOOL _inProcess;
	BOOL _needHideAuthVCAfterCompletion;
	id _completeBlock;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL needHideAuthVCAfterCompletion;
@property(readonly, assign) VK_LoaderViewController* authLoaderViewController;
@property(copy, nonatomic) id completeBlock;
@property(assign, nonatomic) BOOL inProcess;
+(id)shared;
-(void).cxx_destruct;
-(void)startVKAuthorization;
-(void)completeWithUserId:(id)userId andAccessToken:(id)token;
-(void)updatePassKey;
-(void)setup;
-(void)authorizationCompletedWithUserId:(id)userId andAccessToken:(id)token;
-(void)startLoginWithCompletion:(id)completion;
-(id)init;
@end

