/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface VK_Analitic : XXUnknownSuperclass {
}
+(unsigned short)feedBlockAsAnaliticBlock:(int)block;
+(void)trackAudioID:(unsigned long long)anId ownerId:(unsigned long long)anId2 umaProductId:(unsigned)anId3 commercModel:(id)model timeStart:(double)start timeEnd:(double)end useType:(unsigned short)type;
+(void)trackAction:(unsigned short)action withScreen:(unsigned short)screen withBlock:(unsigned short)block;
+(void)trackAction:(unsigned short)action withBlock:(unsigned short)block;
+(void)trackAction:(unsigned short)action;
+(void)trackScreen:(unsigned short)screen;
+(void)trackScreenAsCurrent:(unsigned short)current;
+(void)initialize;
@end

