/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_BaseTableViewController.h"
#import "VK_Music-Structs.h"


__attribute__((visibility("hidden")))
@interface VK_AudioPlayerModalViewController : VK_BaseTableViewController {
	id _data;
}
@property(retain, nonatomic) id data;
-(void).cxx_destruct;
-(void)statusBarTouched;
-(void)closeModalViewController;
-(void)internalConfigureNavigationBarButtons;
-(void)internalCloseModalViewController;
-(UIEdgeInsets)internalAdditionalTableContentInset;
-(void)internalConfigureTitleLabel:(id)label;
-(void)prepareNavigationBarButtons;
-(void)internalSetup;
-(void)dealloc;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
@end

