/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface VK_BarAnimationLayer : XXUnknownSuperclass {
	BOOL _needToStartAnimation;
	float _barCornerRadius;
	double _animationDuration;
	double _animationTimeOffset;
}
@property(assign, nonatomic) BOOL needToStartAnimation;
@property(assign, nonatomic) float barCornerRadius;
@property(assign, nonatomic) double animationTimeOffset;
@property(assign, nonatomic) double animationDuration;
-(void)interruptAnimationWithKey:(id)key;
-(void)addRestoreAnimation;
-(void)addBarAnimation;
-(void)stopAnimation;
-(void)startAnimation;
-(id)defaultPath;
@end

