/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VK_Music-Structs.h"


__attribute__((visibility("hidden")))
@interface VK_BaseLabel : XXUnknownSuperclass {
}
-(void)layoutSubviews;
-(void)internalLabelSetup;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
@end

