/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAppearanceContainer.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "VK_Music-Structs.h"

@class NSArray, UIColor, NSString;

__attribute__((visibility("hidden")))
@interface VK_DashedLineView : XXUnknownSuperclass <UIAppearanceContainer> {
	int _direction;
	float _phase;
	NSArray* _lengthPattern;
	UIColor* _lineColor;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIColor* lineColor;
@property(retain, nonatomic) NSArray* lengthPattern;
@property(assign, nonatomic) float phase;
@property(assign, nonatomic) int direction;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)commonInit;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
@end

