/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_TableCellProxy.h"


__attribute__((visibility("hidden")))
@interface VK_FeedViewNoteFullTextCellProxy : VK_TableCellProxy {
	BOOL _isPostText;
	id _onLinkTapBlock;
	id _onNoteLinkProfileTapBlock;
}
@property(assign, nonatomic) BOOL isPostText;
@property(copy, nonatomic) id onNoteLinkProfileTapBlock;
@property(copy, nonatomic) id onLinkTapBlock;
-(void).cxx_destruct;
-(Class)viewModelClass;
-(Class)cellClass;
@end

