/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_TableControllerBaseConfiguration.h"

@protocol VK_FeedDataProvider;

__attribute__((visibility("hidden")))
@interface VK_FeedTableControllerConfiguration : VK_TableControllerBaseConfiguration {
	id<VK_FeedDataProvider> _feedDataProvider;
	id _prepareDataAllocatorBlock;
}
@property(copy, nonatomic) id prepareDataAllocatorBlock;
@property(retain, nonatomic) id<VK_FeedDataProvider> feedDataProvider;
-(void).cxx_destruct;
-(void)trackShowAllButtonPressed:(int)pressed;
-(void)prepareMonthNewsCells:(id)cells;
-(void)prepareNewReleaseCells:(id)cells;
-(void)prepareNewFriendsCells:(id)cells;
-(void)prepareRecommendationCells:(id)cells;
-(void)createFeedTrackListProviderForTrackCellConfiguration:(id)trackCellConfiguration;
-(void)preparePostCells:(id)cells;
-(void)applyToTableController:(id)tableController;
-(id)internalDataProvider;
-(id)internalTableViewDataAllocator;
@end

