/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "EKMappingProtocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VK_FeedBaseBlockModel : XXUnknownSuperclass <EKMappingProtocol> {
	BOOL _isRemoved;
	int _type;
	NSString* _blockId;
}
@property(assign, nonatomic) BOOL isRemoved;
@property(retain, nonatomic) NSString* blockId;
@property(assign, nonatomic) int type;
@property(readonly, assign, nonatomic) BOOL isPostRepost;
+(id)objectMapping;
+(id)createBlockModelFromDictionary:(id)dictionary;
-(void).cxx_destruct;
-(id)init;
-(id)asMonthNewsModel;
-(id)asNewReleaseBlockModel;
-(id)asRecommendationBlock;
-(id)asNewFriends;
-(id)asNote;
@end

