/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_Music-Structs.h"
#import "VK_TableViewCellBase.h"

@class UILabel, VK_Button, VK_FeedNewReleaseBlockModel, VK_ImageManagerOperation, VK_FeedViewNewReleaseCellProxy, VK_FeedViewNewReleaseCellViewModel;

__attribute__((visibility("hidden")))
@interface VK_FeedViewNewReleaseCell : VK_TableViewCellBase {
	VK_Button* _coverBtn;
	VK_Button* _albumNameBtn;
	VK_Button* _artistNameBtn;
	UILabel* _yearGenresLabel;
	VK_ImageManagerOperation* _coverImageLoadingOperation;
}
@property(retain, nonatomic) VK_ImageManagerOperation* coverImageLoadingOperation;
@property(assign, nonatomic) __weak UILabel* yearGenresLabel;
@property(assign, nonatomic) __weak VK_Button* artistNameBtn;
@property(assign, nonatomic) __weak VK_Button* albumNameBtn;
@property(assign, nonatomic) __weak VK_Button* coverBtn;
@property(readonly, assign, nonatomic) VK_FeedViewNewReleaseCellViewModel* viewModel;
@property(readonly, assign, nonatomic) VK_FeedViewNewReleaseCellProxy* proxy;
@property(readonly, assign, nonatomic) VK_FeedNewReleaseBlockModel* data;
-(void).cxx_destruct;
-(void)cancelLoadingCoverImage;
-(void)updateCoverImage:(id)image withCacheFlag:(BOOL)cacheFlag;
-(void)loadCoverImage;
-(void)createViews;
-(void)artistNamePressed:(id)pressed;
-(void)onAlbumPressed;
-(void)albumNamePressed:(id)pressed;
-(void)coverBtnPressed:(id)pressed;
-(void)internalReset;
-(void)internalUpdateData;
-(void)layoutSubviews;
-(void)internalSetup;
@end

