/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_Music-Structs.h"
#import "VK_TableViewCellBase.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDataSource.h"

@class NSArray, UICollectionView, NSCache, VK_FeedMonthNewsCellProxy, VK_FeedMonthNewsBlockModel, NSString;

__attribute__((visibility("hidden")))
@interface VK_FeedMonthNewsCell : VK_TableViewCellBase <UICollectionViewDelegate, UICollectionViewDataSource> {
	UICollectionView* _collectionView;
	NSArray* _albumsData;
	NSCache* _coversCache;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSCache* coversCache;
@property(readonly, assign, nonatomic) VK_FeedMonthNewsBlockModel* data;
@property(retain, nonatomic) NSArray* albumsData;
@property(retain, nonatomic) UICollectionView* collectionView;
@property(readonly, assign, nonatomic) VK_FeedMonthNewsCellProxy* proxy;
-(void).cxx_destruct;
-(void)collectionView:(id)view didSelectItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view didEndDisplayingCell:(id)cell forItemAtIndexPath:(id)indexPath;
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;
-(int)numberOfSectionsInCollectionView:(id)collectionView;
-(void)createViews;
-(void)internalUpdateProxy;
-(void)internalUpdateData;
-(void)internalSetup;
@end

