/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VK_Music-Structs.h"

@class UIView, NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface VK_ImagesTiles : XXUnknownSuperclass {
	UIView* _contentView;
	NSMutableArray* _cachedImageViews;
	NSMutableArray* _imageViews;
	NSArray* _viewsConfigurations;
	NSArray* _imagesUrls;
	CGSize _estimatedViewSize;
}
@property(retain, nonatomic) NSArray* imagesUrls;
@property(retain, nonatomic) NSArray* viewsConfigurations;
@property(retain, nonatomic) NSMutableArray* imageViews;
@property(retain, nonatomic) NSMutableArray* cachedImageViews;
@property(assign, nonatomic) CGSize estimatedViewSize;
@property(assign, nonatomic) __weak UIView* contentView;
-(void).cxx_destruct;
-(id)configurationFor9Images;
-(id)configurationFor8Images;
-(id)configurationFor7Images;
-(id)configurationFor6Images;
-(id)configurationFor5Images;
-(id)configurationFor4Images;
-(id)configurationFor3Images;
-(id)configurationFor2Images;
-(id)configurationFor1Image;
-(id)imagesRectsForConfiguration:(id)configuration;
-(id)imagesRectsForConfiguration:(id)configuration withWorkingRect:(CGRect)workingRect;
-(void)setupCachedImageViews;
-(void)updateImagesViewsForImagesCount:(unsigned)imagesCount;
-(void)resetImages;
-(void)setup;
-(void)showWithImagesURLs:(id)imagesURLs;
-(void)showWithPhotos:(id)photos;
-(id)initWithContentView:(id)contentView andEstimatedSize:(CGSize)size;
@end

