/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_BaseManager.h"


__attribute__((visibility("hidden")))
@interface VK_MyAudioManager : VK_BaseManager {
}
+(id)currentManager;
-(void)postNotification:(id)notification withTrack:(id)track;
-(void)removeFromMyAudio:(id)myAudio;
-(void)addToMyAudio:(id)myAudio;
@end

