/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol VK_NetworkReachabilitySubscriber <NSObject>
@optional
-(void)networkReachability:(id)reachability networkReachableChanged:(BOOL)changed;
-(void)networkReachability:(id)reachability networkStatusChanged:(int)changed;
@end

