/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_TableViewCellBase.h"
#import "VK_Music-Structs.h"

@class UILabel, UIImageView, UIView;

__attribute__((visibility("hidden")))
@interface VK_NeedSyncCell : VK_TableViewCellBase {
	UILabel* _titleLabel;
	UIImageView* _syncIcon;
	UIView* _selectionView;
}
@property(assign, nonatomic) __weak UIView* selectionView;
@property(assign, nonatomic) __weak UIImageView* syncIcon;
@property(assign, nonatomic) __weak UILabel* titleLabel;
+(float)estimatedHeight;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)internalSetup;
@end

