/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_AuthorizedApiRequest.h"

@class NSString, VK_ProfileResponse;

__attribute__((visibility("hidden")))
@interface VK_ProfileRequest : VK_AuthorizedApiRequest {
	NSString* _userId;
}
@property(readonly, assign, nonatomic) VK_ProfileResponse* response;
@property(retain, nonatomic) NSString* userId;
-(void).cxx_destruct;
-(id)internalResponseModelMapping;
-(void)internalInitRequestParams:(id)params;
-(id)internalBuildRequestCommand;
@end

