/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_ApiResponse.h"

@class NSString, NSArray;

__attribute__((visibility("hidden")))
@interface VK_ProfilesResponse : VK_ApiResponse {
	NSArray* _profiles;
	NSString* _ref;
}
@property(retain, nonatomic) NSString* ref;
@property(retain, nonatomic) NSArray* profiles;
+(void)internalInitMapping:(id)mapping;
-(void).cxx_destruct;
@end

