/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class VK_BaseLabel, VK_Button, NSLayoutConstraint, UIImageView;

__attribute__((visibility("hidden")))
@interface VK_ProfileMessageView : XXUnknownSuperclass {
	VK_BaseLabel* _messageLabel;
	VK_Button* _actionButton;
	NSLayoutConstraint* _messageLabelBottomMaxConstraint;
	UIImageView* _lockView;
	NSLayoutConstraint* _containerVerticalCenterConstraint;
	id _actionBlock;
}
@property(copy, nonatomic) id actionBlock;
@property(assign, nonatomic) __weak NSLayoutConstraint* containerVerticalCenterConstraint;
@property(assign, nonatomic) __weak UIImageView* lockView;
@property(assign, nonatomic) __weak NSLayoutConstraint* messageLabelBottomMaxConstraint;
@property(assign, nonatomic) __weak VK_Button* actionButton;
@property(assign, nonatomic) __weak VK_BaseLabel* messageLabel;
-(void).cxx_destruct;
-(void)actionButtonPressed:(id)pressed;
-(void)configure;
-(void)hideMessage;
-(void)setVerticalOffset:(float)offset;
-(void)showMessageWithText:(id)text image:(id)image actionText:(id)text3 andActionBlock:(id)block;
-(void)awakeFromNib;
-(id)init;
@end

