/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_ProfilesResponse.h"


__attribute__((visibility("hidden")))
@interface VK_ProfilesSequenceResponse : VK_ProfilesResponse {
}
+(void)internalInitMapping:(id)mapping;
@end

