/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_TracksProviderBase.h"
#import "VK_DataWithTracksShuffleableProvider.h"
#import "VK_Music-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VK_ShuffleableTracksProvider : VK_TracksProviderBase <VK_DataWithTracksShuffleableProvider> {
	BOOL _shuffled;
}
@property(readonly, assign, nonatomic) BOOL isCanFetch;
@property(readonly, assign, nonatomic) BOOL isFetching;
@property(readonly, assign, nonatomic) BOOL isAllDataLoaded;
@property(readonly, assign, nonatomic) id customData;
@property(readonly, assign, nonatomic) id actualData;
@property(readonly, assign, nonatomic) id data;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL shuffled;
-(void)reloadWithOffset:(unsigned)offset;
-(id)internalCreatePagedRequestWithShuffleEnabled:(BOOL)shuffleEnabled;
-(id)internalCreatePagedRequest;
-(void)internalDidDataChanged;
-(void)unshuffleFromTrack:(id)track;
-(void)shuffleFromTrack:(id)track;
-(id)createTrackListProviderFromTrack:(id)track;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

