/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VK_Music-Structs.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface VK_SegmentControl : XXUnknownSuperclass {
	id _action;
	NSArray* _segmentTitles;
}
@property(retain, nonatomic) NSArray* segmentTitles;
@property(copy, nonatomic) id action;
-(void).cxx_destruct;
-(void)action:(id)action;
-(void)setupDefaultActions;
-(void)setupDefaultAppearance;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
@end

