/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_BaseManager.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VK_SubscriptionsManager : VK_BaseManager {
	BOOL _scheduleUpdatingEnabled;
	BOOL _isScheduleReloading;
	NSString* _contentEncryptionKey;
	unsigned _internalStatus;
	double _tariffEndPeriod;
	double _tariffServerTime;
}
@property(readonly, assign, nonatomic) unsigned internalStatus;
@property(readonly, assign, nonatomic) unsigned status;
@property(assign, nonatomic) BOOL scheduleUpdatingEnabled;
@property(readonly, assign, nonatomic) NSString* contentEncryptionKey;
@property(readonly, assign, nonatomic) BOOL isValidTime;
@property(assign, nonatomic) BOOL isScheduleReloading;
@property(readonly, assign, nonatomic) BOOL isHaveSecureKey;
@property(assign, nonatomic) double tariffServerTime;
@property(assign, nonatomic) double tariffEndPeriod;
+(id)currentManager;
-(void).cxx_destruct;
-(void)resetData;
-(id)secureKeyRequestTask;
-(BOOL)validateSecureKey:(id)key;
-(void)setNewSecureKey:(id)key;
-(void)loadSecureKey;
-(void)networkStatusDidChanged;
-(void)onTariffDidChanged;
-(void)onStatusChangedNotificate;
-(void)timeValidationStatusDidChanged;
-(void)internalWillUserDataUnload;
-(void)internalNeedLoadUserData;
-(void)setInternalStatus:(unsigned)status withSaving:(BOOL)saving;
-(void)setInternalStatus:(unsigned)status;
-(BOOL)validate;
-(void)scheduleSubscriptionsChanging;
-(void)internalLoadNewSecureKeyWithCompletion:(id)completion;
-(void)showSubscriptionsMessageWithNewStatus:(unsigned)newStatus andPrevStatus:(unsigned)status;
-(void)onSubscriptionsChangingFailed;
-(void)scheduleReloadSubscriptions;
-(void)reloadSubscriptionsWithCompletion:(id)completion;
-(void)dealloc;
-(id)init;
-(id)reloadSubscriptionsTask;
@end

