/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_AuthorizedApiRequest.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface VK_SetOptionsRequest : VK_AuthorizedApiRequest {
	NSNumber* _isMusicVisible;
}
@property(retain, nonatomic) NSNumber* isMusicVisible;
-(void).cxx_destruct;
-(void)internalInitRequestParams:(id)params;
-(id)internalBuildRequestCommand;
-(BOOL)internalCachingSupported;
@end

