/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_ApiResponse.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface VK_TracksDataResponse : VK_ApiResponse {
	NSArray* _tracksData;
}
@property(retain, nonatomic) NSArray* tracksData;
+(void)internalInitMapping:(id)mapping;
-(void).cxx_destruct;
@end

