/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_AuthorizedApiRequest.h"

@class VK_TariffsResponse;

__attribute__((visibility("hidden")))
@interface VK_TariffsRequest : VK_AuthorizedApiRequest {
}
@property(readonly, assign, nonatomic) VK_TariffsResponse* response;
-(id)internalResponseModelMapping;
-(void)internalInitRequestParams:(id)params;
-(id)internalBuildRequestCommand;
-(BOOL)internalCachingSupported;
@end

