/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_BaseManager.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface VK_TimeManager : VK_BaseManager {
	BOOL _isValidTime;
	NSTimer* _timerForTimeValidation;
	double _lastServerTime;
	double _lastValidTime;
	double _lastServerAbsoluteTime;
}
@property(readonly, assign, nonatomic) double absoluteTime;
@property(readonly, assign, nonatomic) double actualTime;
@property(readonly, assign, nonatomic) BOOL isValidTime;
@property(readonly, assign, nonatomic) double serverTime;
@property(readonly, assign, nonatomic) double localTime;
@property(retain, nonatomic) NSTimer* timerForTimeValidation;
@property(assign, nonatomic) double lastServerAbsoluteTime;
@property(assign, nonatomic) double lastValidTime;
@property(assign, nonatomic) double lastServerTime;
+(id)shared;
-(void).cxx_destruct;
-(void)setIsValidTime:(BOOL)time;
-(void)onValidateTimeOffline;
-(void)onValidateTimeOnline;
-(void)saveData;
-(void)loadData;
-(void)setupServerTime:(double)time;
-(void)startOnlineValidation;
-(void)startOfflineValidation;
-(void)resetTimer;
-(void)dealloc;
-(id)init;
@end

