/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_DataTable.h"


__attribute__((visibility("hidden")))
@interface VK_TrackTable : VK_DataTable {
}
+(id)notDownloadedPredicate;
-(unsigned)countByImage:(id)image;
-(id)getTracksByAlbum:(id)album;
-(id)getNotDownloaded;
-(id)firstNotDownloaded;
-(id)getByManagedId:(id)anId;
-(id)initWithModel:(id)model;
@end

