/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_UserProfilesSequenceRequest.h"


__attribute__((visibility("hidden")))
@interface VK_UserFollowersRequest : VK_UserProfilesSequenceRequest {
}
-(id)internalBuildRequestCommand;
@end

