/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VK_SearchRequestBase.h"

@class VK_UserAudioSearchResponse;

__attribute__((visibility("hidden")))
@interface VK_UserAudioSearchRequest : VK_SearchRequestBase {
}
@property(readonly, assign, nonatomic) VK_UserAudioSearchResponse* response;
-(id)internalResponseModelMapping;
-(id)internalBuildRequestCommand;
@end

