/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VK_Music-Structs.h"

@class NSArray, CALayer, UIColor;

__attribute__((visibility("hidden")))
@interface VK_WaveAnimationView : XXUnknownSuperclass {
	NSArray* _bars;
	CALayer* _transformLayer;
	BOOL _animationInited;
	BOOL _animating;
	UIColor* _color;
	float _barCornerRadius;
}
@property(assign, nonatomic) float barCornerRadius;
@property(retain, nonatomic) UIColor* color;
@property(readonly, assign, nonatomic, getter=isAnimating) BOOL animating;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)initAnimationIfNeeded;
-(id)barAnimationLayerWithFrame:(CGRect)frame animationDuration:(double)duration animationTimeOffset:(double)offset;
-(void)resetAnimation;
-(void)stopAnimation;
-(void)startAnimation;
-(id)initWithFrame:(CGRect)frame;
-(void)awakeFromNib;
-(void)setup;
@end

