/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class VKShareDialogController;

@interface VKActivity : XXUnknownSuperclass {
	VKShareDialogController* _shareDialog;
}
@property(retain, nonatomic) VKShareDialogController* shareDialog;
+(BOOL)vkShareExtensionEnabled;
+(int)activityCategory;
-(void).cxx_destruct;
-(id)activityViewController;
-(void)prepareWithActivityItems:(id)activityItems;
-(BOOL)canPerformWithActivityItems:(id)activityItems;
-(id)activityTitle;
-(id)activityImage;
-(id)activityType;
@end

