/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKApiObject.h"

@class NSString, NSNumber;

@interface VKDocs : VKApiObject {
	NSNumber* _id;
	NSNumber* _owner_id;
	NSString* _title;
	NSNumber* _size;
	NSString* _ext;
	NSString* _url;
	NSString* _photo_100;
	NSString* _photo_130;
	NSNumber* _date;
	NSNumber* _type;
}
@property(retain, nonatomic) NSNumber* type;
@property(retain, nonatomic) NSNumber* date;
@property(copy, nonatomic) NSString* photo_130;
@property(copy, nonatomic) NSString* photo_100;
@property(copy, nonatomic) NSString* url;
@property(copy, nonatomic) NSString* ext;
@property(retain, nonatomic) NSNumber* size;
@property(copy, nonatomic) NSString* title;
@property(retain, nonatomic) NSNumber* owner_id;
@property(retain, nonatomic) NSNumber* id;
-(void).cxx_destruct;
@end

