/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKApiObject.h"

@class NSString, NSNumber;

@interface VKGroupContact : VKApiObject {
	NSNumber* _user_id;
	NSString* _desc;
	NSString* _email;
}
@property(retain, nonatomic) NSString* email;
@property(retain, nonatomic) NSString* desc;
@property(retain, nonatomic) NSNumber* user_id;
-(void).cxx_destruct;
@end

