/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKApiObject.h"

@class NSString, NSNumber, VKPhotoSizes;

@interface VKPhoto : VKApiObject {
	NSNumber* _id;
	NSNumber* _album_id;
	NSNumber* _owner_id;
	NSString* _photo_75;
	NSString* _photo_130;
	NSString* _photo_604;
	NSString* _photo_807;
	NSString* _photo_1280;
	NSString* _photo_2560;
	NSNumber* _width;
	NSNumber* _height;
	NSString* _text;
	NSNumber* _date;
	VKPhotoSizes* _sizes;
}
@property(readonly, assign, nonatomic) NSString* attachmentString;
@property(retain, nonatomic) VKPhotoSizes* sizes;
@property(retain, nonatomic) NSNumber* date;
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) NSNumber* height;
@property(retain, nonatomic) NSNumber* width;
@property(retain, nonatomic) NSString* photo_2560;
@property(retain, nonatomic) NSString* photo_1280;
@property(retain, nonatomic) NSString* photo_807;
@property(retain, nonatomic) NSString* photo_604;
@property(retain, nonatomic) NSString* photo_130;
@property(retain, nonatomic) NSString* photo_75;
@property(retain, nonatomic) NSNumber* owner_id;
@property(retain, nonatomic) NSNumber* album_id;
@property(retain, nonatomic) NSNumber* id;
-(void).cxx_destruct;
@end

