/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKObject.h"

@class NSDate;

@interface VKRequestTiming : VKObject {
	NSDate* _parseStartTime;
	NSDate* _startTime;
	NSDate* _finishTime;
	double _loadTime;
	double _parseTime;
}
@property(readonly, assign, nonatomic) double totalTime;
@property(assign, nonatomic) double parseTime;
@property(assign, nonatomic) double loadTime;
@property(retain, nonatomic) NSDate* finishTime;
@property(retain, nonatomic) NSDate* startTime;
-(void).cxx_destruct;
-(void)finished;
-(void)parseFinished;
-(void)parseStarted;
-(void)loaded;
-(void)started;
-(id)description;
@end

