/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "VKObject.h"
#import "VK_Music-Structs.h"

@class UIImage, NSString, VKRequest;

@interface VKUploadingAttachment : VKObject {
	BOOL _isDownloading;
	NSString* _attachmentString;
	UIImage* _preview;
	VKRequest* _uploadingRequest;
	CGSize _attachSize;
}
@property(assign, nonatomic) __weak VKRequest* uploadingRequest;
@property(retain, nonatomic) UIImage* preview;
@property(retain, nonatomic) NSString* attachmentString;
@property(assign, nonatomic) CGSize attachSize;
@property(assign, nonatomic) BOOL isDownloading;
-(void).cxx_destruct;
@end

